### ISSUE TITLE
How to include Forge bundle in a js file?

### ISSUE THREAD

**Issue by wolvz** [digitalbazaar/forge#119]
Hello!

This isn't exactly an issue, but I really need some help on how to use forge library in a js file.
I created forge.bundle.js with "npm install" and "npm run bundle".

I can't use < script src = "js/forge.bundle.js" > < / script > because the file is "pure" javascript.

I did some research and I know that there is a javascript module loader named "RequireJS" but I can't figure out how to "include" the forge library and how to use its functions.

I tried, by loading the requirejs module (pdf.js has worker_loader.js, where I can add requirejs to be loaded) and using the following code in the function where I need the forge code.

require(['forge.bundle'], function (forge) {
    var p7 = forge.pkcs7.messageFromPem("test");
});

I get this error:
Uncaught ReferenceError: window is not defined Uncaught Error: Load
timeout for modules: forge.bundle

Can anyone give me a hint of how can I do it, please? Thanks in advance.

**Comment by MikeGads** [comment]
I have node-forge working in my server (JS in Node) with var forge = require(`node-forge`); using CommonJS but my client side is struggling top get it installed. I use React so packages usually include with an import  { forge }   from   = "node-forge"; but that comes up undefined... I must missed this on the examples.
