### ISSUE TITLE
Extract p12 key and certificate

### ISSUE THREAD

**Issue by vdininski** [digitalbazaar/forge#121]
Is there an easy way to extract the private key and certificate and its x.509 certificate using forge from a p12/pfx archive as I am unable to find a comprehensive example for this (knowing the password of course)?

Essentially what I need to do is close to this in openssl:
`openssl pkcs12 -in somefile.p12 -out otherfile.pem`

and then read the .pem file

**Comment by joaovelozo** [comment]
I need help the certificate is inside but I can't find it, how do I disable this call to stop giving this error?


  [Exception]
  Can't find the .p12 certificate in: /var/www/vhosts/com.com.br/httpdocs/storage/laravel-analytics/
