### ISSUE TITLE
browserifying forge

### ISSUE THREAD

**Issue by mvhenten** [digitalbazaar/forge#126]
Hi,

After strugging for quite some time, I've come to realize that browserify does not play well with the AMD support built into forge.  I want to use browserify as part of my tool chain for some particular reasons - getting things to work in webworkers is one of them.

While reading the sources, I figured out how to rewrite the parts I need using esprima. This entails rewriting the sourcecode significantly automatically.

While playing with esprima, it prove to work a lot better then I had anticipated. I've published some of the work to Github, but I'd like to have your consent in doing so, especialy for publishing this to npmjs.

Curious for your thoughts, and many thanks for your work...

https://github.com/mvhenten/browserify-forge-aes-crypt

**Comment by dlongley** [comment]
Addressed by #456.
