### ISSUE TITLE
web workers prime.js

### ISSUE THREAD

**Issue by slxcc** [digitalbazaar/forge#129]
When a worker is created to generate a RSA keypair and the script url is not explicitly given the implementation defaults to "forge/prime.worker.js" (prime.js:154).
This path does not seems to match the actual layout of the project ?
The minification doesn't seems to keep a separate prime.worker.js ?

**Comment by dlongley** [comment]
Addressed by #456.

**Comment by siprikorea** [comment]
Is there a way to get primes without using workers? I tested on http server, not https server, but could not use webcrypto api on the http server. So 'forge' use prime.worker.js to generate the key in pure JavaScript, but the 'prime.worker.js' file is not bundled with the product, so I want to generate the key without using worker. Is there a way to generate a key without using a worker?

**Comment by JensPanisPXL** [comment]
> Is there a way to get primes without using workers? I tested on http server, not https server, but could not use webcrypto api on the http server. So 'forge' use prime.worker.js to generate the key in pure JavaScript, but the 'prime.worker.js' file is not bundled with the product, so I want to generate the key without using worker. Is there a way to generate a key without using a worker?

Have you found out if it works with HTTPS?
