### ISSUE TITLE
AES string encode

### ISSUE THREAD

**Issue by benzmuircroft** [digitalbazaar/forge#134]
I cannot find any docs on here (even, issues), nothing really on google eather, or stackoverflow...

How do you encode a string with AES?

Notice how the "Message" is type string in CryptoJS:

var encrypted = CryptoJS.AES.encrypt("Message", "Secret Passphrase");

var decrypted = CryptoJS.AES.decrypt(encrypted, "Secret Passphrase");

You only show a buffer in your examples, but you don't show what that buffer is. How can a string be encoded and decoded with forge please?

Start as string, end as string... a simple example is missing from the docs, like the CryptoJS example.

**Comment by sgofman** [comment]
@dlongley 
Hello Dave, maybe you can also help me on this great thread with some issue signing CSR. We create CSR with two additional attributes: extensionRequest and challengePassword and sign it using csr.sign . We noticed that when we use a long challengePassword attribute (92 chars) the validation of CSR request fails. For shorter challengePassword input the CSR verification works just fine. 
I found some suspicious lines under asn1.toDer that deal with csr length > 127 , do you know maybe if this code works properly for such scenario ? 
Thank you for your help !

**Comment by dlongley** [comment]
@sgofman,

Could you open a new issue for the problem you're experiencing and provide a minimal, runnable code example? We'll be better able to assist you that way.
