### ISSUE TITLE
RSA decrypt with Public Key

### ISSUE THREAD

**Issue by wolvz** [digitalbazaar/forge#144]
Hello!
I'm trying to decrypt a signature value with forge.pki.rsa.decrypt, but the output array is empty. Why is that happening? Is it a bug?

I'm doing this:

var signed = "6bfd7226e101c2874630174ba846b92aa4d824d8bb5ff2b7404f776f0668e18b3d7c66945b7616505668b194639d4a75d09fa62299ad769964c0711c953b126526a5bbb0474d44aa373c09951ad60411cb3c576fb338314c5e697d6c9f366f1e50eedc3734894d5ca1372c79a4359a569ea146926275878381ba4e7e98957882";
var bytes = hexToBytes(signed);
var decrypted = forge.pki.rsa.decrypt(bytes,p7.certificates[0].publicKey,true,false);

**Comment by stocktonchow** [comment]
> 
> 
> Thanks @davidlehn and @dlongley. Problem solved! :)

hi wolvz, would you please share your solution? I face the same problem as you. It lack of reference for showing decrypt signed message and verify the signature. Thank you.
