### ISSUE TITLE
How to create a root CA certificate and store it as *.crt ?

### ISSUE THREAD

**Issue by SunboX** [digitalbazaar/forge#152]
Hi, I found a sample how to create a self singed certificate here: https://github.com/digitalbazaar/forge/blob/master/tests/nodejs-create-cert.js

But how do I create a custom root CA to store on my Android Device for validating this self signed certificate created above?

I know I can do this using openssl, but could it be done using forge?

**Comment by joshenders** [comment]
> Hi,
> 
> I am dealing with the same "Error: Integer too large; max is 32-bits.". But, what I am doing is creating a PKCS7 signature from two certificates for a passbook server.
> 
> ```
> var p7 = forge.pkcs7.createSignedData();
> p7.addCertificate(fs.readFileSync(certificates.appleWWDRCA));
> p7.addCertificate(fs.readFileSync(certificates.certificate));
> var pem = forge.pkcs7.messageToPem(p7);
> ```
> 
> The issue happens when 'messageToPem(p7)' is called. But, since the certificates used here are generated by Apple, not sure how to use 'forge.pki.createCertificate'.

I recognize it was 5 years ago but do you recall how you resolved this? I'm in the same situation trying to create a PKCS7 signature with a certificate generated by Apple.

**Comment by jay-stance** [comment]
Please I can't still find the code on how to sign a certificate using the CA in the readme.MD file
