### ISSUE TITLE
RC4

### ISSUE THREAD

**Issue by jduncanator** [digitalbazaar/forge#162]
I think there should be a discussion on whether to implement RC4 as an available cipher suite or not. I understand it is a broken cipher but in my opinion it is not upto us to decide what should and shouldn't be used. To provide a full TLS1.0 implementation we need to support RC4. A lot of websites out there force RC4 on their users so it would be nice to have support for it.

Also, a lot of other applications hard code in RC4 support, so having RC4 available via the Forge API would be really nice.

**Comment by dlongley** [comment]
Everyone is shutting off RC4 completely these days, so I think there is very little value in implementing it. I'm going to close this issue.

**Comment by jduncanator** [comment]
That's fine, the use case I was planning on using it for is well and truly been and gone!
