### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by cschram** [digitalbazaar/forge#175]
It would be nice to have [bower](http://bower.io) support in Forge, and register it in the bower repo. Currently I just have Forge tracked in my `bower.json` by git repo URL and version tag.

**Comment by henry74** [comment]
Have installed forge with bower, but cannot access the forge methods.  console.log(forge) returns Object {disableNativeCode: false}

I'm assuming forge is undefined and getting this set based on the code in forge.js:
```
    if(typeof forge === 'undefined') {
      // set to true to disable native code if even it's available
      forge = {disableNativeCode: false};
    }
```
I'm using AngularJS - do I need to include/inject something specifically?
