### ISSUE TITLE
PKCS#7 Signer

### ISSUE THREAD

**Issue by Bibo1978** [digitalbazaar/forge#190]
The Sign function in the PKCS#7 is broken, there is no actual implementation for the sign function or even for the digest info creation also signing parameters aren't considered
The suggested code should be like this

      if('content' in msg) {
        throw new Error('PKCS#7 signing not yet implemented.');
       }

      if(typeof msg.content !== 'object') {
        // use Data ContentInfo
        msg.contentInfo = asn1.create(
          asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
            // ContentType
            asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OID, false,
              asn1.oidToDer(forge.pki.oids.data).getBytes())
          ]);

        // add actual content, if present
        if('content' in msg) {
          msg.contentInfo.value.push(
            // [0] EXPLICIT content
            asn1.create(asn1.Class.CONTEXT_SPECIFIC, 0, true, [
              asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OCTETSTRING, false,
                msg.content)
            ]));
        }
      }

      // TODO: generate digest algorithm identifiers
      var actualSigner = signer;
      var signersCount = 0;
      var actualSigners = new Array();
      if(typeof signer == 'Array')
      { 
         
           //TODO validate type and length of array is one or more 
           actualSigners = signer;
           actualSigner = signer[0];
           
      }
      else
      {
          actualSigners[0] = signer;
      }
      msg.AlgorithmIdentifiers = 
             asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SET, true,'');
        
      for(var i =0; i <actualSigner.Count; i++)
      {

              var digistOid = "1.3.14.3.2.26"; // SHA1 OID
               if(!('DigistOid' in signer))
              {
                     digistOid = signer.DisgistOid;
              }
             var DigistValue = signer.CalculateDigist(msg.contentInfo.value); //Not supporting parameters
           
            msg.AlgorithmIdentifiers.value.push(             
             // AlgorithmIdentifier
               asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
                    // algorithm
                     asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OID, false,
                     digistOid.getBytes()),
                      // parameters 
                     //TODO add parameters from signer
                    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.NULL, false, '') // assuming a null  parameters for the digist
                 )  
              );

                
      }
       msg.SignerInfos= 
             asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SET, true,'');
      // TODO: generate signerInfos
      for(var i=0; i <signersCount; i++)
      {
            msg.SignerInfos.value.push(
                 // Signers Info
                 asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
                    // Version
                     asn1.create(asn1.Class.UNIVERSAL, asn1.Type.INTEGER, false,
                     1),
                      // issuerAndSerialNumber 
                     
                    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, '
                       [ new asn1(signer.CertificateName)
                       , asn1.create(asn1.Class.UNIVERSAL, asn1.TYPE.INTEGER, false,                         signer.CertificateSerialNumber)]),
               // Digist Algorithm
           asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SET, true,[
             // AlgorithmIdentifier
               asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
                    // algorithm
                     asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OID, false,
                     actualSigner.DisgistOid.getBytes()),
                      // parameters 
                  
                    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.NULL, false, '') // assuming a null parameters for the digist
               ])
            //TODO Add  authenticatedAttributes
           ,
           //DigestEncryptionAlgorithmIdentifier
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
                    // algorithm
                     asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OID, false,
                     actualSigner.SigningEncryptionAlgorithm.getBytes()),
                      // parameters                   
                    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.NULL, false, '') // assuming a null parameters for the digist
               ])
     , 
      // Digist Itself
               asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OCTET_STRING, false,            actualSigner.Sign(msg.content.value)
                 ]) ; 
      }     
   }

**Comment by roysjosh** [comment]
I implemented this last week for work. I can probably share it in a week or two after legal signs off on it if you're interested.

**Comment by dlongley** [comment]
@roysjosh, we've already got an implementation in progress; it may be interesting to compare once it's merged in, however.

**Comment by Bibo1978** [comment]
Must have a look at that I hope you made it with a virtual key interface

**Comment by dlongley** [comment]
PKCS#7 Signing support is now available in version 0.6.34.
