### ISSUE TITLE
What's the correct way of using forge.min.js and require.js(amd) together ?

### ISSUE THREAD

**Issue by dcu** [digitalbazaar/forge#197]
Should I include it before require.js? after? how can I require it?

I am having a really hard time including forge as part of my project and require.js is not very helpful when printing the errors.

can someone please point me in the right direction?

EDIT1: 
This is for a client-based app and not a nodejs-based server.

EDIT2:
If I modify the forge.min.js file to give a name to the module like: `define("js/forge", [], t)`  it seems to work. I'm testing this atm.

EDIT2:
I had to set it to "/vendor/js/forge.js" so the web workers can load it. This is all very hackish and horrible so I'd like to find a proper solution. It's good enough for the moment because I was tired of spending time fighting the tool rather than solving my actual problem.

**Comment by dlongley** [comment]
Addressed by #456.
