### ISSUE TITLE
forge.pki.verifyCertificateChain supported by Win RT 8.1 for tablet + IE11

### ISSUE THREAD

**Issue by lautarobock** [digitalbazaar/forge#221]
I'm trying to verify certificate chain in **Win RT 8.1 for tablet + IE11** and is not working properly. 
It works in fine in others platforms (chrome, FF, IE 9, 10 and 11 for desktop) but we have a problem in this version for tablet. 
I dont have more information yet.

**Comment by dlongley** [comment]
We haven't tested forge with **Win RT 8.1 for tablet + IE11** yet. If you can provide any sort of feedback, console errors, or other debugging information related to the problem that would be great.

**Comment by dlongley** [comment]
Closing as potentially resolved, can be reopened if necessary.
