### ISSUE TITLE
enable pki.verifyCertificateChain() to test with an arbitrary date/time (for S/MIME email)

### ISSUE THREAD

**Issue by rhashimoto** [digitalbazaar/forge#222]
This is a feature request.

`pki.verifyCertificateChain()` checks that all chain certificates are valid at the current date/time. It would be nice if an optional `Date` could be provided for this test. An example of why this might be useful is verifying S/MIME signed email, where all certificates were valid at the time the message was sent but one or more have since expired. It doesn't appear possible to use this function for this purpose.

Alternatively, if the date/time check is moved to be the last one before calling the `verify` callback, then no change in the function arguments is needed as the callback can override the error knowing that all other checks have passed. This might break existing code as the `verify` callback could _not_ be used to override the check that is currently last (`keyUsageExt`), though this seems unlikely.

A third possible solution would be to always apply all the tests and pass a collection of errors to the `verify` callback. Unfortunately this is more likely to break existing code.

**Comment by dlongley** [comment]
This is similar to #188. We agree there's value in a feature like this and we'd like to support it -- we just need some time to sit down and figure out the right way forward. Ideally, we wouldn't break backward compatibility. If we must, then the feature can be part of **0.7.x** which has some other breaking API changes.

**Comment by dlongley** [comment]
Related to #195 as well.

**Comment by davidlehn** [comment]
A variation of this was added in https://github.com/digitalbazaar/forge/pull/635.
