### ISSUE TITLE
estimateCores does not work on firefox

### ISSUE THREAD

**Issue by browning** [digitalbazaar/forge#225]
On chrome 40 I get this:

    window.forge.util.estimateCores(function(err, cores) { console.log(cores); });
    8

On Firefox 36:

    window.forge.util.estimateCores(function(err, cores) { console.log(cores); });
    Error: Failed to load script (nsresult = 0x805e0006)
      map()util.js (line 2856)
      sample()util.js (line 2846)
      initModule/util.estimateCores()util.js (line 2834)
      var worker = new Worker(blobUrl);

**Comment by dlongley** [comment]
It's working fine for me with Firefox 36 with this simple test setup:

```html
<!DOCTYPE html>
<html>
<head>
  <script src="/js/util.js"></script>
</head>
<body>

<script>
window.forge.util.estimateCores(function(err, cores) {
  console.log('cores', cores);
});
</script>

</body>
</html>
```

Do you have a special `Content-Security-Policy` header set? I saw this bug while looking around to see what might be the problem: https://bugzilla.mozilla.org/show_bug.cgi?id=964276

**Comment by browning** [comment]
Ahhhh, thanks!

Yea that must be the bug, I do have a Content Security Policy set.
