### ISSUE TITLE
Java and keytool compatibility

### ISSUE THREAD

**Issue by kkrauth** [digitalbazaar/forge#231]
I persisted a PKCS#12 keystore using node and forge (based on test nodejs-create-pkcs12.js). Using openssl I can parse and extract the private key. However, when I try to use java or keytool, I run into issues. Listing the contents of the P12 seems fine:

    keytool -list -keystore key.p12 -storetype pkcs12
    Enter keystore password:  

    Keystore type: PKCS12
    Keystore provider: SunJSSE

    Your keystore contains 1 entry

    test, 01-Apr-2015, PrivateKeyEntry, 
    Certificate fingerprint (SHA1): 41:38:D6:FD:53:14:A1:12:29:A2:40:7A:28:DD:AB:EB:A7:FA:6C:C4

However if I attempt to convert it to JKS, I get the following error:

    keytool -importkeystore -srckeystore key.p12 -srcstoretype pkcs12 -srcalias test -destkeystore key.jks -deststoretype jks -deststorepass password -destalias test
    Enter source keystore password:  
    keytool error: java.security.UnrecoverableKeyException: Private key not stored as PKCS#8
    EncryptedPrivateKeyInfo: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)

I get the same exception when trying to load the PKCS12 in code using the following block:

```java
KeyStore ks = KeyStore.getInstance("PKCS12");
ClassLoader cl = this.getClass().getClassLoader();
InputStream stream = cl.getResourceAsStream("key.p12");
ks.load(stream, "password".toCharArray());
Key key = ks.getKey("test", "password".toCharArray());
```

    Exception in thread "main" java.security.UnrecoverableKeyException: Private key not stored as PKCS#8 EncryptedPrivateKeyInfo: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:332)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at App.getPrivateKey(App.java:116)

Java version:

    java -version
    java version "1.8.0_40"
    Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
    Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

Is there a known incompatibility? I couldn't find anything browsing the issues.

**Comment by kkrauth** [comment]
What I should also mention is that if I convert the private key into PEM like so:

If I convert the private key into PEM format and store that on disk like so:
```javascript
  var rsaPrivateKey = forge.pki.privateKeyToAsn1(keys.privateKey);
  var privateKeyInfo = forge.pki.wrapRsaPrivateKey(rsaPrivateKey);
  var pem = forge.pki.privateKeyInfoToPem(privateKeyInfo);
  fs.writeFile("privateKey.pem", pem);
```
I can load this key in Java without any issues. Briefly glancing at `pkcs12.js` source, I can see it stores the private key inside the PKCS#12 keystore in the same format:
```javascript
var pkAsn1 = pki.wrapRsaPrivateKey(pki.privateKeyToAsn1(key));
```

Could it be something related to the implementation with `encryptPrivateKeyInfo` perhaps? I also tried generating the P12 without a password but then I was getting keytool errors saying the integrity of the file couldn't be verified.

**Comment by dlongley** [comment]
> Is there a known incompatibility? I couldn't find anything browsing the issues.

No, there's no known incompatibility, these things can just sometimes be more tricky than they should be. :)

> So I find it odd that the erorr suggests that the key is not stored as PKCS#8. I also tried generating the P12 without a password but then I was getting keytool errors saying the integrity of the file couldn't be verified.

Well, if no password is given, PKCS#8 isn't used (there's nothing to encrypt with):

https://github.com/digitalbazaar/forge/blob/master/js/pkcs12.js#L923

 If a password is given, then it definitely is:

https://github.com/digitalbazaar/forge/blob/master/js/pkcs12.js#L942-L947

Java should accept either format (both are valid), but it seems like perhaps it doesn't. Did you use a password when generating the PKCS#12? If not, try that, as it seems that Java may require it.

**Comment by kyleclarkMC** [comment]
It does indeed appear that getting PKCS#12 structure cross-compatible with various tools is tricky. :) And yes, I used a password when generating the P12 for all the cases I listed in the example.

**Comment by kkrauth** [comment]
It does indeed appear that getting PKCS#12 structure cross-compatible with various tools is tricky. :) And yes, I used a password when generating the P12 for all the cases I listed in the example.

**Comment by dlongley** [comment]
> I get the feeling that the message is misleading and being thrown because Java is reading the incorrect byte range within the PKCS#12 when extracting private key.

Yeah, it could be any number of things like that. Can you come up with a minimal example with code for JavaScript and for Java that I can run on my end (when I get a chance)? That may help figure out the issue.

**Comment by kkrauth** [comment]
Certainly!

Javascript:
```javascript
var forge = require('../js/forge');
var fs = require('fs');

try {
  // generate a keypair
  console.log('Generating 1024-bit key-pair...');
  var keys = forge.pki.rsa.generateKeyPair(1024);
  console.log('Key-pair created.');

  // create a certificate
  console.log('Creating self-signed certificate...');
  var cert = forge.pki.createCertificate();
  cert.publicKey = keys.publicKey;
  cert.serialNumber = '01';
  cert.validity.notBefore = new Date();
  cert.validity.notAfter = new Date();
  cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear() + 1);
  var attrs = [{
    name: 'commonName',
    value: 'example.org'
  }, {
    name: 'countryName',
    value: 'US'
  }, {
    shortName: 'ST',
    value: 'Virginia'
  }, {
    name: 'localityName',
    value: 'Blacksburg'
  }, {
    name: 'organizationName',
    value: 'Test'
  }, {
    shortName: 'OU',
    value: 'Test'
  }];
  cert.setSubject(attrs);
  cert.setIssuer(attrs);
  cert.setExtensions([{
    name: 'basicConstraints',
    cA: true
  }, {
    name: 'keyUsage',
    keyCertSign: true,
    digitalSignature: true,
    nonRepudiation: true,
    keyEncipherment: true,
    dataEncipherment: true
  }, {
    name: 'subjectAltName',
    altNames: [{
      type: 6, // URI
      value: 'http://example.org/webid#me'
    }]
  }]);

  // self-sign certificate
  cert.sign(keys.privateKey);
  console.log('Certificate created.');

  // create PKCS12
  console.log('\nCreating PKCS#12...');
  var password = 'password';
  var newPkcs12Asn1 = forge.pkcs12.toPkcs12Asn1(
    keys.privateKey, [cert], password,
    {generateLocalKeyId: true, friendlyName: 'test'});
  var newPkcs12Der = forge.asn1.toDer(newPkcs12Asn1).getBytes();

  fs.writeFile("key.p12", forge.util.encode64(newPkcs12Der), 'base64');

} catch(ex) {
  if(ex.stack) {
    console.log(ex.stack);
  } else {
    console.log('Error', ex);
  }
}
```
Ran it with `node`.

Then Java class to load it:
```java
import java.io.InputStream;
import java.security.Key;
import java.security.KeyStore;

public class ForgeP12Loader {
    public static void main(String[] args) throws Exception {
        KeyStore ks = KeyStore.getInstance("PKCS12");
        ClassLoader cl = ForgeP12Loader.class.getClassLoader();
        InputStream stream = cl.getResourceAsStream("key.p12");
        ks.load(stream, "password".toCharArray());
        Key key = ks.getKey("test", "password".toCharArray());
    }
}
```
Compile and run (The key.p12 file generated by node must be in the same folder as the Java class) :

    javac ForgeP12Loader.java
    java ForgeP12Loader

Keytool can also be run as sanity check and produces same output:

    keytool -importkeystore -srckeystore key.p12 -srcstoretype pkcs12 -srcalias test -destkeystore key.jks -deststoretype jks -deststorepass password -destalias test -srcstorepass password

**Comment by dlongley** [comment]
@kkrauth, if you use '3des' encryption instead of AES, it works.

```js
  var newPkcs12Asn1 = forge.pkcs12.toPkcs12Asn1(
    keys.privateKey, [cert], password,
    {algorithm: '3des', generateLocalKeyId: true, friendlyName: 'test'});
```

**Comment by dlongley** [comment]
Apparently Java doesn't support AES (for p12 containers) ... or perhaps something else needs to be done in the Java code to support it. There's a similar problem with browsers ... they also only support the old Triple DES algorithm.

**Comment by kkrauth** [comment]
Well spotted! As you said, works without any any issues when using 3des. Thanks a lot for such fast feedback Dave. Hopefully this will help others who end up in a similar situation...

**Comment by dlongley** [comment]
@kkrauth, sure! :) ... Yeah, it always helps to have these issues documented.
