### ISSUE TITLE
Can Forge.js simulate OpenSSL CA CRL commands?

### ISSUE THREAD

**Issue by efkan** [digitalbazaar/forge#234]
I want to publish certificates to my users to implement ssl-client authentication.

I will;
1- Create CA and server certificates using `OpenSSL`.
2- Publish a certificate per user using `forge.js`
3- Use a `CRL` for my CA.

Is there any chance to simulate the below commands through forge.js ?

revoke a certificate;
`openssl ca -revoke client-crt.pem -keyfile ca-key.pem -config ca.cnf -cert ca-crt.pem -passin 'pass:password'`

and update CRL;
`openssl ca -keyfile ca-key.pem -cert ca-crt.pem -config ca.cnf -gencrl -out ca-crl.pem -passin 'pass:password'`

**Comment by dlongley** [comment]
Hi @efkan,

Forge doesn't support CRLs at the moment. We'd be happy to accept a well-written PR that adds support, however. Most of the framework necessary to implement certificate revocation via CRLs is already available in forge, I believe the only work would be adding methods to convert CRLs to/from ASN.1 format and a basic API for creating/updating a CRL.

**Comment by efkan** [comment]
Thank you.
