### ISSUE TITLE
Possible to determine Algorithm Type/Encryption level of CSR decoding?

### ISSUE THREAD

**Issue by georgebohnisch** [digitalbazaar/forge#235]
I'm decoding a CSR by passing a string to forge.pki.certificationRequestFromPem();

Is it possible to get the algorithm used and the encryption level (i.e. 128/256/etc) of the csr?

**Comment by dlongley** [comment]
CSRs aren't generally encrypted, rather they contain a digital signature provided by the requestor's private key. The code below demonstrates how to print out the signature algorithm as an object identifier and as a human readable string for that identifier:

Example CSR:

```
-----BEGIN CERTIFICATE REQUEST-----
MIIB3TCCAUYCAQAwaTEUMBIGA1UEAxMLZXhhbXBsZS5vcmcxCzAJBgNVBAYTAlVT
MREwDwYDVQQIEwhWaXJnaW5pYTETMBEGA1UEBxMKQmxhY2tzYnVyZzENMAsGA1UE
ChMEVGVzdDENMAsGA1UECxMEVGVzdDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkC
gYEAjL3R57UVC6UoEbcePu1NflyLEM+apcJkuwu8Tcju/DedJ/ur/+voZ+sb22I4
OoeNdsouMt923SeW+ZYNX2BqCUKaU01aKQJBwyrSRqlRZJedjrnE5vXQ2ygB6f1B
nQ+Pu/fu4C2yB4IX29JydmE/lYUCh+TGT7Bm2enU82tHwqMCAwEAAaA0MBcGCSqG
SIb3DQEJBzEKDAhwYXNzd29yZDAZBgkqhkiG9w0BCQIxDAwKTXkgY29tcGFueTAN
BgkqhkiG9w0BAQUFAAOBgQAWtgmW305k7d4CA0xloFAS8RljoRbAppkQZmFkd474
0N5GOa0j3GM6M/LHFX9SCPr81B+YMXvooQJVLfzrr5VSRctHta74aK1T4mf0+8EK
LJdFo/7c2gEjYF8VPtE+pzT7+mOt/MrWEdDHbtRB5RY2dX4dzmzrSUawHS+I//qm
vg==
-----END CERTIFICATE REQUEST-----
```

Code to print out the signature algorithm:

```js
var csr = forge.pki.certificationRequestFromPem(pem);

console.log('csr signatureOid', csr.signatureOid);
console.log('csr signature algorithm', forge.pki.oids[csr.signatureOid]);
```

Result:

```
csr signatureOid 1.2.840.113549.1.1.5
csr signature algorithm sha1WithRSAEncryption
```

**Comment by georgebohnisch** [comment]
Great,

Thanks for the rapid response.

I suppose what I'm looking for is determining the bit level of the pk.

For example:

`openssl req -in Test.csr -noout -text`

Returns

`Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: C=US, ST=Utah, L=Lindon, O=DigiCert Inc., OU=DigiCert, CN=example.digicert.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:...
`
It's the 2048bit that I'm looking for

**Comment by dlongley** [comment]
This should do it:

```js
console.log('bit size: ', csr.publicKey.n.bitLength());
```

```
bit size: 1024
```
