### ISSUE TITLE
Load public key from base64 encoded der.

### ISSUE THREAD

**Issue by biddster** [digitalbazaar/forge#236]
I'm trying to load a der public key cert into forge. It is being supplied to me base 64 encoded.

I'm loading it like this:

```
var der = forge.util.decode64(base64EncodedDer);
var asn1 = forge.asn1.fromDer(der, false);
var publicKey = forge.pki.publicKeyFromAsn1(asn1);
```

I'm always getting the error 'Error: Cannot read public key. ASN.1 object does not contain an RSAPublicKey.'.

The doc on publicKeyFromAsn1 states 'Converts a public key from an ASN.1 SubjectPublicKeyInfo or RSAPublicKey.'

If I dump the Der to disk and get openssl to inspect it (openssl x509 -in test.crt -inform der -text), I can see that it does have subject public key info in there: 

```
Signature Algorithm: sha256WithRSAEncryption
...
Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (1024 bit)
```

I'm guessing I'm missing something really obvious and would be very grateful indeed for any pointers.

**Comment by dlongley** [comment]
Can you provide the base64-encoded public key here in the issue?

**Comment by biddster** [comment]
Sure, thanks for the fast reply.

```
MIIBoTCCAQqgAwIBAgIICNIaY48bHcEwDQYJKoZIhvcNAQELBQAwEjEQMA4GA1UEAwwHbWN5cGhlcjAgFw0xNTAyMTkxNDAwMzJaGA8yMTE1MDIxOTE0MDAzMlowEjEQMA4GA1UEAwwHbWN5cGhlcjCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAlgW+89nQ8Sp+3n8vNTHtqEVaQ7vM0vyldPqNMvfK9E7Gyf4G3bMEO5KtMvsWZQ94PoUMR0zQrlzl03QO9zJTFZktiwgOqnIPOOTF1jQboOdLCUBdlcTqz8H8C0PFXw9zRpVcFThRlwhyoC6w5Umg8PywCg64EavsuCd9d+ei+DUCAwEAATANBgkqhkiG9w0BAQsFAAOBgQCTCRpsldZutaXpwWcLRMtDpyNEEj7sG/GR88UXvSpy7m4bwqa5zwn46NaXYsfg/PfAblW5fScn0ZRqNfV3PooCOM6uxcsXfa8K4yPLMKikgQ2b3STPzUwJNGB9LrMmPJKzTi74FXMyNvV1KRI1HW2LuWkP2kSJbWGShkOSj5Cxvg==
```

**Comment by dlongley** [comment]
Sure. :)

Do this instead:

```js
var der = forge.util.decode64(base64EncodedDer);
var asn1 = forge.asn1.fromDer(der, false);
var cert = forge.pki.certificateFromAsn1(asn1);
var publicKey = cert.publicKey;
```

The data you've got there is an X.509 certificate, not just a public key. It's true that there is a SubjectPublicKeyInfo buried deep in an X.509 certificate, but forge doesn't try to do a deep scan of what you give it to find the first occurrence of such a public key; rather, it expects it to be at the top level.

**Comment by biddster** [comment]
Outstanding, thanks for that. Makes perfect sense now and I'm off and working. Many thanks again.

**Comment by dlongley** [comment]
Sure, no problem :)
