### ISSUE TITLE
Current state of PRNG in nodejs

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/forge#238]
Looking at [random.js](https://github.com/digitalbazaar/forge/blob/master/js/random.js#L123) it's unclear to me exactly what happens if nodejs is detected as the runtime environment.  However, it does appear that what I believe to be the best solution is not being implemented which would be to call the [randomBytes](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) function from node's built-in 'crypto' module.

This function provides access to a CSPRNG via the native openssl lib.  [Here are some words](https://wiki.openssl.org/index.php/Random_Numbers) about how the openssl lib comes by randomness.

**Comment by dlongley** [comment]
@mattcollier, node's `randomBytes` native implementation is used, if available, in [prng.js](https://github.com/digitalbazaar/forge/blob/master/js/prng.js#L19) which `random.js` depends on.

See also: https://github.com/digitalbazaar/forge/blob/master/js/prng.js#L315

**Comment by mattcollier** [comment]
Great!  Thanks for your prompt response.
