### ISSUE TITLE
Integrating electron (atom-shell) with forge

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/forge#240]
I'm attempting to get the [forge module](https://github.com/digitalbazaar/forge) to work with [atom-shell](https://github.com/atom/electron/).

Forge module mods:
https://github.com/mattcollier/forge/blob/master/js/prng.js#L23

Atom-shell renderer code:
https://gist.github.com/mattcollier/3a713b4a076cd65257fe

The code as shown allows one to utilize webworkers while still getting a CSPRNG from io.js via openssl.

I found that I can't call include('remote') on line 23 as shown

All of this works as shown, but I would like to have a solution that could be incorporated into forge. Ideally, the code would behave properly whether it is loaded from the renderer or the main process.

Also, see: https://github.com/atom/electron/issues/1436

**Comment by mattcollier** [comment]
Turns out the idea I was trying to implement is not thread safe.

**Comment by dlongley** [comment]
> Turns out the idea I was trying to implement is not thread safe.

Ok. Sorry I couldn't get to this sooner. I hope you figure out a better approach to solve your problem.
