### ISSUE TITLE
How make forge keys crypto api compatible?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [digitalbazaar/forge#255]
I exctracted pkcs#8 private key from p12 file. I know, 12!=8, but it seems getting private key from p12 via `keyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0];` is OK because forge.sign() was equal to Java output. After that I converted pkcs8 to PEM (stripped "BEGIN, END" headers and footers) and tried to give that key to standart web crypto API function:

	 window.crypto.subtle.importKey(
	  "pkcs8", //can be "jwk" (public or private), "spki" (public only), or "pkcs8" (private only)
	  //der,
	  //der.getBytes().buffer,
	  b64ToArrayBuffer(PEM_headers_stripped);	
         //b64ToArrayBuffer(PEM_headers_NOT_stripped);				
	  {   //these are the algorithm options
	   name: "RSASSA-PKCS1-v1_5",
	   hash: {name: "SHA-256"}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
	  },
	  false, //whether the key is extractable (i.e. can be used in exportKey)
	  ["sign"] //"verify" for public key import, "sign" for private key imports
	)
	.then ...

and in console recieving message `"DataError", code: 0`.

May be you know, how pass a forge key in PEM/DER/ASN/any format to web crypto? 
Thanks.

**Comment by dlongley** [comment]
The code below works for me. It will take a forge private key object, wrap it in a PKCS#8 PrivateKeyInfo container, DER-encode it, and convert the resulting binary string to an ArrayBuffer which is passed to the `importKey` function.

```js
var privateKey = // get forge private key object

// convert to PKCS#8 PrivateKeyInfo
var rsaPrivateKey = forge.pki.privateKeyToAsn1(privateKey);
var privateKeyInfo = forge.pki.wrapRsaPrivateKey(rsaPrivateKey);

// get DER-formatted PKCS#8 private key
var pkcs8 = forge.asn1.toDer(privateKeyInfo).getBytes();

// converts a forge 0.6.x string of bytes to an ArrayBuffer
function str2ab(str) {
  var b = new ArrayBuffer(str.length);
  var view = new Uint8Array(b);
  for(var i = 0; i < str.length; ++i) {
    view[i] = str.charCodeAt(i);
  }
  return b;
}

// import the PKCS#8 DER-formatted key
window.crypto.subtle.importKey(
  'pkcs8', str2ab(pkcs8), {
    name: 'RSASSA-PKCS1-v1_5',
    hash: {name: 'SHA-256'}
  },
  false,
  ["sign"]).then(function(result) {
    console.log('imported', result);
  }).catch(function(err) {
    console.log('error', err);
  });
```

**Comment by BaurzhanSakhariev** [comment]
Thank you! 

Even if one day Web Crypto API will provide USB tokens, smart cards, p12 keys support out of the box and people migrate from JS to Web Crypto API you should know that you reduced entropy (chaos) in our planet by helping to developers from whole world!

**Comment by dlongley** [comment]
Sure and thank you!
