### ISSUE TITLE
Import encrypted pkcs#12 - not able to read private key 

### ISSUE THREAD

**Issue by fsp77** [digitalbazaar/forge#258]
I have been trying to import an encrypted pkcs#12 into forge.
I created the pkcs#12 using openssl:
```
openssl pkcs12 -export -inkey keypairs/key01.pem -in keypairs/cert01.pem -certfile cacert.pem -out keypairs/pkcs01.p12
```
I have so far been able to read the certificates using this procedure:
```
function pkcsFromFile(file) {
    return fs.readFileSync(file);
}
var p12Buffer = pkcsFromFile("/home/xyz/bkup/pkcs01.p12");
var p12Der = forge.util.binary.raw.encode(new Uint8Array(p12Buffer));
var p12Asn1 = forge.asn1.fromDer(p12Der);
var p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, 'passwd');
var certBags = p12.getBags({bagType: forge.pki.oids.certBag});
```
^^ I could extract all the certificates from certBags.

Actual Issue:
Getting the private key has proved a bit difficult... here's what I have tried:
```
var pkeyBags = p12.getBags({bagType: forge.pki.oids.keyBag}); // returns an empty bag
var pkeyBags = p12.getBags({bagType: forge.pki.oids.pkcs8ShroudedKeyBag});
```
^^getBags with bagType = pkcs8ShroudedKeyBag returns a bag but am not able to decrypt it.
```
> var pkeyBags =  p12.getBags({bagType: forge.pki.oids.pkcs8ShroudedKeyBag}, "passwd");
undefined
> pkeyBags
{ '1.2.840.113549.1.12.10.1.2': 
   [ { type: '1.2.840.113549.1.12.10.1.2',
       attributes: [Object],
       key: [Object] } ] }
> forge.pki.oids.pkcs8ShroudedKeyBag
'1.2.840.113549.1.12.10.1.2'
> forge.pki.privateKeyToPem(pkeyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0].key)
```
^^ This gives me a key but this is not the same as the one I encoded into the pkcs#12 envelope.

**Comment by BaurzhanSakhariev** [comment]
var keyBags = p12.getBags({bagType: forge.pki.oids.pkcs8ShroudedKeyBag});
     var bag = keyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0];
     var privateKey = bag.key;

Now you may convert forge key to PEM:

       var pem = forge.pki.publicKeyToPem(publicKey);
       var 64pem = forge.util.decode64(pem);

this function returns with BEGIN,END headers, if you want to get pure b64 PEM key without headers, use:

    var asn1 = forge.pki.privateKeyToAsn1(privateKey);
    var der = forge.asn1.toDer(asn1);
    var b64key = forge.util.encode64(der.getBytes()); //same with PEM above, without headers.

**Comment by fsp77** [comment]
Baurzhan Sakhariev: thanks for checking.

Sorry if I was not clear...

I have tried what you suggested (please also see my first note); the key that is output from ```forge.pki.privateKeyToPem(pkeyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0].key)``` does not match the private key I had encoded into the pkcs#12 using openssl.

Also tried your suggestion:
```
var asn1 = forge.pki.privateKeyToAsn1(privateKey);
var der = forge.asn1.toDer(asn1);
var b64key = forge.util.encode64(der.getBytes()); //same with PEM above, but without headers.
```
Got the same key as from ```forge.pki.privateKeyToPem```

**Comment by BaurzhanSakhariev** [comment]
Second approach returns pem key without "BEGIN/END RSA PRIVATE KEY" headers, so, the are not fully same but I guess you didn't take it to account.
But binary(asn-der-b64) != binary(pem), because pem binary takes to account headers. I mean, if you comparing binary outputs of ssl and binary of pem you should compare binary of ssl with binary(without headers). If you already comparing binaries without headers or even tried to compare both variants I didn't know the reason, sorry.

**Comment by fsp77** [comment]
My bad: Yes, I see that now. Sorry about the wild goose chase.
My test was failing because I was doing a Buffer.compare.

One question still though: 
why is forge returning an RSA private key (PKCS#1) when a PKCS#8 bag is requested.

**Comment by BaurzhanSakhariev** [comment]
I also asked this in one of previous issues but it seems that p12 container which devoted to store public certs and private keys stores private keys in pkcs8. In other words, pkcs#12 has private key section which has pkcs#8 formatted key. 

But I was too lazy to check it, you may read pkcs#12 specification and try to prove this hypothesis) If you will find anything interesting you post it here it will be interesting)

**Comment by fsp77** [comment]
Sure will do. Many thanks at the interim though. Cheers.

**Comment by dlongley** [comment]
> why is forge returning an RSA private key (PKCS#1) when a PKCS#8 bag is requested.

Forge deserializes the private key entirely, it only maintains an association with the type of bag from which it came (which is how you filter the pkcs12 contents). You can serialize it back to a PKCS#8 container by doing this:

```js
// convert a Forge private key to an ASN.1 RSAPrivateKey
var rsaPrivateKey = forge.pki.privateKeyToAsn1(privateKey);

// wrap an RSAPrivateKey ASN.1 object in a PKCS#8 ASN.1 PrivateKeyInfo
var privateKeyInfo = forge.pki.wrapRsaPrivateKey(rsaPrivateKey);

// then you can convert to DER, etc. like before
var der = forge.asn1.toDer(privateKeyInfo);
```

**Comment by fsp77** [comment]
Thanks for that info. Closing this issue now. Cheers.

**Comment by NishantDesai1306** [comment]
When i use 
```
var p12Der = forge.util.decode64(p12File);
var p12Asn1 = forge.asn1.fromDer(p12Der);
var p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, password);
var keyBags = p12.getBags({bagType: forge.pki.oids.pkcs8ShroudedKeyBag});
var bag = keyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0];
var privateKey = bag.key;
var pem = forge.pki.publicKeyToPem(privateKey); 
  /*
    according to BaurzhanSakhariev's comment on May 19, 2015 in second code snippet 
    in comment argument is publickKey but i guess its private key as the key in first snippet is stored in 
    variable privatekey correct me if i am wrong
  /*
var key = forge.util.decode64(pem);
console.log(key);
```

The problem that i am facing is that when i log the key (last line of code in above snippet) i get RSA PRIVATE KEY. On searching on internet i found out that RSA PRIVATE KEY is traditional format in PKCS#1 and to get PRIVATE KEY from it I need to convert it into PKCS#8 form

I did it using this command in openssl
`openssl pkcs8 -topk8 -inform pem -in file.key -outform pem -nocrypt -out file.pem`

I just wanna know how can i do this in javascript ??
Any help is appreciated

**Comment by dlongley** [comment]
Try this:

```js
var publicKey = forge.pki.setRsaPublicKey(privateKey.n, privateKey.e);
var pem = forge.pki.publicKeyToPem(publicKey);
```

**Comment by dlongley** [comment]
@NishantDesai1306,

Oh, sorry, I misread your comment. You want PKCS#8 form, one minute, I'll get a code sample for that.

**Comment by dlongley** [comment]
@NishantDesai1306,

```js
// convert a Forge private key to an ASN.1 RSAPrivateKey
var rsaPrivateKey = forge.pki.privateKeyToAsn1(privateKey);

// wrap an RSAPrivateKey ASN.1 object in a PKCS#8 ASN.1 PrivateKeyInfo
var privateKeyInfo = forge.pki.wrapRsaPrivateKey(rsaPrivateKey);

// convert a PKCS#8 ASN.1 PrivateKeyInfo to PEM
var pem = forge.pki.privateKeyInfoToPem(privateKeyInfo);

// encrypts a PrivateKeyInfo and outputs an EncryptedPrivateKeyInfo
var encryptedPrivateKeyInfo = forge.pki.encryptPrivateKeyInfo(
  privateKeyInfo, 'password', {
    algorithm: 'aes256', // 'aes128', 'aes192', 'aes256', '3des'
  });

// converts an EncryptedPrivateKeyInfo to PEM
var pem = forge.pki.encryptedPrivateKeyToPem(encryptedPrivateKeyInfo);
```

**Comment by NishantDesai1306** [comment]
thanks it worked flawless

**Comment by BaurzhanSakhariev** [comment]
тенст

2016-04-12 21:12 GMT+06:00 NishantDesai1306 <notifications@github.com>:

> thanks it worked flawless
