### ISSUE TITLE
Public key from private (RSA)

### ISSUE THREAD

**Issue by cadorn** [digitalbazaar/forge#26]
When I generate an RSA key pair:

```
var pair = RSA.generateKeyPair(size, 0x10001);
```

And keep the private key as:

```
var pk = ASN1.toDer(PKI.privateKeyToAsn1(pair.privateKey)).getBytes()
```

How can I derive the public key from `pk`?

I am assuming I can get the public key for a private key in the first place?

**Comment by dileepkeeppalli** [comment]
@dlongley 

I am using node-forge definitions in my typescript application. 
Able to generate keypair and now I want to generate a password protected private key.

I tried the way that  you mentioned above.
`forge.pki.encryptRsaPrivateKey(pair.privateKey, 'password')`

But  `**encryptRsaPrivateKey**` method is showing as unresolved. in my typescript. Is there any way to achieve password protected private key?

**Comment by kiranhpe** [comment]
I'm using typescript, it is working for me without any issue.
