### ISSUE TITLE
option for using native openssl / gnupg / etc

### ISSUE THREAD

**Issue by coolaj86** [digitalbazaar/forge#263]
I'm trying to get the letsencrypt demo to run in a reasonable timeframe on a raspberry pi:
https://github.com/letsencrypt/node-acme/issues/22 (took 89 minutes using node-forge)

It appears that in order to do that I need to drop down to the cli and exec openssl or similar for the generate key and sign steps because pure-js just isn't going to cut it.

I've been sifting through the code for about an hour now, but I'm not sure how I would pass the key to the commandline to or how I would pass an option through to signify that cli tools should be used instead of pure-js.

Is this feasible to do, or should I look for a different avenue (such as doing everything from the CLI and just reading the files back into node as needed).

**Comment by dlongley** [comment]
> (took 89 minutes using node-forge)

Ha! :)

Yeah, sounds like pure-js is a no go for key generation on raspberry pi. Can you just use `ursa` for key generation?

It seems like you could replace:

https://github.com/letsencrypt/node-acme/blob/master/lib/crypto-util.js#L98-L104
```js
generateKeyPair: function(bits) {
    var keyPair = forge.pki.rsa.generateKeyPair({bits: bits, e: 0x10001});
    return {
      privateKey: exportPrivateKey(keyPair.privateKey),
      publicKey: exportPublicKey(keyPair.publicKey)
    };
  },
```

With something like this:

```js
generateKeyPair: function(bits) {
    var ursa, keyPair;
    try {
      ursa = require('ursa');
    } catch(e) {
    }
    if(ursa) {
      keyPair = ursa.generatePrivateKey(bits, 0x10001);
      return importPemPrivateKey(keyPair.toPrivatePem('utf8'));
    }
    keyPair = forge.pki.rsa.generateKeyPair({bits: bits, e: 0x10001});
    return {
      privateKey: exportPrivateKey(keyPair.privateKey),
      publicKey: exportPublicKey(keyPair.publicKey)
    };
  },
```

**Comment by dlongley** [comment]
That should take care of key generation ... then see if signing is still too slow as well. If so, a similar patch can be done with `crypto.createSign`.

**Comment by coolaj86** [comment]
This works awesome.
