### ISSUE TITLE
How populate cert chain array parameter in verifyCertificateChain function?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [digitalbazaar/forge#264]
I'm trying to validate cert path of my cert file:

    var caStore = forge.pki.createCaStore();
    caStore.addCertificate(cert);
    try{
		forge.pki.verifyCertificateChain(caStore, [cert], function(vfd, depth, chain) {
		   console.log(vfd);
		    console.log(cert.verifySubjectKeyIdentifier());
		});
		}catch(ex){
			console.log(ex);
			console.log(JSON.stringify(ex, null, 2));
			console.log(JSON.stringify(ex));
		}

and getting 
 > "message": "Certificate keyUsage or basicConstraints conflict or indicate that the certificate is not a CA. If the certificate is the only one in the chain or isn't the first then the certificate must be a valid CA.",
  "error": "forge.pki.BadCertificate"

If I got it properly in the case of one cert it MUST be root (trusted) while I'm giving it my own cert. So, I have 2 questions:

1. How get full cert path in forge? After converting p12 to .cer and looking it properties in Windows I'm seeing full path of cert  = root-ca1-mycert. Is it possible to get this **full path** and populate chain array programatically?
2. How does forge check root cert? As far as I know root cert must be either installed manually (and thus trusted) or should be downloadable from trusted URL, am I right? Does forge check OS trusted store (which looks impossible for JS), somehow gets cert from browser (if root cert installed in browser), or downloads from some url (where url stored, under what O.I.D.?) ? 

*UPDATE*

I applied the code above to root cert. Now I'm recieving other error message:
>
  "message": "The application rejected the certificate.",
  "error": "forge.pki.BadCertificate"

My previous questions are actual and also I would be very grateful for any clarification of this "rejection".

**Comment by dlongley** [comment]
You need to get all three certificates and place them in the array you pass to `forge.pki.verifyCertificateChain`:

```js
[mycert, ca1, root]
```

Then you need to include the root certificate in your `caStore` so it will be trusted:

```js
caStore.addCertificate(root);
```

**Comment by BaurzhanSakhariev** [comment]
So, I have to somehow get full certificate chain and provide it to the forge. Got it. One can't grab chain from cert contents because usually chain stored in OS am I right? BTW, I should perform `verifyChain` but also I have to perform CRL/OCSP check for each item in cert-chain-array parameter, don't I?

**Comment by dlongley** [comment]
Yeah, forge doesn't currently check CRLs, so you'd have to do that yourself if you want that support.
