### ISSUE TITLE
Sign certificate with ca certificate

### ISSUE THREAD

**Issue by ThauEx** [digitalbazaar/forge#265]
I have a CA cert and the private key for that and now I want to create certificates and sign it with my CA cert. I don't know where I can assign the CA to the new generated cert.
As base I used this test: https://github.com/digitalbazaar/forge/blob/master/tests/nodejs-create-cert.js
This one is creating a new CA cert, so I modified it (different subject and issuer, removed extensions), but now I just have a new certificate, without my root CA.

So how can I add the root CA?

**Comment by dlongley** [comment]
When creating the new CA certificate, list the root CA's subject attributes as its issuer attributes. Then sign the certificate with the root CA's private key. That is what associates the new CA with its issuer, the root CA. That should be all you have to do; the root certificate contents don't go into the new CA certificate itself.

To actually use the certificates, you may need to "bundle" them together (concatenate the PEMs) to create a full chain.

**Comment by ThauEx** [comment]
Thanks for your answer, but with this way, every certificate has the same private key. I thought each certificate needs its own private key.
With openssl I created a csr with the private key of the certificate and then I used this and the ca+key to sign it.

**Comment by dlongley** [comment]
> Thanks for your answer, but with this way, every certificate has the same private key.

To be clear, the private key is not stored with the certificate, it is used to sign it. The certificate stores the public key -- and that public key would not match the one used to sign it. To better illustrate:

root CA:
Contains public key "root". Signed by private key "root". (It is self-signed).

intermediate CA 1:
Contains public key "intermediate1". Signed by private key "root".

intermediate CA 2:
Contains public key "intermediate2". Signed by private key "intermediate1".

server certificate:
Contains public key "server". Signed by private key "intermediate2". The server uses its private key to sign data in the TLS protocol.

> With openssl I created a csr with the private key of the certificate and then I used this and the ca+key to sign it.

Creating a CSR is something else entirely. You have to sign that with your own private key (the private key for the certificate you want generated) because you need to prove that you're the owner of the public key that is to be placed in the certificate. However, when the certificate is signed, it will be signed with the private key of the CA, not yours (as you should never give it to anyone). Your certificate needs to be signed by the CA's private key in order to prove that the CA did, indeed, approve and issue your certificate.

**Comment by ThauEx** [comment]
Hmmm thanks, now I got it, I think...
But! :D
Something is still not working...


This is my code for now (just a modified version of test):

```javascript
var forge = require('node-forge');

exports.generateForHost = function(domain, privateKey) {
    privateCAKey = forge.pki.privateKeyFromPem(privateKey);

    console.log('Generating 1024-bit key-pair...');
    var keys = forge.pki.rsa.generateKeyPair(1024);
    console.log('Key-pair created.');
    console.log('Creating self-signed certificate...');
    var cert = forge.pki.createCertificate();
    cert.publicKey = keys.publicKey;
    cert.serialNumber = '01';
    cert.validity.notBefore = new Date();
    cert.validity.notAfter = new Date();
    cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear() + 1);
    var attrsSubject = [{
        name: 'commonName',
        value: domain
    }, {
        name: 'organizationName',
        value: 'my-app'
    }];
    var attrsIssuer = [{
        name: 'commonName',
        value: 'my-app'
    }, {
        name: 'organizationName',
        value: 'my-app'
    }];
    cert.setSubject(attrsSubject);
    cert.setIssuer(attrsIssuer);

    // self-sign certificate
    // cert.sign(keys.privateKey/*, forge.md.sha256.create()*/);
    // better sign this with the CA private key
    console.log(privateKey);
    cert.sign(privateCAKey);
    console.log('Certificate created.');

    // PEM-format keys and cert
    var pem = {
        privateKey: forge.pki.privateKeyToPem(keys.privateKey),
        publicKey: forge.pki.publicKeyToPem(keys.publicKey),
        certificate: forge.pki.certificateToPem(cert)
    };


    console.log('\nKey-Pair:');
    console.log(pem.privateKey);
    //console.log(pem.publicKey);

    console.log('\nCertificate:');
    console.log(pem.certificate);
    return pem;
}
```

Here I sign it with my CA private key, but after checking the generated certificate, I got the message, that they don't match. When I use the generated private key (keys.privateKey), it matches...

And now another problem...
When I use this certificate with node js and create a https server, I got this error in Firefox:
> Secure Connection Failed
>
> An error occurred during a connection to ffrk.static.denagames.com. Cannot communicate securely with peer: no common encryption algorithm(s). (Error code: ssl_error_no_cypher_overlap) 


And a big thanks to you, for your time/help!

**Comment by dlongley** [comment]
> Here I sign it with my CA private key, but after checking the generated certificate, I got the message, that they don't match.

The issuer in the certificate you create must match that of the CA. In your example code, it's matching the subject -- you only do that for a self-signed certificate, where the issuer and subject are one in the same.

In a certificate, the "subject attributes" identify the subject of the certificate, namely, the server entity with the `domain` you want here. The "issuer attributes" identify the entity that issued and signed the certificate, namely, the CA. You need to get the CA's certificate and get out its subject attributes and insert them as the issuer attributes in the new certificate you're trying to generate. Effectively, pass in the CA certificate (parsed via `forge.pki.certificateFromPem`) and along with the domain and CA's private key, then set the new certificate's issuer to the subject attributes from the CA certificate.

```js
function(domain, caCert, caKey) {
  ...
  // issuer from CA
  cert.setIssuer(caCert.subject.attributes);
  ...
};

If it helps, here's a similar issue with sample code for generating a certificate from a CSR: #154

**Comment by dlongley** [comment]
Once your certificate is set up properly, I'd expect it to work with Firefox. If it doesn't, then you may need to change your signing algorithm to use SHA-256, as SHA-1 has been deprecated. To do that, it should just be a matter of providing the alternative message digest to `sign()`:

```js
cert.sign(privateCAKey, forge.md.sha256.create());
```

**Comment by ThauEx** [comment]
Thanks, that helped alot!
I figured out, that the library I'm using seems to be broken and had problems with loading certificates from variables instead of the file system...
Firefox doesn't import the created root certificate, only the ones created by openssl, I think it's because of the missing authorityKeyIdentifier extension...

**Comment by dlongley** [comment]
The failure to import a root CA certificate because it lacked an `authorityKeyIdentifier` extension would be unusual. Most Root CA certificates don't have authorityKeyIdentifier extensions anyway -- as they would just duplicate the information from the subjectKeyIdentifier and be a waste of space.

Regarding other potential problem information in the certificate, I googled a quick check list and found this comment:

https://bugzilla.mozilla.org/show_bug.cgi?id=492900#c7

**Comment by ThauEx** [comment]
SInce my issues is solved for now, I will close this issue.
Thanks again.

**Comment by dio** [comment]
@ThauEx do you have a full example on how to generate self-signed certs?

**Comment by ThauEx** [comment]
Sure,    
https://github.com/ThauEx/ffrk-proxy/blob/master/tests/createRootCa.js
and here     
https://github.com/ThauEx/ffrk-proxy/blob/master/lib/cert.js

I hope it helps

**Comment by dmail** [comment]
> I hope it helps

Definitely yes, I am going to try the code you linked and let you know if it works, thank you very much for sharing it.
