### ISSUE TITLE
ECB mode for AES

### ISSUE THREAD

**Issue by gausie** [digitalbazaar/forge#272]
Could this be supported?

**Comment by dlongley** [comment]
Yes. Landed in: https://github.com/digitalbazaar/forge/commit/38e95e6841a12c836a33482f87e9bc5556d15d31

Available in version: 0.6.31.

**Comment by gausie** [comment]
Fantastic! Managed to do my crypto with the Node built-in in the end but great job!

Will move onto this if I ever need to loose the OpenSSL dep.
