### ISSUE TITLE
Wrong SHA-256 computation

### ISSUE THREAD

**Issue by brillout** [digitalbazaar/forge#277]
For the following file

https://fb.me/react-0.13.3.min.js

forge computes a SHA-256 hash of
```
3bfb4252025da38d243bf37438283943f3221c092a8d3eb145d59ce8ee012c16
```

sha256sum of GNU coreutils and many other implementations computes a SHA-256 hash of 
```
a9cabcd164e8e495c28685591c7d2e4d9cab95a8daff1c52abf9be221fffd74f
```

**Comment by fxa** [comment]
Please post your code with wich you calculated the hash.
Btw I used
openssl dgst -hex -sha256 react-0.13.3.min.js
and got the same result as you with coreutils


On 03.07.2015 16:26, brillout wrote:
> For the following file
> 
> https://fb.me/react-0.13.3.min.js
> 
> forge computes a SHA-256 hash of
> ```
> 3bfb4252025da38d243bf37438283943f3221c092a8d3eb145d59ce8ee012c16
> ```
> 
> sha256sum of GNU coreutils and many other implementations computes a SHA-256 hash of 
> ```
> a9cabcd164e8e495c28685591c7d2e4d9cab95a8daff1c52abf9be221fffd74f
> ```
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/digitalbazaar/forge/issues/277
> 


-- 
Franz Antesberger
Alexander Ferdinand Str 3
93051 Regensburg
info@franz-antesberger.de
0160 374 84 95

**Comment by fxa** [comment]
hmmm,
I don't get your result with forge, but the same as coreutils
I just tried:

> var forge = require('node-forge')
> var f = fs.readFileSync('../../react-0.13.3.min.js', 'utf8')
> var md = forge.md.sha256.create()
> md.update(f)
> console.log(md.digest().toHex())
a9cabcd164e8e495c28685591c7d2e4d9cab95a8daff1c52abf9be221fffd74f

what did you do to get
3bfb4252025da38d243bf37438283943f3221c092a8d3eb145d59ce8ee012c16



On 03.07.2015 16:26, brillout wrote:
> For the following file
> 
> https://fb.me/react-0.13.3.min.js
> 
> forge computes a SHA-256 hash of
> ```
> 3bfb4252025da38d243bf37438283943f3221c092a8d3eb145d59ce8ee012c16
> ```
> 
> sha256sum of GNU coreutils and many other implementations computes a SHA-256 hash of 
> ```
> a9cabcd164e8e495c28685591c7d2e4d9cab95a8daff1c52abf9be221fffd74f
> ```
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/digitalbazaar/forge/issues/277
> 


-- 
Franz Antesberger
Alexander Ferdinand Str 3
93051 Regensburg
info@franz-antesberger.de
0160 374 84 95

**Comment by brillout** [comment]
My bad, I forgot to call `create()` before `update()`

Sincere apologies.
