### ISSUE TITLE
How can I extract the public key from the x.509 certificate ?

### ISSUE THREAD

**Issue by tngan** [digitalbazaar/forge#278]
I have a x.509 certificate in string format, e.g.  MIIB+jCCAWOgAwIBAgIB...
How can I extract the public key just using the string, without saving it as .pem manually first.

**Comment by dlongley** [comment]
```js
var certString = 'MIIB+jCCAWOgAwIBAgIB...';

// base64-decode DER bytes
var certDerBytes = forge.util.decode64(certString);

// parse DER to an ASN.1 object
var obj = forge.asn1.fromDer(certDerBytes);

// convert ASN.1 object to forge certificate object
var cert = forge.pki.certificateFromAsn1(obj);

// get forge public key object
var publicKey = cert.publicKey;

// `publicKey` can now be used to verify, encrypt, etc.
// if you did want to convert it to PEM format for transport:
var pem = forge.pki.publicKeyToPem(publicKey);
```

**Comment by tngan** [comment]
It works, thanks very much.

**Comment by petermikitsh** [comment]
Works great! Thanks.

**Comment by tyrsius** [comment]
@dlongley I must be missing something, because I am getting an error when calling `verify`.

```
Encrypted message length is invalid.] length: 342, expected: 256
```

I am able to get the public key with the directions above. I have used this public key via the `pem` package, and validated this payload. I am confident it is correct.

I have tried

```
var md = forge.md.sha1.create()
md.update(jwt.payload, 'base64')
return key.verify(md.digest().getBytes(), jwt.signature)
```

and 

```
var buf = new Buffer(jwt.payload, 'base64')
return key.verify(buf, jwt.signature)
```

both are failing. Am I using the `verify` method incorrectly?

**Comment by dlongley** [comment]
@tyrsius,

The message digest `update` API in forge 0.6.x does not support `base64` as an encoding. It should really be throwing an error to warn you of this. You'll need to use: `forge.util.decode64(foo)` on your data to decode it first. Also, you probably need to be using a `base64url` decoder library for JWTs -- they don't use standard base64 encoding.

**Comment by herrjemand** [comment]
Cannot read public key. OID is not RSA.

 *(
