### ISSUE TITLE
Detached PKCS#7 signature

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [digitalbazaar/forge#279]
Will be there any parameter to generate attached or detached PKCS#7 signature? It would be very useful. 

I mean something like this:

```
signature = createPkcs7(data, false) // get pure signature, without data
signature = createPkcs7(data,true)  // get pkcs7 signature with attached data
```

**Comment by dlongley** [comment]
I haven't looked into it yet, but, naively, it does seem like it would be fairly easy to support detached signatures. We'll keep this issue open as a desirable future feature; PRs welcome.

**Comment by fadlijuniarso** [comment]
@BaurzhanSakhariev you can check this one: https://gitlab.com/rootcaid/kominfo-pki-websdk/blob/master/lib/forge/pkcs7.js#L331

**Comment by vbuch** [comment]
@dlongley The changes propsed by @fadlijuniarso 3 years ago: https://github.com/digitalbazaar/forge/pull/605

**Comment by davidlehn** [comment]
Thanks to @vbuch and others, the feature was added in 0.7.6:
https://github.com/digitalbazaar/forge/blob/master/CHANGELOG.md
https://github.com/digitalbazaar/forge#pkcs7
