### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by code-tree** [digitalbazaar/forge#282]
Does Forge have any goals for browser support, or any current data on what browsers work/don't work?

I can't seem to find any official information, especially regarding IE support.

Note: I'm only trying to get AES, RSA, and SHA256 working in at least IE9+ at the moment.

Thanks for your work

**Comment by dlongley** [comment]
@code-tree,

> Does Forge have any goals for browser support, or any current data on what browsers work/don't work?

Our main goal is to be compatible with the most recent stable versions of the most commonly used browsers. We may sometimes take some extra steps to support older browsers if it doesn't require too much work/won't substantially impact performance on modern browsers.

> I can't seem to find any official information, especially regarding IE support.

Yeah, we need to do a better job of continuous testing in a variety of browsers and reporting the results. We're happy to accept help in these areas :)

> Note: I'm only trying to get AES, RSA, and SHA256 working in at least IE9+ at the moment.

To my knowledge, everything should work just fine with IE9+. I believe, in fact, forge may still be compatible with IE7-IE8.

> Thanks for your work

Sure!

**Comment by code-tree** [comment]
That's great to hear, thanks.

**Comment by dlongley** [comment]
@mattcollier could you look into adding saucelabs support now that #456 has been merged?

**Comment by dlongley** [comment]
Duplicates #261.
