### ISSUE TITLE
Extracted privateKey from pkcs12 has different structure to privateKey that generated by native webcrypto

### ISSUE THREAD

**Issue by herpiko** [digitalbazaar/forge#292]
Hi,

I trying to extract the privateKey from a PKCS12. My goal : the extracted privateKey should be able to imported to a webcrypto key and converted to PEM format.

<pre>
var p12Der = forge.util.decode64(p12base64);
var p12Asn1 = forge.asn1.fromDer(p12Der);
var p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, "password_string");
var keyBags = p12.getBags({bagType: forge.pki.oids.pkcs8ShroudedKeyBag});
var bag = keyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0];
var privateKey = bag.key;
</pre>

But the ``bag.key`` object has different structure to jwk (privatekey) that generated from native webcrypto API.

This is the private key's jwk from native webcrypto
![screenshot from 2015-09-03 17-10-26](https://cloud.githubusercontent.com/assets/2534060/9655906/be132bd4-525e-11e5-882a-72697570dd36.png)

And this is the private key's jwk that extracted from pkcs12
![screenshot from 2015-09-03 14-59-29](https://cloud.githubusercontent.com/assets/2534060/9655668/0e976d7e-525d-11e5-8724-2da37f5d84bc.png)

I was tried to convert this extracted private key to PEM format and check it with openssl. But openssl gave me error :

<pre>
$ openssl rsa -in extractedPrivateKey.pem -check
140490032944784:error:0407B080:rsa routines:RSA_check_key:p not prime:rsa_chk.c:86:
140490032944784:error:0407B081:rsa routines:RSA_check_key:q not prime:rsa_chk.c:95:
140490032944784:error:0407B07F:rsa routines:RSA_check_key:n does not equal p q:rsa_chk.c:107:
140490032944784:error:0407B07B:rsa routines:RSA_check_key:d e not congruent to 1:rsa_chk.c:148:
140490032944784:error:0407B07C:rsa routines:RSA_check_key:dmp1 not congruent to d:rsa_chk.c:167:
140490032944784:error:0407B07D:rsa routines:RSA_check_key:dmq1 not congruent to d:rsa_chk.c:185:
140490032944784:error:0306E06C:bignum routines:BN_mod_inverse:no inverse:bn_gcd.c:525:
</pre>

Is there any other way to convert p12's extracted private key to PEM?

**Comment by dlongley** [comment]
See PKCS#8 on the README: https://github.com/digitalbazaar/forge#pkcs8

```js
var p12Der = forge.util.decode64(p12base64);
var p12Asn1 = forge.asn1.fromDer(p12Der);
var p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, "password_string");
var keyBags = p12.getBags({bagType: forge.pki.oids.pkcs8ShroudedKeyBag});
var bag = keyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0];
var privateKey = bag.key;
var pem = forge.pki.privateKeyToPem(privateKey);

// OpenSSL should be able to read the string stored in `pem`
```

For importing keys via the WebCrypto API, #255 and #256 may be of assistance.

**Comment by herpiko** [comment]
I can already convert the extracted private key to web crypto jwk using PEM format between them.
private key jwk (forge version) -> PEM -> standard jwk -> crypto key object
Anyway, thank you for pointing this out.
