### ISSUE TITLE
forge with ember-cli

### ISSUE THREAD

**Issue by acerov** [digitalbazaar/forge#293]
Hi,

how to use forge with ember-cli?
I did "bower install forge" and "npm install node-forge",
but when I try to use it like "var md = forge.md.md5.create();" I am getting error "forge is not defined"

Please help

**Comment by acerov** [comment]
anyone?
Please help, it must be some little quirk because I used it with older ember-cli version but after upgrade no luck

**Comment by dlongley** [comment]
I don't have any experience with ember-cli. Does anyone else?

If you could provide more information on how libraries are loaded by ember-cli or some debugging information, we may be able to assist you.

**Comment by acerov** [comment]
Hi, thank you for response,
good news are that I finally made some progress:
instead of :     app.import('bower_components/forge/js/forge.js');
this works:     app.import('bower_components/forge/js/forge.min.0.6.12.js');

but obviously with older minified version.
I have yet to learn how to "npm run minify" because on my win7-64 that command gives me just errors.

**Comment by aaroncraigongithub** [comment]
I know this is old but thought it worth mentioning that I've created an addon to wrap this library for use in Ember apps.

https://github.com/aaroncraigongithub/ember-cli-forge

**Comment by dlongley** [comment]
Closing as potentially resolved via above solutions and wrappers. Feel free to reopen if necessary.
