### ISSUE TITLE
Extract Private Key / Certificate from X.509 .p12 file

### ISSUE THREAD

**Issue by mojontwins** [digitalbazaar/forge#298]
Hello - I'm in the process of building s/mime into a webmail client. Everything goes fine, I'm able to encrypt/decrypt, sign/verify s/mime messages with the aid of forge (all private key fiddling must be done in the user's browser as we can't/shouldn't store/transmit private keys to the server).

My problem has to be with user interface. Right now I extract the user's private key and certificate from a .pem file and use HTML5 storage to store them in PEM - and use them later.

The .pem files my code imports are simple plain text files with Private Key (unprotected) and Certificate:

```javascript
Bag Attributes
    friendlyName: XXXXXX
    localKeyID: XX XX XX XX XX XX... 
Key Attributes: <No Attributes>
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
Bag Attributes
    friendlyName: XXXXXX
    localKeyID: XX XX XX XX ...
subject=/C=ES/O=FNMT/OU=FNMT Clase 2 CA/OU=501074646/CN=NOMBRE TOCINO MARIN ALBERTITO - NIF 55556666O
issuer=/C=ES/O=FNMT/OU=FNMT Clase 2 CA
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

I extract the stuff I need from there and store them in HTML5. Once they are stored, I use this code to create my private key and certificate:

```javascript
var pki = forge.pki;
var privateKey = pki.privateKeyFromPem (localStorage [prefix + '.pk']);
var cert = pki.certificateFromPem (localStorage [prefix + '.cer']);
```
And use them to work with my pkcs7-encoded messages. 

This works fine, but the process of obtaining pem formatted private keys is unacceptable for the average user of our Webmail, so I have to automate this and let the users use their .p12 files and enter their passwords, and extract the stuff I need from that information. And this is where I'm getting COMPLETELY lost. I get as far as using forge.pkcs12.pkcs12FromAsn1 to get a PFX object, but I don't know what to do with it.

```javascript
// p12Der has the contents of my .p12 file
var p12Asn1 = forge.asn1.fromDer(p12Der);
var p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, '<password>');
```

I just need to get my "privateKey" and "cert" from a X.509 .p12 file with a password-encoded private key. Any pointers?

**Comment by mattcollier** [comment]
Hello, does the example provided here help? 

https://github.com/digitalbazaar/forge/blob/f070f4afc37d2b0f3191ccb066e1b42c4eb3f473/tests/nodejs-create-pkcs12.js#L84

**Comment by dlongley** [comment]
> Hello, does the example provided here help?

It may, yes, but it involves iterating over the entire PKCS#12 container. Instead, you probably want to use one of the simpler filter mechanisms for your use case.

Keys are certificates are stored in "bags" in a PFX container. If you look at the PKCS#12 section of the [README](https://github.com/digitalbazaar/forge#pkcs12), you'll see that there are some ways to filter out bags by type, friendly name, or local ID. Any one of these approaches should work to get you the key and certificate you want.

**Comment by mojontwins** [comment]
Thanks for the prompt responses. They are quite helpful. I'll look into it, thanks.

**Comment by mojontwins** [comment]
Hello. I just drop by to tell you that with your unvaluable help I have solved my issues. Thank you again. You can close this if desired.

I've followed the example and succeeded completely. My .p12 just contain two bags: PK and just one certificate, plus it is just read once per user (and browser), so I'm not concerned about having to iterate the whole container.

Thanks again.

**Comment by mayooran99** [comment]
@mojontwins i'm having in issue with the lines var p12Asn1 = forge.asn1.fromDer(fs.readFileSync('C:/Users/macilamanym/Desktop/certs/mayoorancert.p12'));
var p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, 'qwerty'); 
How did you get it working? What have I done wrong with these lines? It throws an error saying bytes.length is not a function

**Comment by dlongley** [comment]
```js
var p12Asn1 = forge.asn1.fromDer(fs.readFileSync('C:/Users/macilamanym/Desktop/certs/mayoorancert.p12', 'binary'));
```

**Comment by mayooran99** [comment]
@dlongley that worked. Thanks mate. I followed the loadPkcs12 function in your example. How can I print the private key contents from this? 

`map[localKeyId].privateKey`

The above just prints the object. How can I get the private key buffer from it?  Also how can I get the certificate buffer from it? Any help would be greatly appreciated mate!

**Comment by dlongley** [comment]
@mayooran99,

Do these examples help?

https://github.com/digitalbazaar/forge#pkcs12

**Comment by mayooran99** [comment]
Thanks a lot for the prompt replies :) I got it working.

**Comment by dlongley** [comment]
@mayooran99,

> Thanks a lot for the prompt replies :) I got it working.

Sure and great!

**Comment by alawatugoda** [comment]
Dear mates,
I'm trying to read a private key file and certificate from a folder, create a .p12 file and write it back to the same folder using node forge. I have tried this but couldn't properly write the p12 file into the folder. Could you please help me with this?

My code was:

var crt = fs.readFileSync ('jiji.cert.pem');
var crt_forge = forge.pki.certificateFromPem(crt);
var sk = fs.readFileSync ('jiji.key.pem');
var sk_forge = forge.pki.privateKeyFromPem(sk);

var newPkcs12Asn1 = forge.pkcs12.toPkcs12Asn1(sk_forge, [crt_forge], 'password');
var pkcs12 = forge.pkcs12.pkcs12FromAsn1(newPkcs12Asn1, false, 'password');
fs.writeFile("cert.test.p12", pkcs12, function(err) {
        if(err) {
          return console.log(err);
        }
      }); 

My lack of knowledge in these file formats probably put me into this trouble.
