### ISSUE TITLE
Does not work with AMD loader?

### ISSUE THREAD

**Issue by liuzhen2008** [digitalbazaar/forge#299]
I have a AMD loader implemented on the sever side. But when I do 
define("moduleName", ["node-forge", "my other modules"], function(nodeforge, otherModules) {});
I get Error: Cannot find module './aes'

Googling around, it seems that the issue is fixed sometime ago. Does that mean there is an AMD loader implementation issue on my side?  Or is there some kind of workaround?

**Comment by dlongley** [comment]
Using RequireJS and a `packages` config that includes forge like so:

```json
"packages": [
    {
      "name": "forge",
      "main": "js/forge.js",
      "location": "/bower-components/forge"
    }
]
```

Should allow you to do this:

```js
define(['forge'], function(forge) {
  // ...
});
```

An example of including individual modules from forge:

```js
define(['forge/js/md', 'forge/js/pki', 'forge/js/util', function(md, pki, util) {
  // ...
});
```

We want to make loading forge much easier and have it work with a variety of loaders in the future, see number 6 of #203.

**Comment by ysangkok** [comment]
@liuzhen2008 I have replaced RequireJS with CommonJS (e.g. using Webpack). Check it out, maybe it works for you: https://github.com/digitalbazaar/forge/pull/357
