### ISSUE TITLE
ASCII-armored openPGP

### ISSUE THREAD

**Issue by vSaKv** [digitalbazaar/forge#302]
Hi,
first of all thank you for great library. 

Currently I run into some problem with interoperability, and seek your help to point me in right direction or if this feature may become available in forge. 

Is there any way  I can convert ASCII-armored pgp key into pem format using forge? or export pem key into ASCII-armored format? 
I would appreciate some direction .

Thank you

**Comment by mattcollier** [comment]
@vSaKv 

I don't think forge can help you with that, but I found this post about working with pgp keys in javascript: http://blog.rubbingalcoholic.com/post/42173323097/javascript-read-ascii-armor

**Comment by dlongley** [comment]
This may be of help:

https://github.com/openpgpjs/openpgpjs

**Comment by vSaKv** [comment]
@mattcollier thanks for the article, probably i will be able to work with it.

@dlongley Yes this is a library I was asking about, because I'm using forgejs internally, with plain pem keys, which is supported by forge. But openpgp accepts only armored keys, and I can't find a easy way to convert one into another.

**Comment by Jonybang** [comment]
@vSaKv hello, i got the same issue as you. Did you found the solution for convert forge private key to openpgp private key?
