### ISSUE TITLE
Need Error Message when trying to read DER private key

### ISSUE THREAD

**Issue by AlaRuba** [digitalbazaar/forge#308]
Hi,

I'm trying to read in the private keys encoded in DER (binary) files. I'm doing this in the browser. It seems you've gotten this question before, so I tried using the solutions you showed here 
http://stackoverflow.com/questions/24893292/issue-using-rsa-encryption-in-javascript
http://stackoverflow.com/questions/26028573/forge-errors-with-reading-p12-and-pfx-files

I read in the file this way
```
var selectedFile = event.target.files[0];
var reader = new FileReader();

reader.onload = function(event) {
    console.log(event.target.result)
    key = event.target.result.split(',')[1];
};

reader.readAsDataURL(selectedFile);
```
I keep it encoded in base64, for the next part. After reading stackoverflow, it seems I should do the following.
```
var pkeyDer = forge.util.decode64(key);
var pkeyAsn1 = forge.asn1.fromDer(pkeyDer);
var privateKey = forge.pki.privateKeyFromAsn1(pkeyAsn1);
``` 
However, this gets me the following error
```
Uncaught Error: Cannot read private key. ASN.1 object does not contain an RSAPrivateKey.
```

On another note, if the DER files are encrypted with a password. Is this the right way to get the key? I couldn't find anything in the README. 

Thanks so much and sorry to bug but I couldn't find the instructions in the README.

**Comment by dlongley** [comment]
@AlaRuba,

> Thanks so much and sorry to bug but I couldn't find the instructions in the README.

Sure and no problem. The README can and should always improve to catch any holes like this. Once you've converted from DER format to an ASN.1 object, it sounds like what you've got is an ASN.1 "EncryptedPrivateKeyInfo". You need to decrypt that before you can convert to a private key. See the code below:

```
var pkeyDer = forge.util.decode64(key);
var pkeyAsn1 = forge.asn1.fromDer(pkeyDer);

// decrypts an ASN.1 EncryptedPrivateKeyInfo
var privateKeyInfo = forge.pki.decryptPrivateKeyInfo(pkeyAsn1, 'password');

var privateKey = forge.pki.privateKeyFromAsn1(privateKeyInfo);
```

**Comment by AlaRuba** [comment]
That does the trick. Thanks
