### ISSUE TITLE
How to split signature

### ISSUE THREAD

**Issue by AlaRuba** [digitalbazaar/forge#309]
Hi,

I am creating a signature using the private key, using this line of code

```
var md = forge.md.sha256.create();
md.update(randomString, 'utf8');
var signature = privateKey.sign(md);
```

That works well. However, I'm trying to verify the signature using Golang's dsa library. When the Golang library signs, it returns the signature as two integers. I was wondering how to extract those two integers from the signature. Alternatively, I was wondering what's its class so I can find how it is constructed in the code in the repository, then maybe I can figure out how it is constructed.

Thanks

**Comment by dlongley** [comment]
DSA is the wrong algorithm, forge implements RSA (it is much more popular/prevalent). Use Golang rsa instead:

https://golang.org/pkg/crypto/rsa/

**Comment by AlaRuba** [comment]
Just to clarify, the VerifyPKCS1v15 is what I want right?

Thanks so much

**Comment by dlongley** [comment]
Yes, PKCS#1 v1.5 is the default in forge. Forge also supports RSA-PSS which is recommended for new apps, but for compatibility purposes use PKCS#1 v1.5.

**Comment by dlongley** [comment]
Note that you'll probably want to encode your signature as base64 (`forge.util.encode64(signature)`) for transport and then decode and verify on the other side.

**Comment by AlaRuba** [comment]
Thanks so much

**Comment by dlongley** [comment]
Sure!
