### ISSUE TITLE
Does forge work in IE8?

### ISSUE THREAD

**Issue by AlaRuba** [digitalbazaar/forge#310]
I'm getting a forge is undefined error in IE8. Just wanted to clarify if it works for that browser.

**Comment by dlongley** [comment]
We don't have any continuous integration tests for IE8, but forge has been known to run in IE8 (it has even run in IE7). The issue you're seeing may be related to how it's being required in the browser, for example, the dependency order must be correct, if you're using script tags.

**Comment by AlaRuba** [comment]
Really? It seems it use the Array.map function which is not supported in IE8.

http://stackoverflow.com/questions/30780813/javascript-library-forge-does-not-work-in-internet-explorer-ie8

To clarify, I'm talking about the forge.bundle.js that you generate.

**Comment by dlongley** [comment]
> Really? It seems it use the Array.map function which is not supported in IE8.

Yeah, it must have worked prior to that, or a perhaps a polyfill was used. Just serve a polyfill that provides the required methods along with forge. For example:

https://github.com/es-shims/es5-shim
https://github.com/plusdude/array-generics

**Comment by thicham** [comment]
I hvae the same probleme with ie8 and 9 for Uint8Array
did you have a solution for that
Thanks

**Comment by AlaRuba** [comment]
I forgot if I got it working, I think I just did ctrl-f everyone in the source code and replaced it with the polyfills. Good luck

**Comment by thicham** [comment]
Do you remember the polyfiils that you use
Thanks

**Comment by AlaRuba** [comment]
I unfortunately dumped the code out, because turns out IE8 backwards compatibility had to be thrown out for another reason.

Try this polyfill?
https://github.com/inexorabletash/polyfill/blob/master/typedarray.js

**Comment by thicham** [comment]
I already try it it works with IE9 but not IE8
Probleme is probabaly the way I do it , I just add the ployfill as a script without replacement in util.js
