### ISSUE TITLE
forge/js/xhr.js : the implementation of XHR object is not compatibility with the XHR standard

### ISSUE THREAD

**Issue by xang8848** [digitalbazaar/forge#311]
for example, at least, the function "send" of XHR object should support blow form:
void send();
void send(ArrayBuffer data);
void send(ArrayBufferView data);
void send(Blob data);
void send(Document data);
void send(DOMString? data);
void send(FormData data);
(refer https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest)

I tried to send data using XHR in the form "void send(FormData data)" , but it work incorrectly.

**Comment by xang8848** [comment]
The XHR object has implemented level 1 of XHR, and not implement level 2 of XHR.

**Comment by dlongley** [comment]
There's no plan to implement anything further on forge's xhr object. It will likely be deprecated in the next version of forge. It depends on flash, which is being replaced on the Web with HTML5 features.

**Comment by xang8848** [comment]
thank you!
