### ISSUE TITLE
decodeUtf8 and encodeUtf8 broken on iOS WebView (i.e. Chrome for iOS)

### ISSUE THREAD

**Issue by coolaj86** [digitalbazaar/forge#313]
These functions don't work everywhere:

```
util.encodeUtf8 = function(str) {
  return unescape(encodeURIComponent(str));
};

util.decodeUtf8 = function(str) {
  return decodeURIComponent(escape(str));
};

// throws URI Error
```

I was doing the same thing with some other code of my own and ran into the same problem, so thankfully I know how to solve it and it is tested working.

```
util.encodeUtf8 = function(str) {
  var escstr = encodeURIComponent(str);
  // replaces any uri escape sequence, such as %0A,
  // with binary escape, such as 0x0A
  var binstr = escstr.replace(/%([0-9A-F]{2})/g, function(match, p1) {
    return String.fromCharCode(parseInt(p1, 16));
  });

  return binstr;
};

util.decodeUtf8 = function(binstr) {
  var escstr = binstr.replace(/(.)/g, function (m, p) {
    var code = p.charCodeAt(0).toString(16).toUpperCase();
    if (code.length < 2) {
      code = '0' + code;
    }
    return '%' + code;
  });

  return decodeURIComponent(escstr);
};
```

**Comment by coolaj86** [comment]
Actually, I thought it was tested working, but it also is failing now.

Digging deeper...

**Comment by coolaj86** [comment]
Looks like a bug in Chrome's implementation of `console.log()` which explicitly calls any explicitly defined `.toString()` method where it should instead be logging an object.

The real solution for this is to solve https://github.com/digitalbazaar/forge/issues/60 and https://github.com/digitalbazaar/forge/issues/203.

**Comment by dlongley** [comment]
Closing as the solution is on the roadmap.
