### ISSUE TITLE
Modular approach?

### ISSUE THREAD

**Issue by Dindaleon** [digitalbazaar/forge#314]
Hello,

I see forge package is big. Is there a way to load only the needed functions? Like cryptojs does.

**Comment by dlongley** [comment]
Each module uses an AMD interface. If you're using an AMD loader and set up, for example, a proper requirejs config, you can pull in just what you need and its dependencies.

Setting up AMD is more complicated than it should be but that's not really a forge problem. You can read about RequireJS here: http://requirejs.org/docs/start.html.

In the future we hope to support a multitude of different loaders and provide scripts to make integrating forge or whatever parts of forge you want more easily; see number 6 on the roadmap: #203.

**Comment by dlongley** [comment]
You can also see the example in #299.

**Comment by Dindaleon** [comment]
That's awesome! Keep up the great work. I will look into AMD and RequireJS later on. Thank you.
