### ISSUE TITLE
How to save key and iv in a database for later use?

### ISSUE THREAD

**Issue by Dindaleon** [digitalbazaar/forge#315]
Hello,

I need to save the key and iv in a database for later use. Both are generated the following way:
    var secret = forge.random.getBytesSync(32);
    var iv = forge.random.getBytesSync(32);

The problem is that if I save them just like that, and then retrieve them, they get corrupted. So, what is the proper way for storing and retrieving those values?

**EDIT**
I am saving them like this:

    var secretHex = forge.util.bytesToHex(secret);
    var ivHex = forge.util.bytesToHex(iv);

Then, when I need to decipher, I convert them back to bytes like this:

    var secretBytes = forge.util.hexToBytes(secretHex);
    var ivBytes = forge.util.hexToBytes(ivHex);
    var somedataBytes = forge.util.hexToBytes(somedataHex);

    var decipher = forge.cipher.createDecipher('AES-CBC', secretBytes);
    decipher.start({ iv: ivBytes });
    decipher.update(somedataBytes);
    decipher.finish();
    console.log('outputs decrypted hex ', decipher.output.toHex());

This gives me the following error:

    error TypeError: buffer.getBytes is not a function
    at ByteStringBuffer.util.ByteStringBuffer.putBuffer (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\node-forge\js\util.js:391:31)
    at [object Object].BlockCipher.update (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\node-forge\js\cipher.js:170:17)

**Comment by dlongley** [comment]
Wrap your bytes in a forge buffer:

```js
decipher.update(forge.util.createBuffer(somedataBytes));
```

**Comment by Dindaleon** [comment]
@dlongley great! That fixed it.

Another question, in this issue (https://github.com/digitalbazaar/forge/issues/135) you say to use at most 16 bytes for the IV. Could you please elaborate more on this? Can the key size be 32 bytes and the IV size only 16?

**Comment by dlongley** [comment]
@Dindaleon,

The IV size needs to match the block size for the cipher, not the key size. AES uses a 16 byte block size and hence a 16 byte IV. It doesn't matter what the key size is, the IV is always 16 bytes. AES-128 uses a 16 byte key and 16 byte IV, AES-192 uses a 24 byte key and a 16 byte IV, AES-256 uses a 32 byte key and a 16 byte IV. 

If you provide an IV of 32 bytes, the last 16 bytes will be ignored. So just use 16 bytes so there won't be any confusion.

**Comment by Dindaleon** [comment]
Perfect! Thank you.

**Comment by erlangp** [comment]
Thank you so much sir @dlongley :+1:

**Comment by TheGEN1U5** [comment]
> Wrap your bytes in a forge buffer:
> 
> ```js
> decipher.update(forge.util.createBuffer(somedataBytes));
> ```

I don't know how to thank you!!!
It worked!
