### ISSUE TITLE
Which one will potentially throws?

### ISSUE THREAD

**Issue by fadlijuniarso** [digitalbazaar/forge#322]
Hello,

From this following test, I could see it has big try catch to do the signing process,

https://github.com/digitalbazaar/forge/blob/2db093951e1cb99e87c6daf7c3d32817ece8ba93/tests/nodejs-sign-p7.js#L4-L32

Which lines do potentially throw?

Thank you!

**Comment by dlongley** [comment]
> Which lines do potentially throw?

Anything that receives bad input could throw: an unknown OID, a bad certificate, etc. So, for example, when adding certificates or signers, if a certificate is given in PEM format, it needs to be parsed -- which could yield a parse error if you give it bad data. If you don't set any message content an error will be thrown when trying to sign the message.

**Comment by fadlijuniarso** [comment]
Thank you!
