### ISSUE TITLE
How Do I load forge client side?

### ISSUE THREAD

**Issue by Dindaleon** [digitalbazaar/forge#323]
Hello,

I want to encrypt my users' passwords with forge client side. Is it possible to require forge client side?

Right now when I try to do so, I get the following error:

    Uncaught ReferenceError: Invalid left-hand side in assignment

I am importing it like this:

    const forge = require('node-forge')({ disableNativeCode: true });

**Comment by dlongley** [comment]
> Is it possible to require forge client side?

Yes. Use a module loader like [RequireJS](http://requirejs.org/). You can also fallback to using script tags if necessary. A variety of other module loaders have been used with success but we don't have a test suite yet to track them. Perhaps others could chime in with how they're loading forge.

Improving the build system to make it easier to generate the appropriate boilerplate for different loaders is on the roadmap (#203).
