### ISSUE TITLE
forge.cipher returns fewer bytes 

### ISSUE THREAD

**Issue by dimitrirostavo** [digitalbazaar/forge#324]
Hi there, 
Firstly, i want to say that the forge library is a god sent. It is really awesome. 

Secondly, I have a question 

I have this example 

```javascript
                                var decipher = forge.cipher.createDecipher('AES-CBC', aesKey);
                                 //encryptedData is just an ArrayBuffer.
				var decryptedData = new forge.util.ByteStringBuffer(encryptedData.byteLength);
				decipher.start({iv:iv,
					output:decryptedData
				});
				var buffer = forge.util.createBuffer(encryptedData);
				decipher.update(buffer);
				decipher.finish();
                               
```
Is there any reason for decryptedData.length not the same as encryptedData.byteLength ? 

What I am seeing is that encryptedData.byteLength is 64 
and decryptedData.length is coming back as 34.

Any help would be greatly appreciated.

**Comment by dlongley** [comment]
@dimitrirostavo,

> Firstly, i want to say that the forge library is a god sent. It is really awesome.

Thanks! Glad it's useful to you.

> Is there any reason for decryptedData.length not the same as encryptedData.byteLength?

Can you provide a runnable example with the unexpected result? It's hard to analyze what's going on otherwise. It sounds like the decryption may be failing (make sure you're checking the return value of `decipher.finish()` for `true`).

**Comment by dimitrirostavo** [comment]
Hi there, my apologies for not replying earlier. I was traveling and couldn't get a working sample for you.

Here is what I am seeing
```
window.addEventListener("load", function(event){
	//base 64 encoded key
	var key="vmap9moRFXdasAbl9gKOO3kHIGsrusbo3LaWK8GWhPg=";
	//encodedIV
	var iv = "Rk9X/lVYLqdpZ/hKvA6J2w==";
	//base64encoded<str<Uint8Buff>>>
	//Uint8 buffer actually contains the encrypted data;
	var encryptedData = "EHRb8izVF+WrUuAxDzEpCZDCvzJunt81egp/J2+WjK4=";
	decrypt(key, iv, encryptedData);
});

var createUInt8Buffer	= function(rawData) {
	var buffer = new Uint8Array(rawData.length);
	for (var i=0, strLen=rawData.length; i<strLen; i++)
	{
		buffer[i] = rawData.charCodeAt(i);
	}
	return buffer;
};

function decrypt(eKey, eIV, eEncryptedData)
{
	var key = forge.util.decode64(eKey);
	var iv 	= forge.util.decode64(eIV);

	var encrypedData = createUInt8Buffer(forge.util.decode64(eEncryptedData));
	var buff = forge.util.createBuffer(encrypedData);

	var decipher = forge.cipher.createDecipher('AES-CBC', key);
	decipher.start({iv:iv});
	decipher.update(buff);
	var didFinish = decipher.finish();
	if(!didFinish) {
		throw new Error("Could not decrypt");
	}
	var dPrivateKey = decipher.output.getBytes();
  if(dPrivateKey.length !== encrypedData.length) {
		throw new Error("Data sizes are not the same");
	}
}
```

**Comment by dimitrirostavo** [comment]
My test html file is really simple. 
```
<html>
<head>
	<script src="forge.js"></script>
	<script src="Test.js"></script>
</head>
</html>
```

**Comment by dimitrirostavo** [comment]
Please help. I'd really appreciate it. I've never seen this problem before. 
Thanks!

**Comment by dlongley** [comment]
@dimitrirostavo,

CBC mode encryption adds padding, that's why the encrypted data is larger than the decrypted data.

**Comment by dimitrirostavo** [comment]
Yup I understand it now. Sounds good. My application expects the bytes with the padding and the forge API is removing them which is what was causing the problem for me. 

Thank you for pointing that out. I really appreciate it.

**Comment by dlongley** [comment]
Sure :)
