### ISSUE TITLE
Firefox: Failed to load script (nsresult = 0x804b000d) error

### ISSUE THREAD

**Issue by animalillo** [digitalbazaar/forge#329]
When i try to run this example on firefox i get a nice error, so i'm unable to generate a keypair asynchronously, just in a synchronous way. Any ideas of what am i doing wrong or if it's a bug?

var kp;
forge.rsa.generateKeyPair({bits: 512, workers: 2}, function(err, keypair) {
  kp = keypair; console.log(err);
});
undefined
Error: Failed to load script (nsresult = 0x804b000d)

Cloned today master (b922df6ee8fbf8b141549e3298a88e47b6b4e832).
Firefox 42.0
Ubuntu Mate 15.10 x64
Using the minified version as specified in the readme (npm install; run minify) and including forge.min.js in the browser

**Comment by animalillo** [comment]
Also, i've tried different worker (-1, 2, 4) and bits (512, 1024, 2048) values

**Comment by dlongley** [comment]
Haven't been able to reproduce; closing until repeatable.

**Comment by davidlehn** [comment]
The "Failed to load script" error may mean you need to add the workerScript option and point to the proper prime.worker.js file (and jsbn.js in 0.6.x).
