### ISSUE TITLE
forge  in IE8 and 9

### ISSUE THREAD

**Issue by thicham** [digitalbazaar/forge#331]
I have an issue with forge in ie8 and 9, in fact we use util.js in our project and we get an error with 
Uint8Array
could please advise us about that issue, i read about plyfill but i don't know how to integarte it 
Thanks

**Comment by dlongley** [comment]
@thicham,

Hi, can you provide the exact error text and line number?

Thanks!

**Comment by dlongley** [comment]
Integrating a polyfill should just be a matter of including it in a script tag (or via whatever other module loading mechanism you're using) prior to including forge.

**Comment by thicham** [comment]
Thank you for your response
The line number is 1754 in util.js (here the function name util.binary.base64.decode = function(input, output, offset) )

I'am not a javascript programmer, but i try to resolve that problem in our application 
I just copy pat the code of  this plolyfill in the end of  util.js  :https://github.com/inexorabletash/polyfill/blob/master/polyfill.js
and it seems that it works for ie9, bit i'am not sure if it is the good solution

**Comment by thicham** [comment]
The error is : Unit8Array is undefined

**Comment by thicham** [comment]
When I add polyfill.js i got the message withe ie98: 
Function.prototype.apply: Array or arguments object expected

**Comment by davidlehn** [comment]
Where is the new failure?  In the polyfill or forge?

IE8 is obsolete and often unsupported by many projects at this point, so you may need to search around to find polyfills or other support libraries that address issues in a IE8 compatible way.  In this case you might need polyfills to fix polyfills!

Please add details when you are reporting issues and in followups.  I don't think the forge developers have the time or access to IE8 to test potential fixes so we need specific issue details when searching the web and guessing on what to try.  If you can get it to work, we'd be happy to add docs on how it was done.  Thanks.

**Comment by thicham** [comment]
The new failure is on the polyfill

**Comment by davidlehn** [comment]
Please provide details so the forge developers can help you.  Browser console logs, stack traces, snippets of the failing code, line numbers, links to the code, etc.  Hopefully IE8 has some useful console or debug output.
