### ISSUE TITLE
How to generate private key, encrypt it with password & add to p12 file?

### ISSUE THREAD

**Issue by shobhitsingh** [digitalbazaar/forge#332]
As the Subject says I am doing this in Java and wanted to achieve same effect in Javascript.

What I have done till now
var newPkcs12Asn1 = forge.pkcs12.toPkcs12Asn1(
keys.privateKey, [{add password encrypted private key here},cert,caCert], password,
   {generateLocalKeyId: true, friendlyName: 'test'});
 var newPkcs12Der = forge.asn1.toDer(newPkcs12Asn1).getBytes();

Is this possible in forge?
I am doing similar in Java, but not able to figure out how to do this in forge.

Actually I wanted to achieve this as an example, which I did in Java
alias
Private RSA Key
Strength: 1024 bits

Algorithm:	RSA
Size:	1024
Fingerprints
SHA1:	83 90 9D 4C D1 9D 13 5C 57 8E 03 78 5B D4 AA 01 57 66 49 FC
SHA256:	7B A9 DD 10 2B 87 47 64 C0 38 8B 29 2B 50 D1 9F 77 C6 38 2D F9 B6 9B 33 E0 96 A5 0B 32 32 B4 49

**Comment by shobhitsingh** [comment]
I have added this code to create encrypted cipher
var numIterations = 20,
          keyLength = 24,
          password = forge.util.createBuffer('password'),
          salt = new forge.util.ByteBuffer(new Uint8Array([0xc7, 0x73, 0x21, 0x8c, 0x7e, 0xc8, 0xee, 0x99])),
          derivedKey = forge.pkcs5.pbkdf2(password, salt.getBytes(), numIterations, keyLength, forge.md.md5.create()),
          iv = forge.random.getBytesSync(8);
var cipher = forge.des.createEncryptionCipher(derivedKey);
cipher.start(iv);
cipher.update(forge.util.createBuffer('someBytes'));
cipher.finish();
var encrypted = cipher.output.toHex();
Now how do I add this to p12 file?
Can anyone give any pointers on this?
Thanks.

**Comment by dlongley** [comment]
Your original code was fine other than adding the private key as a certificate. All you need to do is this:

```
// generate a p12 using AES (default)
var p12Asn1 = forge.pkcs12.toPkcs12Asn1(
  privateKey, certificateChain, 'password');
```

If you want your PKCS#12 to be importable in Firefox/Chrome, use `3des` encryption instead:

```
// generate a p12 that can be imported by Chrome/Firefox
// (requires the use of Triple DES instead of AES)
var p12Asn1 = forge.pkcs12.toPkcs12Asn1(
  privateKey, certificateChain, 'password',
  {algorithm: '3des'});
```

So, taking your original code, it should look something like this:

```
var newPkcs12Asn1 = forge.pkcs12.toPkcs12Asn1(
  keys.privateKey, [cert, caCert], password,
  {generateLocalKeyId: true, friendlyName: 'test', algorithm: '3des'});
var newPkcs12Der = forge.asn1.toDer(newPkcs12Asn1).getBytes();
```

**Comment by shobhitsingh** [comment]
Thanks a lot, probably, I missed the 3des encryption.
With algorithm: '3des', it works as expected.
