### ISSUE TITLE
AES CBC 256 IV Size

### ISSUE THREAD

**Issue by thorst** [digitalbazaar/forge#335]
var key = forge.random.getBytesSync(32);
var iv = forge.random.getBytesSync(16);

Dumb question....

I believe I read that the IV size stays the same no matter the key size, so its best to keep it 16 so that there is no mistaking the size that's being used.

I just wanted to confirm the above code is the correct way aes 256 should look.

**Comment by dlongley** [comment]
The IV size must match the block size for the algorithm. It stands for "Initialization Vector" and it gets "mixed" into the blocks of data you encrypt. It is used to guarantee that you start encrypting with a unique value for every new encryption. If one wasn't required by a block encryption scheme, then every time you encrypted the same message with the same key, the output would be the same. An attacker could use this information to learn more than they should know about the encrypted data.

The block size for AES is always 16 bytes, regardless of the key size. Therefore, the IV size is always 16 bytes, regardless of the key size.

**Comment by thorst** [comment]
Thats what i thought.
I generate the key once, and then a new iv each time i encrypt. I transmit my iv in plain text along with my based and encrypted text.
Thanks again.
--
Sent from Mail.Ru app for Android Saturday, 12 December 2015, 09:33AM -05:00 from Dave Longley < notifications@github.com> :
