### ISSUE TITLE
Difference between PEM and DER when file is passed in as a buffer

### ISSUE THREAD

**Issue by AlaRuba** [digitalbazaar/forge#336]
Hi,

I opened a previous issue, but I think this issue better encapsulates the problem.

So, I'm uploading my certificates to be parsed. I'm trying to handle both PEM and DER files, but they both get uploaded in a multi-part form that stores the contents in a buffer.

Now, I have the PEM working. If I pass in the buffer containing the buffer that has PEM format,

I can get the certificate this way

    var certString = certBuffer.toString();
    var cert = pki.certificateFromPem(certString);

Now I have the DER version of the same certificate that just worked. Now, I uploaded the DER file the same way, and I thought I would be able to extract the certificate the same way

    var certString = certBuffer.toString();
    var obj = forge.asn1.fromDer(certString);
    var cert = forge.pki.certificateFromAsn1(obj);

However, I get the following error  Cannot read X.509 certificate. ASN.1 object is not an X509v3 Certificate

I was wondering if DER should be handled differently. I notice when I print the string, the content is some haphazard malformed data with some correct data. Whereas when I open the DER in Sublime, it's just bytes.

I was wondering how to handle this.

Sorry to bug and great work.

**Comment by AlaRuba** [comment]
I decided to print out the buffer in hex and I got

    var certString = certBuffer.toString('hex');

and the output matches what I have in the file when I open in Sublime minus spaces between every 4 characters.

However, I still get a Too few bytes to read ASN.1 value. error. I was wondering if you could shed light on this error message.

**Comment by dlongley** [comment]
Forge uses binary-encoded strings. If you're using node.js, use 'binary' encoding:

```
var certString = certBuffer.toString('binary');
```

If you're using something else, you'll need to provide more details on how you populated `certBuffer` and what type it is.

**Comment by AlaRuba** [comment]
That did the trick.

I wanna thank you so much for being so responsive and helpful.

**Comment by dlongley** [comment]
> That did the trick.

Great!

> I wanna thank you so much for being so responsive and helpful.

Sure :). Glad it's working for you now.
