### ISSUE TITLE
PublicKey.rightAlign()

### ISSUE THREAD

**Issue by AlaRuba** [digitalbazaar/forge#337]
Hi,

I'm trying to use the forge library to recreate some functionality in the golang ocsp library (the only node ocsp library I could find made some assumptions about my certificates that aren't true).

I noticed in the crypto golang library. They have this function on public keys called RightAlign() used in this context.

    h := opts.hash().New()
    h.Write(publicKeyInfo.PublicKey.RightAlign())

I was wondering if forge has a similar function.
https://golang.org/pkg/encoding/asn1/#BitString.RightAlign

**Comment by ysangkok** [comment]
There is no such function, but the code is easy to understand, you should be able to add it yourself.
