### ISSUE TITLE
Reading Certificate Data from p12 file

### ISSUE THREAD

**Issue by shobhitsingh** [digitalbazaar/forge#338]
I am trying to read p12 file. I guess the code is quite clear in the documentation and it's like this

```
// Read file in binary contents
var p12Pem = fs.readFileSync("file.p12");
//base 64 encode file
var b64P12 = forge.util.binary.base64.encode(new Uint8Array(p12Pem));
var p12Asn1 = forge.asn1.fromDer(b64P12, false);
var p12Parsed = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, 'password');
console.log('not printed');
```

But pkcs12FromAsn1 is not working. Have I missed anything?

I am able to extract the certificate and private key using openssl
openssl pkcs12 -in file.p12 -out keyStore.pem -nodes

Any pointers would be great.
Thanks.

**Comment by davidlehn** [comment]
I think a `.p12` file is already in binary DER format. Try reading the file in as binary and using it directly:

```
// Read file in binary contents
var p12 = fs.readFileSync('file.p12', 'binary');
var p12Asn1 = forge.asn1.fromDer(p12, false);
var p12Parsed = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, 'password');
```

**Comment by shobhitsingh** [comment]
It works.
I always thought without the 'utf8', node fs reads file in binary.
Thanks a lot.
