### ISSUE TITLE
Expose handshake events

### ISSUE THREAD

**Issue by cintolas** [digitalbazaar/forge#339]
I am writing a library to use websockets to connect to an RDP server

The RDP protocol initiates the TLS connection after an initial negotiation 
I need to send each individual Client Message to the server and then process the server responses

The current library wraps the handshake messages and then puts them in a queue.

Is there a way I can grab the messages and send them over the websocket connection to my remote server?

**Comment by dlongley** [comment]
The TLS implementation is completely abstracted away from any particular socket/transport layer. You can transport the messages however you want. Whenever more TLS data is ready, the `tlsDataReady` callback will be called on the TLS connection:

```js
var conn = forge.tls.createConnection({
  // ...
  tlsDataReady: function(c) {
    var bytes = c.tlsData.getBytes();
    // send TLS data to server however you want
    // eg: send "bytes" via a websocket
  },
  dataReady: function(c) {
    var bytes = c.data.getBytes();
    // do something with decrypted bytes
  },
  // ...
});
```
