### ISSUE TITLE
Public/Private Key Encryption in JavaScript?

### ISSUE THREAD

**Issue by simkessy** [digitalbazaar/forge#341]
I'm trying to figure out a licensing system for my client-side application. I'm trying to figure out if this process i'm thinking of is at all possible. 

- Basically say I have a `private key` and in my script I store a `public key`
- Then I take `secret message` encrypt it using my `private key` into 
- I save `SOME HASH` in my DB
- The application retrieves `SOME HASH`, decrypts it using `public key` back into `secret message`
- Then I can do whatever validation to determine if `secret message = secret message`

Is this at all possible?

**Comment by ysangkok** [comment]
This question is not specific to forge, try asking it on the cryptography StackExchange.
