### ISSUE TITLE
`forge.pki.rsa.generateKeyPair` performance issue?

### ISSUE THREAD

**Issue by fuqcool** [digitalbazaar/forge#351]
`forge.pki.rsa.generateKeyPair(2048)` takes several seconds to finish on my env(node#5.x, MacOS). Is their anyway to speed it up?

**Comment by dlongley** [comment]
Speeding up the pure JavaScript implementation would involve doing some serious math -- whilst avoiding the patent asteroid field.

RSA key generation requires finding very large prime numbers to construct a secret key for you. It's a very CPU-intensive process. The only easy way to speed it up is to use native code (which is available to you if your browser supports the Subtle WebCrypto API). Forge will eventually wrap this code bringing the speed improvements to any environment that supports it.

**Comment by dlongley** [comment]
See #347 for speeding things up w/node.
