### ISSUE TITLE
Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by HexAtlanta** [digitalbazaar/forge#353]
Installed a fresh version of forge from bower 
 bower install forge --save

That add me "forge": "~0.6.38" as dependecies.

the the app goes in error with the error above, line 50:

var tmpDefine = define;
--> define = function(ids, factory) {
  deps = (typeof ids === 'string') ? factory.slice(2) : ids.slice(2);
  if(nodeJS) {
    delete define;
    return tmpDefine.apply(null, Array.prototype.slice.call(arguments, 0));
  }
  define = tmpDefine;
  ret

**Comment by ysangkok** [comment]
Might be a RequireJS related problem. I have a PR for switching to CommonJS/Webpack: https://github.com/digitalbazaar/forge/pull/357 Maybe it solves your issue.

**Comment by dlongley** [comment]
Should be addressed in a new release now that #456 has been merged.
