### ISSUE TITLE
key pair to ASN.1 to DER, then recovering in reverse

### ISSUE THREAD

**Issue by UnsungHero97** [digitalbazaar/forge#354]
I'm trying to convert a key pair to ASN.1, then to DER, and then the reverse process to recover the original key pair. However, it looks like the result after the reversal is different than the original key pair.

    forgeKeyPair = forge.rsa.generateKeyPair(128)

    publicKeyAsn1_1  = forge.pki.publicKeyToAsn1(forgeKeyPair.publicKey)
    privateKeyAsn1_1 = forge.pki.privateKeyToAsn1(forgeKeyPair.privateKey)
    publicKeyDer     = forge.asn1.toDer(publicKeyAsn1_1)
    privateKeyDer    = forge.asn1.toDer(privateKeyAsn1_1)

    publicKeyAsn1_2  = Forge.asn1.fromDer(publicKeyDer)
    privateKeyAsn1_2 = Forge.asn1.fromDer(privateKeyDer)
    publicKey        = Forge.pki.publicKeyFromAsn1(publicKeyAsn1_2)
    privateKey       = Forge.pki.privateKeyFromAsn1(privateKeyAsn1_2)

After trying to recover the public and private key, the result is different than the original key pair. For example, in the original, I see this for the public key:

    forgeKeyPair.publicKey.n = {
      data: Array[6],
      s: 0,
      t: 5
    }

However, the recovered public key is this:

    publicKey = {
      data: Array[5],
      s: 0,
      t: 5
    }

The difference is the `data` array, which originally has 6 elements, but after recovery, it has 5 elements.

Is this expected behavior? If not, what am I doing wrong? Is it actually possible to do this reversal process and recover the original public and private keys?

**Comment by dlongley** [comment]
You're peeking at the implementation details of a BigInteger (from the `jsbn` library) to try and determine if two numbers are the same. But you'd have to understand those details to know how they matter (of if they don't). What does "data" mean? What do "s" or "t" mean?

The quickest way to find out is to ask the public API. You shouldn't have to know those details anyway.

In other words:

```js
var same = forgeKeyPair.publicKey.n.equals(publicKey.n);
```

Yields ```same === true```. So, it doesn't matter, the numbers are the same and the library promises you this via its public API.

**Comment by UnsungHero97** [comment]
Ok, cool! I didn't realize that there's an `.equals()` to help me out. The reason I'm doing this is because I'm trying to write unit tests, and I was using a different approach to testing equality. It seems like I should be using this `.equals()` instead.

**Comment by dlongley** [comment]
> How would you recommend I test equality between forgeKeyPair.publicKey and publicKey?

For now, use `.n.equals` and `.e.equals`. This will compare the modulus (n) and the exponent (e), which are the two components of an RSA public key.

We may consider adding an `equals` method to the public key in the future to abstract away comparing different kinds of keys (RSA, ECDSA, etc.) but we're not there yet.

**Comment by UnsungHero97** [comment]
Sounds good. That's an easy enough solution for unit tests.

Just curious, would it make more sense to convert the key to a different format that's easier to compare? For example, would I achieve the same equality check if I convert both keys to PEM and compare the resulting strings?

**Comment by dlongley** [comment]
> Just curious, would it make more sense to convert the key to a different format that's easier to compare? For example, would I achieve the same equality check if I convert both keys to PEM and compare the resulting strings?

Yup, you can do that as well. It's your call.

**Comment by UnsungHero97** [comment]
Awesome! Thanks for your help!

**Comment by dlongley** [comment]
Sure!
