### ISSUE TITLE
generating random integers

### ISSUE THREAD

**Issue by UnsungHero97** [digitalbazaar/forge#355]
Is there a util for generating random integers with forge? What's the forge way of doing something like this:

```
function getRandomInteger(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}
getRandomInteger(Number.MIN_SAFE_INTEGER, Number.MAX_SAFE_INTEGER)
```

**Comment by davidlehn** [comment]
You can get random bytes with `forge.random.getBytesSync` or `forge.random.getBytes`. Using that to get a random number in a range is a bit more difficult unless your range distance happens to be a power of two. One approach is to use the random bytes to create a floating point number similar to what Math.random() provides and do like your sample code. Another is to do a loop that gets the right number of bits that could represent your desired range, check you are not over the max, else try again. I'm not sure of other algorithms. Here's some info:

https://stackoverflow.com/questions/33609404/node-js-how-to-generate-random-numbers-in-specific-range-using-crypto-randomby
