### ISSUE TITLE
Virus detected in util.js ( FALSE warning )

### ISSUE THREAD

**Issue by DanailMinchev** [digitalbazaar/forge#360]
Hi,

I started using this awesome lib in my Apache Cordova app and sometimes I upload my Android / iOS binary in Gmail to distribute it.

So, when I upload the file as an attachment Gmail stops it with the message "Virus detected" (no information about specific file).
I've filtered all the files in the project for last changes and one by one I've found which one is problematic: https://github.com/digitalbazaar/forge/blob/master/js/util.js

I used last release one: https://github.com/digitalbazaar/forge/blob/0.6.39/js/util.js

What is interesting is that when I minify the project:
```
npm install
npm run minify
```
`js/forge.min.js` is not detected as virus, but only non-minified version of `util.js`

The file is detected as a virus `JS/Nemucod.S.gen` only with particular Antivirus Engines like "Cyren" and "F-Prot":

https://www.metascan-online.com/#!/results/file/f2e98400ee264a87bdb8965ab4d9fa4c/regular

https://www.virustotal.com/en/file/c72520f196427e691612505306f4493f214c298b6bdf83cbe4fbac55827dc70f/analysis/1455629433/

**Comment by dlongley** [comment]
@DanailMinchev,

Hmm, don't know what to say about that one. Clearly the file is not a virus -- and it's open source, you can inspect it yourself. It would be good to know what lines are triggering the false positive. Do you think you'd be able to determine that?

**Comment by DanailMinchev** [comment]
@dlongley 

I was surprised as well and wondering why it's detected as a virus.
Even with false warning our app can be rejected once uploaded to the app store, that's why I have created this issue.
I'm using `bower` and the minified version is not available.

Yes, I think I found where the problem is:

https://github.com/digitalbazaar/forge/blob/0.6.39/js/util.js#L1750

If you remove `util.binary.base64.decode` function the file passes all checks

**Comment by dlongley** [comment]
@DanailMinchev,

> If you remove util.binary.base64.decode function the file passes all the checks.

Can you try moving that function elsewhere or tweaking some variable names? Obviously we can't remove the base64 decoder. :)

> I'm using bower and the minified version is not available.

Yeah, the plan is to start making that minified version available once we sort out some other module loader/build issues. But don't wait on that.

**Comment by mattcollier** [comment]
@DanailMinchev I would recommend that you report this false positive to the AV vendor.  They have a form for doing so here:  http://support.f-prot.com/index.php?/Tickets/Submit/RenderForm/7

**Comment by DanailMinchev** [comment]
@dlongley 

Of course, I didn't mean to remove the function :) Just wanted to show you where is "the problem".
Anyway, I think I found the exact line which Google (and other AVs) doesn't like:
https://github.com/digitalbazaar/forge/blob/0.6.39/js/util.js#L1775
`out[j++] = ((enc3 & 3) << 6) | enc4;`

I tried with different variable names, etc - AV still detects it. I think AV analysis the code in a different way and if you add grouping operator the operators stack is changed and this works.

So, something silly like this:
`out[j++] = ((enc3 & 3) << 6) | enc4;`
-->
`out[j++] = (((enc3 & 3) << 6) | enc4);`
can do the trick. I know this way it's now optimized, but moving the function will not help as well - I have copied only the function in a separate file which is detected as a false virus.
Another way to "fix" this is to do some refactoring if it's possible, but I am not confident to do this.

If you like this change I can create PR, also I can change all the three `out[j++]` lines this way (for consistency).

@mattcollier 

Thank you, I will submit a ticket once we "patch" the project here and I will provide the link to this issue.

**Comment by dlongley** [comment]
If simply adding parentheses around that expression will "fix" the problem, let's do that.

**Comment by DanailMinchev** [comment]
@mattcollier 
I have submitted a ticket to `F-prot`

@dlongley 
I have created a pull request

**Comment by davidlehn** [comment]
This sounds like a sneaky plan to slowly transition people to LISP.

**Comment by DanailMinchev** [comment]
@dlongley

I checked the file again, it seems that `F-prot` has updated their signatures or at least Gmail, www.virustotal.com and www.metascan-online.com accept the file as a clean one.

I will close the issue and the pull request as they not needed anymore.

**Comment by dlongley** [comment]
Oh, ok, great!
