### ISSUE TITLE
Encrypt binary data in AES

### ISSUE THREAD

**Issue by Loceka** [digitalbazaar/forge#364]
Hello,

I have tried using binary data (compressed text) as input of the AES algorithm but I can't manage to correctly decrypt it.
For compressing the text I use LZString : http://pieroxy.net/blog/pages/lz-string/index.html

```javascript
<script type="text/javascript" src="https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.js"></script>
// ...
var text = "my text";
text = LZString.compress(text);

var key = forge.random.getBytesSync(32);
var iv = forge.random.getBytesSync(16);

var cipher = forge.cipher.createCipher('AES-CBC', key);
cipher.start({iv: iv});
cipher.update(new forge.util.ByteBuffer(text));
cipher.finish();

var decipher = forge.cipher.createDecipher('AES-CBC', key);
decipher.start({iv: iv});
decipher.update(new forge.util.ByteBuffer(cipher.output.data));
decipher.finish();

console.log("textOut : " + LZString.decompress(decipher.output.data));
```

If I skip the compress/decompress operation, the input text is successfully decrypted.
If I try decompressing the input compressed text, it is successfully decompressed.

But when the compressed text is encrypted and decrypted, it leads to an invalid byte string and cannot be decompressed.

Is there a way to handle binary data in this AES implementation ?

Thanks,
Loceka.

**Comment by dlongley** [comment]
Forge is expecting a 'binary' formatted text string, but you're passing it UTF-8. Try this instead:

```js
var text = "my text";
text = LZString.compress(text);

var key = forge.random.getBytesSync(32);
var iv = forge.random.getBytesSync(16);

var cipher = forge.cipher.createCipher('AES-CBC', key);
cipher.start({iv: iv});
cipher.update(forge.util.createBuffer(text, 'utf8'));
cipher.finish();

var decipher = forge.cipher.createDecipher('AES-CBC', key);
decipher.start({iv: iv});
decipher.update(cipher.output);
decipher.finish();

console.log("textOut : " + LZString.decompress(decipher.output.toString('utf8')));
```

**Comment by Loceka** [comment]
Thanks a lot !
I had played much with encoding, mainly in buffers, but didn't knew about `decipher.output.toString('utf8')`.

It works perfectly, thank you again.
Loceka.

**Comment by dlongley** [comment]
Sure :)
