### ISSUE TITLE
Correct format for pem to forge public key?

### ISSUE THREAD

**Issue by Sbopf** [digitalbazaar/forge#366]
Hi

I've just picked up forge and I'm attempting to send an rsa public key from an API to the client side and load it into forge. 
Using:
forge.pki.publicKeyFromPem(result.Key);

This does not like my server generated key, so I'm wondering if I'm missing some encoding or padding.
Also when I generated a key pair in forge, then send it to the server which is using .NET RSACryptoServiceProvider functionality to load the public key, it says it the key is 2328 bytes but I'm generating it with:

rsa.generateKeyPair({ bits: 2048, e: 0x10001 });

**Comment by hbrls** [comment]
See my #365. Are you looking for this?

    var pkstr = '-----BEGIN PUBLIC KEY-----' + publicKey + '-----END PUBLIC KEY-----'; // not friendly
    var pk = forge.pki.publicKeyFromPem(pkstr);

**Comment by Sbopf** [comment]
Not friendly? I have a similar function and it throws
Cannot read public key. ASN.1 object does not contain an RSAPublicKey

**Comment by dlongley** [comment]
@Sbopf,

Can you provide a sample public key here that you're trying to load?

Can you provide sample code demonstrating how you're serializing the key in forge and then how you're loading the key in .NET? Also, what code are you running that indicates a key size of 2328 bytes? (Note: that would be 18624 bits).

**Comment by Sbopf** [comment]
Hey

Sorry I was a bit vague. I've actually found another thread in here with some helpful information on the XML (from .NET) can be loaded into a forge public key. Using #169 I've managed to get it to load at the correct key size, about to test encrypting and decrypting. My previous way of converting
the key from forge public -> xml was not quite accurate.

For .NET I'm simply using the following code provided by System.Security.Cryptography:

 public string GenerateSessionKeyPair(string key, string cypher)
        {
            using (var rsa = new RSACryptoServiceProvider(2048))
            {
                try
                {
                    //load key
                    rsa.FromXmlString(key);
                    // export key
                    rsa.ToXmlString(false);
                }
                finally
                {
                    rsa.PersistKeyInCsp = false;
                }
            }
        }

 I'll close this one now.

**Comment by UthayaGit** [comment]
Hi ,
I have similar issue , Can any one resolve my issue , I have own public key(Base64) from java generated(.cer)
Cannot read public key. ASN.1 object does not contain an RSAPublicKey
#Source Code
  const crypt = new Crypt();   
   let publicStr =  "-----BEGIN PUBLIC KEY----- "+publickKeyStr+" -----END PUBLIC KEY-----";
   let pk = forge.pki.publicKeyFromPem(publicStr);
   let encrypted = crypt.encrypt(pk, encryptDecryptStr);
    console.log("enMessage"+encrypted);

**Comment by rrigoni** [comment]
I'm facing the same issue. 

This is my public key: 
`MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj1F_rX_RREK_7QpEhn-kc3gVIHbp7N1PHfgi7DY34ryLGymqCeJ6Q3o9WPnWKBN-LAIiF8brvXBrGx4zcN-g5YFh6-36egjKngk5C3brK_oQJWhWAFqCm9SoZ7mPX6J7eiIn7RZQ41u-dJ955DYHbuSFsOF9h1mAtj64tuNTegUgKyZfSzt7XFTo2S85TJC3Jgm3x6OIUdTaSri1scZH8tV_p3aWazQb6il7ttayMKzMS1lLPZdECuJBCs2LWEVIHAJL_BTk6yyfi6P8HrpFCT2E7mOq_IceW3xpBMzeCIEaUTL3GtTalv-3GbydQglPmrsmh8y6eNyHm8xg_Tj7XwIDAQAB`

This is the error I'm getting `Cannot read X.509 certificate. ASN.1 object is not an X509v3 Certificate.`


This is the way I'm trying to initialize the publicKey
 ```
var der = forge.util.decode64("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj1F_rX_RREK_7QpEhn-kc3gVIHbp7N1PHfgi7DY34ryLGymqCeJ6Q3o9WPnWKBN-LAIiF8brvXBrGx4zcN-g5YFh6-36egjKngk5C3brK_oQJWhWAFqCm9SoZ7mPX6J7eiIn7RZQ41u-dJ955DYHbuSFsOF9h1mAtj64tuNTegUgKyZfSzt7XFTo2S85TJC3Jgm3x6OIUdTaSri1scZH8tV_p3aWazQb6il7ttayMKzMS1lLPZdECuJBCs2LWEVIHAJL_BTk6yyfi6P8HrpFCT2E7mOq_IceW3xpBMzeCIEaUTL3GtTalv-3GbydQglPmrsmh8y6eNyHm8xg_Tj7XwIDAQAB");
   var asn1 = forge.asn1.fromDer(der, false);
   var cert = forge.pki.certificateFromAsn1(asn1);
   var publicKey = cert.publicKey;
```


Any thoughts?

**Comment by engpakravan** [comment]
> Hi , I have similar issue , Can any one resolve my issue , I have own public key(Base64) from java generated(.cer) Cannot read public key. ASN.1 object does not contain an RSAPublicKey #Source Code const crypt = new Crypt(); let publicStr = "-----BEGIN PUBLIC KEY----- "+publickKeyStr+" -----END PUBLIC KEY-----"; let pk = forge.pki.publicKeyFromPem(publicStr); let encrypted = crypt.encrypt(pk, encryptDecryptStr); console.log("enMessage"+encrypted);

what is the **crypt** package ? is it Crypto package from node.js ? if true it's not contain encrypt function or decleration
