### ISSUE TITLE
Web Cryptography API

### ISSUE THREAD

**Issue by neochoon** [digitalbazaar/forge#367]
Hi, 

As far as I know, [Web Cryptography API](https://www.w3.org/TR/WebCryptoAPI/) standardization work is in the last miles.

I would like to ask that have you been considering to use this library for forge or just decided to ignore it.

I just want know your opinion of Web Cryptography API.

thank you.

**Comment by dlongley** [comment]
@neochoon,

We have a plan to provide forge as a polyfill for the Web Crypto API -- as well as use it internally where it applies. Web Crypto should be employed whenever possible to ensure native, constant-time code is used.

However, forge provides more functionality and than the Web Crypto API does, and it provides a "progressive" API that Web Crypto does not and it therefore cannot be used as a backing implementation in those cases. A "progressive" API means that you can, for example, stream data to the API and it will progressively output encrypted/hashed/whatever. The Web Crypto API requires all of the input to be in memory at once before it can perform a crypto operation and return the output. It's possible that a future revision of the Web Crypto API will address this.

**Comment by YuryStrozhevsky** [comment]
@neochoon,

Here is a full-features library working with WebCrypot natively: [PKIjs](https://github.com/GlobalSign/PKI.js). Here is a polyfill working with WebCrypto in Node.js environment: [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl). Here is a polyfill making WebCrypto interface for PKCS#11 devices: [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11).

Sorry Dave :)

**Comment by dlongley** [comment]
@neochoon, cool! Yeah, I've seen those libraries.

> Sorry Dave :)

It's ok? :)

**Comment by dlongley** [comment]
This is tracked in #145.
