### ISSUE TITLE
Unable to decrypt the ciphertext in backend!

### ISSUE THREAD

**Issue by maiopirata** [digitalbazaar/forge#373]
We are trying to experimenting crypto for our website.
My backend is using python and at the front I use reactjs with webpack boundling system!

I first had troubles in setting up the package but I solved it with the https://github.com/digitalbazaar/forge/issues/198 

then I'm trying to encrypt/decrypt with RSAES-OAEP/SHA-1/MGF1-SHA-1 algorithm.
1) Generating the keys in forge. No problems! Encryption/Decryption works!
2) Generating the keys in python and importing it in forge i do (ES6)
```
let publicKey = '\
-----BEGIN PUBLIC KEY-----\n\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlPY6dr4M0PdNnHnOaxim\n\
C/OTz5LOdFOcMM7XyxUDIgfHg5plCz4iaWeVHRx/Sxv6HGWfS8q3brfLofElJbjv\n\
X+wbFzRYMA7jmFd2NM9bYJ5SD/xGya3SqpOQxqBwtZTVSoARHMnaeDEKm9aL59XF\n\
lQ4WJOqI1RFsJRZkrgdA78VnzvQkSMJBUe5F3TLYn04il12V2Mbu/4VxkGwQ62pe\n\
4fDAhaGzndVmSx5NehtRRi/qBm9gisj5MYQbaYRwyY2509iORaEP/ecmuZoy0yZX\n\
80g2ZwrQ/7f/rMLfKNXpu6ucSDLHewYwoFGY0+NS3tiIPrYMgHlDFIwJUYLC/x1P\n\
bwIDAQAB\n\
-----END PUBLIC KEY-----'
```
I import it in forge
`forge.pki.publicKeyFromPem(publicKey);`
I then encrypt:
```
var encrypted = publicKey.encrypt(bytes, 'RSA-OAEP', {
        md: forge.md.sha1.create(),
        mgf1: {
          md: forge.md.sha1.create()
        }
      });
```
If I use the imported private key I can decrypt in forge. But when I share the ciphertext with my backend and I try to decrypt it, I don't obtain the original text:

I tried to convert the ciphertext in Base64 (considering that is in utf8) and sharing it in Base64 it is still not working.

To be completely clear in order to convert in Base64 I use this function of CryptoJS:
`CryptoJS.enc.Base64.stringify(CryptoJS.enc.Utf8.parse(encrypted))`

I don't see what I'm doing wrong... How can we test if it is a padding issue?
Any help would be appreciated.

**Comment by dlongley** [comment]
To convert to base64, do this:

```js
var encrypted = publicKey.encrypt(bytes, 'RSA-OAEP', {
        md: forge.md.sha1.create(),
        mgf1: {
          md: forge.md.sha1.create()
        }
      });
var base64Encoded = forge.util.encode64(encrypted);
```

Hopefully that will resolve the issue.

**Comment by maiopirata** [comment]
thank you. This works.. I skipped the direct function.

**Comment by dlongley** [comment]
Sure! :)
