### ISSUE TITLE
Problem creating new certificate signed with my own CA certificate

### ISSUE THREAD

**Issue by jrife** [digitalbazaar/forge#375]
I have created and signed a certificate similar to the example here:

[https://github.com/digitalbazaar/forge/issues/154]

I previously created a root certificate and key and an intermediate certificate and key for my CA. I used the intermediate key to sign my certificates and set the issuer to the subject.attributes from the intermediate certificate. My problem comes when I try to take the PEM encoded certificate that I get at the end of this process, presumably signed by the intermediate key, and try to verify it with the certificate chain. Running this command yields an error:

`openssl verify -CAfile ca/intermediate/certs/ca-chain.cert.pem ./serverCert.pem`
`error 20 at 0 depth lookup:unable to get local issuer certificate`

ca-chain.cert.pem is my concatenated certificate file and serverCert.pem is where I put the generated certificate. If I generate a certificate with openssl command line tools and try to verify this same way I get an OK message. However, when I try generating the certificates in node using forge there is this error. Not sure if I'm just doing something stupid. Any help would be appreciated :).

**Comment by dlongley** [comment]
@jrife,

Sorry you're having trouble. Can you provide a runnable code sample so we can better investigate?
