### ISSUE TITLE
Wrong encode64 and decode64

### ISSUE THREAD

**Issue by kitkatbaf** [digitalbazaar/forge#377]
Hi,

It's normal when i make a decode64 on a key and after a encode64 on result, i haven't the same result ?

var key = "²E£âñso½c%Qüß·:Éo²E";
var tmp = forge.util.decode64(key)   // tmp = "ÊB"
var res = forge.util.encode64(tmp) // res = "EsocQoE="
key !==res

**Comment by dlongley** [comment]
@kitkatbaf,

> It's normal when i make a decode64 on a key and after a encode64 on result, i haven't the same result ?

Yes, if you're decoding something that isn't base64 tp begin with (which is the case here). Did you mean to do the reverse (encode and then decode)?

**Comment by dlongley** [comment]
Feel free to reopen if unresolved.
