### ISSUE TITLE
SHA-256 Standalone

### ISSUE THREAD

**Issue by frederichoule** [digitalbazaar/forge#380]
I would need a standalone function to do SHA-256 hash. I came across Forge, and it's the fastest around.

How can I build a minified version that includes only what is required to generate SHA-256 hashes?

For browser use.

Thanks.

**Comment by dlongley** [comment]
We're currently working on making it easier to do custom builds -- but I'll ping @davidlehn to see if he's instructions for what to do today.

**Comment by dukedougal** [comment]
The ideal would be something standlalone that would allow a simple npm install.  It would be great to avoid having to spend time learning the custom build system.

**Comment by fxa** [comment]
hi there,

why don't you use the nodejs build in cypher?

> require('crypto').createHash('sha256').update('').digest().toString('hex')


On 15.08.2016 23:21, dukedougal wrote:
> The ideal would be something standlalone that would allow a simple npm install.  It would be great to avoid having to spend time learning the custom build system.
> 

Franz

**Comment by fxa** [comment]
be aware, that the crypto subtle in the browser works completely different.
As a sample see
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest

But the days of homebrewn js hashes is gone.

On 15.08.2016 23:21, dukedougal wrote:
> The ideal would be something standlalone that would allow a simple npm install.  It would be great to avoid having to spend time learning the custom build system.
> 


-- 
Franz Antesberger
Alexander Ferdinand Str 3
93051 Regensburg
info@franz-antesberger.de
0160 374 84 95

**Comment by dlongley** [comment]
Addressed by #456.
