### ISSUE TITLE
How do I save a RSA key pair in a usable form?

### ISSUE THREAD

**Issue by adammfrank** [digitalbazaar/forge#384]
I want to create a script to generate a key pair, then save those in a json file to use later.  The problem is that the string representation does not preserve the methods of the keys like encrypt and decrypt.  How do I build a full key object from the data available from JSON.stringify()?

**Comment by dlongley** [comment]
I recommend converting to standard PEM format and storing the key data that way -- which can be inside a JSON file.

```js
var foo = JSON.stringify({
  publicKeyPem: forge.pki.publicKeyToPem(publicKey),
  privateKeyPem: forge.pki.privateKeyToPem(privateKey)
});

// ...

foo = JSON.parse(foo);
var publicKey = forge.pki.publicKeyFromPem(foo.publicKeyPem);
var privateKey = forge.pki.privateKeyFromPem(foo.privateKeyPem);
```

**Comment by adammfrank** [comment]
publicKeyFromPem takes a string?

**Comment by dlongley** [comment]
@adammfrank,

> publicKeyFromPem takes a string?

Yes.

**Comment by adammfrank** [comment]
Thank you.
