### ISSUE TITLE
forge.util.setImmediate seems to break in IE 11 or Edge

### ISSUE THREAD

**Issue by JeremyRann** [digitalbazaar/forge#385]
I noticed that trying to call forge.random.getBytes asynchronously seems to fail in Internet Explorer 11 and Edge (though it works everywhere else). I get "Invalid calling object", which I traced down to a utility function at forge.utils.setImmediate. My best guess at the core problem here is that in IE, forge detects that window.setImmediate is available and attempts to use it, but it's calling the function with an unexpected context.

I made a pull request at https://github.com/JeremyRann/forge/commit/5412530123385ad7dd2f653ef44dd87133cac8d6 which has a primitive fix for the issue; I've only checked that it works on a few browsers, but off-hand I think it's a doable fix.

**Comment by siebertm** [comment]
I have this (mostly) same problem popping up again when using webpack and IE11:

webpack stubs `process` and `process.nextTick`, so the detection code ([util.js:17](https://github.com/digitalbazaar/forge/blob/master/lib/util.js#L17)) "thinks" this is nodejs, leading calling the infamous `invalid calling object` error again.

A quick fix would be to also add the wrapping there as @JeremyRann did for the "browser" code, but.... ugh... this feels so ugly to me...

shall we reopen this issue or create a new one?

**Comment by davidlehn** [comment]
@siebertm Whichever you'd like. Note that the forge webpack config disables the `process` and other polyfills when building a browser bundle itself.  When webpacking higher level projects that use forge it's cumbersome to apply such rules to just forge.  I'm not sure what the solution is.  Some of that code is ancient, so there may be more modern approaches that improve the situation.  Feel free to propose ideas or code updates.
