### ISSUE TITLE
Getting "Encryption block is invalid" instead of "false" for RSA signature verification

### ISSUE THREAD

**Issue by adammfrank** [digitalbazaar/forge#391]
It's pretty self explanatory.  I want to alert the receiver of a message if the message has been signed by a private key not matching the public key they have been given. 

As of now, if the keys do match, verify returns true. If they don't match (but the falsified private key is still a valid private key), it throws an error instead of returning false. Is this the desired behavior? Am I just supposed to catch the error?

**Comment by dlongley** [comment]
This is the behavior in the 0.6.x and future 0.7.x API; we may change it to return false when we make some more sweeping API changes in 0.8.x.
