### ISSUE TITLE
Forge to investigate companies that use root certificate?

### ISSUE THREAD

**Issue by kristofferorstadius** [digitalbazaar/forge#394]
Hi!

Some companies use root certificate to intercept https on employee computers. It's also pretty easy to do a man-in-the-middle with for example Charles Proxy.

I work as a journalist and want to investigate if some government agencies in my country intercept https.

I would like to create a script on a web page that checks if the client uses another certificate than the one that *should* be use.

Is forge suitable for this? How is it possible to do?

Many thanks!

// Kristoffer

**Comment by david-mas** [comment]
You need to check the dn of the https certificate matches the url of the site you are visiting, and do a full pkix path validation on the https certificate. If the root CA is a trusted one, then you should be safe, otherwise the https connection cannot be trusted.
However, modern web browsers already do this and warn you if the https channel is not secure.

**Comment by angelos** [comment]
Sorry, no. This would require the script on the web page to inspect the certificate that the server provided when loading that very same script; that's not something browsers allow you to do. So, Forge is out of the question.

Given your goal, I can think of a few ideas that could help you,
- Build a [Flash-based](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/SecureSocket.html) tool to inspect certificates, as this does allows you to inspect certificates.
- teach the user to inspect the certificate using his browser's tools, and provide a list of "expected" signers,
- or, if you're interested in a one-off investigation, get yourself a VPN, visit a bunch of website from different locations, and compare the results.

That said, I understand what you're trying to do: find out the extent of government interception of HTTPS. Do remember that what you're trying to do isn't all that trivial: there are a number of ways this behavior shows up, ranging from 
- bloatware on [Dell](http://arstechnica.com/security/2015/11/dell-does-superfish-ships-pcs-with-self-signed-root-certificates/) or [Lenovo](http://arstechnica.com/security/2015/02/lenovo-pcs-ship-with-man-in-the-middle-adware-that-breaks-https-connections/) PCs, which shipped with a self-signed root certificate, to
- corporate firewalls which install a certificate on your company-issued PC using some admin tool, to
- full blown [government-decreed root certificates](http://www.zdnet.com/article/kazakhstan-forces-its-citizens-into-installing-internet-backdoors/).

**Comment by kristofferorstadius** [comment]
Many thanks for your answers, @angelos and @david-mas !

One more question: To check if an organisation uses a root certificate on the computers to intercept https on employees - do I really need to inspect the certificate that the server provided when loading that very same script? Isn't it possible to archive this by creating a script on a webpage that "connects" to another https server with forge? And to inspect that certificate and look if it's the correct one..

I just want to check if any government agencies in my country intercept https.

// Kristoffer

**Comment by angelos** [comment]
As far as Javascript goes, the browser doesn't allow you access to the connection, so, no. Besides, this would go against [same origin policy](https://en.wikipedia.org/wiki/Same-origin_policy), so your browser would block the connection anyway.
You could get around it with Flash, or by having users check the connection manually.

And by the way, be aware that it's not as black-and-white as finding out whether interception happens. Agencies could choose to intercept only connections to given servers, or at a given time of day, or even depending on who is initiating the connection. If you do get any data from this experiment, be very careful about extrapolating this to a general case.

**Comment by angelos** [comment]
Come to think of it, there may be something worth trying.

You could create a webpage which uses Forge to connect to a bunch of well-known websites. You have previously downloaded the certificate from these sites, so you know the signature. You can then create a connection _from Javascript, using forge_ to that site, and verify the fingerprint.

Your page would look a little bit like,

    THE INTERCEPTATOR
    [Google.com]  verified
    [Facebook.com] intercepted, view certificate
    [github.com]  verifying...

You'll also need to host it somewhere, and find people willing to visit this page. You can choose to either make it automatically report results to your server, or have people just inspect it, and email you when something's wrong.

It must be said that this method is rather easy to detect, as per my previous comment.

Hope this helps.

**Comment by dlongley** [comment]
Closing as potentially resolved, please reopen if necessary.

**Comment by rogierslag** [comment]
It would still be awesome if this was possible
