### ISSUE TITLE
Please add support for UTF8 in x509 subject

### ISSUE THREAD

**Issue by Cojad** [digitalbazaar/forge#397]
https://github.com/digitalbazaar/forge/blob/master/js/x509.js#L1959

I found the code is default with encoding  with PRINTABLESTRING.
Which user have no option to modify the default encoding to utf8 or I missed?
node-forge would produce illegal cert when subject contains UTF8 characters.  
I have modify this line to UTF8 in order to produce my certs in correct encoding. I'm not familiar for node.js programing and it took me almost a day to find here to get my job done. But I hope there will be option for change default so one doesn't need to modify the code in node-forge.

**Comment by Cojad** [comment]
I apologized. There is indeed a way to set utf8 for subjects.
```
var attr = [
        {name: 'countryName', value: 'TW' valueTagClass: 12},
        {name: 'organizationName', value: 'ass.tw', valueTagClass: 12},
        {shortName: 'ST', value: 'Chinese 大安區', valueTagClass: 12},
        {shortName: 'CN', value: 'Chinese 中文', valueTagClass: 12},
        {shortName: 'OU', value: 'Chinese 中文部門', valueTagClass: 12},
        {shortName: 'CN', value: 'Chinese 中文', valueTagClass: 12}
];
 ```
The key is set "valueTagClass" with a value 12 which indicate UTF8. Then you can put UTF8 character in value and produce well formed certs.

**Comment by Cojad** [comment]
However this didn't fix all the problem. I soon realized that node-forge didn't decode x509 pem correctly with utf8 subject. So I fix it be add a few line in my fork. I'm afraid that my commit doesn't meet the contribute guild. So I din't create a poll from my commit. But feel free to take it.

https://github.com/Cojad/forge/commit/0f6d5d3c718666e871aaac1bae3f29374369f743

**Comment by M-OC** [comment]
+1

**Comment by genaromadrid** [comment]
Great @Cojad, your change also fixes UTF8 characters in the issuer... this was exactly what i has looking for

**Comment by Cojad** [comment]
I'm glad that someone find my patch useful. :)

**Comment by Djalmar** [comment]
Another solution I have found is to use the valueTagClass field on the subject, when the value is 12 you should decode to fix the problems.

**Comment by GitStorageOne** [comment]
Still actual, right?

**Comment by kamil7x** [comment]
@davidlehn @dlongley any chances that patch created by @Cojad will be picked up by you? Or is there any other solution? I still run into decoding problem and I would like not to fork library.

**Comment by davidlehn** [comment]
Does someone have the time to make a PR with that patch and add some tests and maybe a README example?

**Comment by kamil7x** [comment]
@davidlehn I added PR, could you take a look? It's important in my current project and I don't want to fork your repo

**Comment by Cojad** [comment]
3 years later. I think we can close the issue now. Thanks everyone!

**Comment by GitStorageOne** [comment]
In ASN.1 there is no `valueTagClass` with value 12.  
Seems, valueTagClass field is wrongly used in general.  
12 is value from `Type` enum and represent `UTF8`.  
``` javascript
// seems, should be something like that
{ name: 'organizationName', value: 'ass.tw', valueType: 12 }
```

**Comment by j4k0xb** [comment]
I think #731 is the wrong approach as it only affects x.509, #790 fixes the root cause

@GitStorageOne https://certificate.net/Portals/1/STANDARDS/ITU/x-680-x-693.pdf

![Image](https://github.com/user-attachments/assets/4e504e10-0475-4758-9d84-ac892bac7059)
