### ISSUE TITLE
http module disabled?

### ISSUE THREAD

**Issue by ekobi** [digitalbazaar/forge#402]
Hi,

'http' appears to be absent from the list of exported forge submodules:

    var request = forge.http.createRequest({method: 'GET', path: '/'});
                            ^
    TypeError: Cannot read property 'createRequest' of undefined
        at Object.<anonymous> (/Users/kobi/hacking/forge-http-client/forge-http-client.js:35:25)

Any suggestions? Thanks!

--
kobi

**Comment by dlongley** [comment]
@ekobi,

> 'http' appears to be absent from the list of exported forge submodules

Yeah, it's not included by default because it's primary purpose was for integrating with flash sockets -- and flash is being phased out everywhere. It can still be included on its own or added to the minify script prior to bundling if you want to include it.

**Comment by ekobi** [comment]
Thanks for the quick response, Dave.

I added AMD support wrapper to http.js, and then added 'http' to the list of defined modules in forge.js, and that seems to work now.

Would you consider re-enabling this module by default? I'm integrating with emailjs-tcp-socket, and it would be great not to have to carry around a patch. Cheers,
--
kobi
