### ISSUE TITLE
Some encrypted private keys don't decrypt.

### ISSUE THREAD

**Issue by ctel** [digitalbazaar/forge#405]
There are some encrypted private keys (the one attached below within the js file was generated by *botan 1.11.29*), which cannot be decrypted by forge (*OpenSSL 0.9.8zf 19 Mar 2015* (on OSX) cannot decrypt this key either, but *OpenSSL 1.0.1f 6 Jan 2014* (on Ubuntu 14.04.4)  can).
Put the attached js file in the root of forge and execute it to reproduce the error (null should be printed, which is unexpected)
The text file of the attachment was generated with *openssl asn1parse -in cert.key > dump.txt*.
It shows some hmacWithSHA256 involvement (line 12 of *dump.txt*).
I tried to find differences between the decryption behaviour of forge between other encrypted certificates and made the following discoveries while executing the attached js file:

- [js/pbe.js:345](https://github.com/digitalbazaar/forge/blob/ac803a35de4b903f8b4e9f95a6f1425dcfbf4c08/js/pbe.js#L345): cipher.finish() returns false, so the following line doesn't get executed => rval is null

- [js/cipherModes.js:172](https://github.com/digitalbazaar/forge/blob/ac803a35de4b903f8b4e9f95a6f1425dcfbf4c08/js/cipherModes.js#L172): The condition is *true*, which causes the unpad function to *return false*. *count* is set to *207* in this instance; this value is always within the same magnitude for all certificates with the described problem

I hope this helps to narrow down the problem.

[Attachment.zip](https://github.com/digitalbazaar/forge/files/306839/Attachment.zip)

**Comment by dlongley** [comment]
Sorry for not getting back on this for a long while, quite busy.

Is it possible that the password is just incorrect for this example? `null` is the result you get if you use the wrong password. If the padding byte count is invalid, that is an indicator of a bad password.

Can you write a sample that produces a key and encrypts it with a password (given in the sample code itself) and then it fails to decrypt? It looks like this key was encrypted using AES-CBC 256 but other keys using this algorithm decrypt just fine with forge and forge passes all test vectors for that algorithm.

**Comment by ctel** [comment]
Hey thanks for your reply :)

No, it does not seem to be a password problem: OpenSSL 1.0.1f 6 Jan 2014 (on Ubuntu 14.04.4) was able to decrypt this key. I ensured, that there are other instances failing decryption. It is possible that the problem originates from botan generating the key and not in forge during decryption, though.
But OpenSSL is able to decrypt the key, so I guessed it's a problem of the forge library.

I will provide a sample application for botan generating the keys. If you don't want to compile it, tell me your system configuration, so I can provide a binary along with the javascript file. As far as I know, there is no failing example with keys encrypted by forge, so there can't be a js-only test program.

I don't know the internal format of the private key files. Is there any integrity test after the key itself? When I saw the _hmacWithSHA256_, my first idea was that maybe there is an additional mac... Can I savely assume that additional data can corrupt the padding?

**Comment by dlongley** [comment]
@ctel,

You were right about `hmacWithSHA256`. The problem was a lack of support for SHA-256 PRF for PBE -- we just needed to add some support to accept that parameter. This is fixed now in forge v0.6.43. I tested it with your key and it worked properly.

**Comment by dlongley** [comment]
I'm going to close this out, feel free to reopen if the problem persists for any reason.
