### ISSUE TITLE
RSA/ECB/PKCS1Padding

### ISSUE THREAD

**Issue by tifa-show** [digitalbazaar/forge#407]
Hi

I am new to forge and I am coming from JAVA. Can you please show me how to encrypt using RSA with ECB mode and PKCS1 Padding.

please help  am stuck now

thanks

**Comment by dlongley** [comment]
You can find examples on how to do RSA-based encryption here:

https://github.com/digitalbazaar/forge#rsa

Specifically, you can do RSA public key encryption with PKCS1 padding like this:

```js
// load public key from PEM-formatted string
var pem = '-----BEGIN PUBLIC KEY...';
var publicKey = forge.pki.publicKeyFromPem(pem);

// convert string to UTF-8 encoded bytes
var buffer = forge.util.createBuffer('Something to encrypt', 'utf8');
var bytes = buffer.getBytes();

// encrypt data with a public key using RSAES PKCS#1 v1.5
var encrypted = publicKey.encrypt(bytes, 'RSAES-PKCS1-V1_5');

// base64-encode encrypted data to send to server
var b64Encoded = forge.util.encode64(encrypted);
```

**Comment by Bibo1978** [comment]
you encrypt data with random key in ECB then you encrypt the key with rsa using pkcs1.5 .. RSA doesn't encrypt ECB symmetric keys do that 

Kind Regards,
Ibrahim Magdy

**Comment by dlongley** [comment]
Closing out as resolved, feel free to reopen if necessary.

**Comment by JianhuisHuang** [comment]
> You can find examples on how to do RSA-based encryption here:
> 
> https://github.com/digitalbazaar/forge#rsa
> 
> Specifically, you can do RSA public key encryption with PKCS1 padding like this:
> 
> ```js
> // load public key from PEM-formatted string
> var pem = '-----BEGIN PUBLIC KEY...';
> var publicKey = forge.pki.publicKeyFromPem(pem);
> 
> // convert string to UTF-8 encoded bytes
> var buffer = forge.util.createBuffer('Something to encrypt', 'utf8');
> var bytes = buffer.getBytes();
> 
> // encrypt data with a public key using RSAES PKCS#1 v1.5
> var encrypted = publicKey.encrypt(bytes, 'RSAES-PKCS1-V1_5');
> 
> // base64-encode encrypted data to send to server
> var b64Encoded = forge.util.encode64(encrypted);
> ```

it's work for me, thanks.
