### ISSUE TITLE
npm bundle or minify error

### ISSUE THREAD

**Issue by ikoichi** [digitalbazaar/forge#410]
Hi,
while trying to execute

`npm run bundle`

I get the following errors:

   > node-forge@0.6.41-dev bundle       C:\EnterpriseCollection\MDR.Scrum\DEV\DEV_INT_LABS\LABS.Web\offline\forge
> r.js -o minify.js optimize=none out=js/forge.bundle.js
   npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\restaglu.DDNET1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "bundle"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! node-forge@0.6.41-dev bundle: `r.js -o minify.js optimize=none out=js/forge.bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-forge@0.6.41-dev bundle script 'r.js -o minify.js optimize=none out=js/forge.bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-forge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     r.js -o minify.js optimize=none out=js/forge.bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-forge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-forge
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\EnterpriseCollection\MDR.Scrum\DEV\DEV_INT_LABS\LABS.Web\offline\forge\npm-debug.log

![image](https://cloud.githubusercontent.com/assets/588011/16619244/a316a4a2-438d-11e6-9292-83b5d76acac9.png)

OS is Windows 7
Could you please help on this or provide a `dist `folder including bundle js file?
Thanks

**Comment by dlongley** [comment]
See comment: https://github.com/digitalbazaar/forge/issues/167#issuecomment-53285416

Does that work for you?

Once we have a better build system in place we'll start auto-generating bundle files with releases.

**Comment by ikoichi** [comment]
It worked, thanks!
