### ISSUE TITLE
Javascript RSA encryption vs Openssl 

### ISSUE THREAD

**Issue by jofrep** [digitalbazaar/forge#414]
If I encrypt a string and then I repeat the same process using Openssl I get different results and I don't know why.

In JS I have the function below:

```
function encriptacioAsimetrica(clauPem,data)
{
    var publicKey = forge.pki.publicKeyFromPem(clauPem)
    var encrypted = publicKey.encrypt(data, 'RSA-OAEP');
    return forge.util.encode64(encrypted);              
}; 
```
where data is b9744720310fff5319f55dd272972c5019657b5708805eb3f14ef75daea8be1c and clauPEm the public key in PEM format

In openssl I use
```
$echo b9744720310fff5319f55dd272972c5019657b5708805eb3f14ef75daea8be1c| openssl rsautl -encrypt -oaep -pubin -inkey public4096.pem -out out.der
Loading 'screen' into random state - done

$openssl enc -e -a -in out.der
```

Unfortunately in both cases I get different results and I´d like to know why

**Comment by dlongley** [comment]
RSA_OAEP uses random padding bytes, so the encrypted output will be different every time. If you run the openssl commands twice you'll see different output as well.

**Comment by jofrep** [comment]
of course! apologies

**Comment by dlongley** [comment]
No problem! :)
