### ISSUE TITLE
HMAC result different from Python result

### ISSUE THREAD

**Issue by georg90** [digitalbazaar/forge#415]
I want to use forge to encode a signature used to access an API.

My python code looks like this (and is working!)
```
class HVVAuth(AuthBase):

    def __init__(self, payloadFunc):
        # setup any auth-related data here
        print(json.dumps(payloadFunc))
        self.sig = base64.b64encode(hmac.new(password, json.dumps(payloadFunc), hashlib.sha1).digest())
        print(hmac.new(password.encode("UTF-8"), json.dumps(payloadFunc).encode('UTF-8'), hashlib.sha1).digest());
        print(self.sig);

    def __call__(self, r):
        # modify and return the request
        r.headers['geofox-auth-signature'] = self.sig
        r.headers['geofox-auth-user'] = username
        return r
```

My nodejs implementation looks like this:

```
function getSignature(text)
{
var key = 'test';
var algorithm = 'sha1';
var hmac = forge.hmac.create();

hmac.start(algorithm, key);
hmac.update(text);
var hash = hmac.digest().toHex();
var buf = new Buffer(hash, 'hex').toString('base64');
return buf;
}
var sig = getSignature(JSON.stringify(data)); // data is an object
```

I get two different results using these implementation. The python version is working correctly and the API accepts my login. With the same input, I get a different result in the nodejs implementation.

I read a lot about this issue, regarding python using the binary input and nodejs using utf8. But I cannot get it to work. Is there any limitation known in forge which could cause this issue?

**Comment by dlongley** [comment]
Sorry you're having trouble. :)

There's no limitation, you just have to make sure you get all the calls and encodings right which can be trickier than it should be.

Here's a working, simplified example:

```py
import hmac
import hashlib
import base64

sig = base64.b64encode(
    hmac.new('test', '{}', hashlib.sha1).digest())
print sig
```

Yields: `eHbJONOOmblUs9g5x7r7ND0p53Y=`

```js
var forge = require('node-forge');

var hmac = forge.hmac.create();
hmac.start('sha1', 'test');
hmac.update(JSON.stringify({}));
var hash = hmac.digest().toHex();
var sig = new Buffer(hash, 'hex').toString('base64');
console.log('sig', sig);
```

Yields: `eHbJONOOmblUs9g5x7r7ND0p53Y=`

You can also use forge to the base64 encoding instead like this:

```js
var forge = require('node-forge');

var hmac = forge.hmac.create();
hmac.start('sha1', 'test');
hmac.update(JSON.stringify({}));
var sig = forge.util.encode64(hmac.digest().getBytes());
console.log('sig', sig);
```

Anyway, this simple example yields the same result, so there must be something else going on with your code. Hopefully this example will help you figure out what's going on.

**Comment by georg90** [comment]
Hi @dlongley thanks for this answer!  It fixed my problems and the authentication is working.  :) 

You saved me hours of looking around for a solution and eventually dumping forge because 'it's not working' -  thank you!
