### ISSUE TITLE
Get PKCS#12 X.509 public certificate

### ISSUE THREAD

**Issue by mareksip** [digitalbazaar/forge#423]
Hello, thanks for a great library!

I am working with [Web Services Security](http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0.pdf) in SOAP requests, and I am in need of getting 'X.509 security token data' for a '<wsse:BinarySecurityToken>' parameter whose equivalent in C# is [X509Certificate2.GetRawCertData()](https://msdn.microsoft.com/en-us/library/hh400392.aspx).

The BinarySecurityToken should according to [IBM documentation](http://www.ibm.com/support/knowledgecenter/SSAW57_8.5.5/com.ibm.websphere.nd.doc/ae/cwbs_binarysectokenx509.html) contain the **Base64 representation of X.509 public certificate**. "For an X.509 certificate, the public information is the public key/DN".

My certificate:

    var pkcs12Der = loadedCert; //loaded file content in UTF-8
    var pkcs12Asn1 = forge.asn1.fromDer(pkcs12Der);
    var pkcs12 = forge.pkcs12.pkcs12FromAsn1(pkcs12Asn1, false, "password");
    // load keypair and cert chain from safe content(s) 
    for (var sci = 0; sci < pkcs12.safeContents.length; ++sci) {
      var safeContents = pkcs12.safeContents[sci];

      for (var sbi = 0; sbi < safeContents.safeBags.length; ++sbi) {
        var safeBag = safeContents.safeBags[sbi];
        if (safeBag.cert != undefined) {
          //store certificate information
          var publicKey = safeBag.cert.publicKey;
          //is this what I need?
          cert = console.log(forge.pki.publicKeyToRSAPublicKeyPem(publicKey));
        }

        // this bag has a private key
        if (safeBag.type === forge.pki.oids.keyBag) {
          //Found plain private key
          privateKey = safeBag.key;
        } else if (safeBag.type === forge.pki.oids.pkcs8ShroudedKeyBag) {
          // found encrypted private key
          privateKey = safeBag.key;
        } else if (safeBag.type === forge.pki.oids.certBag) {
          // this bag has a certificate...        
        }
      }
    }

Would anyone know how to export x.509 public certificate from above pkcs12, please ?

**Comment by dlongley** [comment]
Sounds like you want:

```js
// PEM-formatted certificate (base64-encoded with header)
// ... this is the most common encoding for a certificate
var pem = forge.pki.certificateToPem(safeBag.cert);
```

Or, if you need the base64-encoded certificate without the PEM header:

```js
// DER-encode certificate and then base64-encode that
var der = forge.asn1.toDer(forge.pki.certificateToAsn1(safeBag.cert));
var b64 = forge.util.encode64(der.getBytes());
```

**Comment by dlongley** [comment]
Closing out as likely resolved, feel free to reopen if not.
