### ISSUE TITLE
Aes encryption is very slow for Big messages

### ISSUE THREAD

**Issue by mj-mehdizadeh** [digitalbazaar/forge#424]
Hi I use this AES library . it is realy very good but for encrypts files and big messages  this encryption process takes too long time 
Actually  `forge.util.createBuffer(myinput, 'binary')` takes too long time
My encryption code:
```
function aesEncrypt(input)
{
    var iv = forge.random.getBytes(symetricIvSize);
    var cipher = forge.cipher.createCipher(symetricMethod, symetricKey);
    cipher.start({
        iv: iv,
        tagLength:symetricMethodtagLength
    });
   cipher.update(forge.util.createBuffer(input, 'binary'));
    cipher.finish();

    return cipher.output.data;
}
```
how to encrypt messages (using this code `cipher.update()`) Without using `forge.util.createBuffer(input, 'binary')` ?

**Comment by dlongley** [comment]
@mj-mehdizadeh,

The cipher API allows you to feed chunks of data to it a little at a time. Are you able to perform your encryption that way? That should allow you to, for example, implement a progress bar or other status indicator while the encryption is being performed.

**Comment by dlongley** [comment]
I'm going to close this out as resolved, feel free to reopen if necessary.
