### ISSUE TITLE
random.getBytes not generating the right number of bytes in firefox 48.0.1

### ISSUE THREAD

**Issue by shashankcs090** [digitalbazaar/forge#426]
Running the following command in chrome returns value 12
forge.random.getBytes(12).length

but 

in firefox version 48.0.1
forge.random.getBytes(12).length returns value 16.
using node-forge version node-forge@0.6.21-dev

**Comment by dlongley** [comment]
Ran 100,000 times in firefox version 48.0.2 and it was always 12. Can you upgrade to 48.0.2? Can you upgrade to the latest version of forge as well?

**Comment by shashankcs090** [comment]
Thanks @dlongley
Upgraded the webpack version to 1.13.1, this resolved the issue.
