### ISSUE TITLE
Parsing ECDSA CSRs

### ISSUE THREAD

**Issue by flashsphere** [digitalbazaar/forge#427]
Passing a ECDSA CSR to forge seems to cause forge to run in an endless loop. It does not complete. I know that forge does not yet support ECC but I was hoping it would throw an error or the like. Is there a way around this?

**Comment by dlongley** [comment]
@flashsphere,

Can you share a minimal, runnable code example (and include a sample CSR) so we can look into it? Thanks!

**Comment by flashsphere** [comment]
Looks like the problem is on my side. When I was creating some sample code, forge does throw an error when it parses the CSR. 

I'll close this. Thanks!
