### ISSUE TITLE
PKCS#5 pbkdf2 is broken on IOS 10 and MacOSX Sierra devices

### ISSUE THREAD

**Issue by kavai77** [digitalbazaar/forge#429]
`forge.pkcs5.pbkdf2` gives inconsistent values for different calls on Apple only.
Please open my tester page on an IOS 10 or MacOSX Sierra device which executes pbkdf2 30 times, and there are always some different values there:
https://passwordmanager-1166.appspot.com/pbkdf2-test.html

**Comment by dlongley** [comment]
Possibly related to #428.

**Comment by BSierakowski** [comment]
I think I'm having a similar issue with inconsistency happening specifically in iOS10 and the latest version of Safari on OSX, I'm still narrowing it down to make sure I'm looking at the same thing, but it appears the method that fails sometimes is `forge.pki.decryptRsaPrivateKey()`. 

Would it help to log actual vs expected in a test environment?

**Comment by alexlamsl** [comment]
Most likely #428, as Mocha would almost always fail for the pbkdf2 tests.

**Comment by alexlamsl** [comment]
@kavai77 as mentioned in #428, your test page should give correct results if you open "Error Console" in Safari before visiting the page.

**Comment by kavai77** [comment]
@alexlamsl Thanks, I read the issue #428 and it is exactly what you experienced in unit tests. I am going to close this one, as well.
