### ISSUE TITLE
Password-based RSA generation

### ISSUE THREAD

**Issue by Loceka** [digitalbazaar/forge#432]
Hello,

First of all I'm sorry for this is not an issue but a feasibility request.
Is there a way to generate an RSA key pair based on a password with forge, and how ?

I guess it would imply initializing the RNG with a seed and pass it to RSA, and I've seen there is an "options.prng" entry but I can't figure out what to set there.

Thank you,
Loceka.

**Comment by dlongley** [comment]
There are a lot of security considerations when generating deterministic asymmetric keys, so make sure you look into that. To give you a simple answer to your question, look at this test, which always generates the same RSA key pair:

https://github.com/digitalbazaar/forge/blob/b7510af9f29b1f3faa333dac32b115ba3a213b9c/nodejs/test/rsa.js#L62-L93

Note that the PRNG seed and the algorithm for finding random numbers needs to remain stable for this to work. You should modify the code above slightly to explicitly include the default prime number generation algorithm as well:

```
forge.rsa.generateKeyPair(512, {prng: prng, algorithm: 'PRIMEINC'});
```

You can still call that function asynchronously by passing a callback.

**Comment by Loceka** [comment]
Thank you a lot for the hint.

> Note that the PRNG seed and the algorithm for finding random numbers needs to remain stable

How to ensure that they remain stable ?
My cryptographic skills are pretty low, sorry. Does it refer to the entropy ?

If that's so, I suppose generating the seed like that would be good enough :
```javascript
prng.seedFileSync = function(needed) {
	return forge.pkcs5.pbkdf2(<password>, <salt>, <numIterations>, needed);
};
```

**Comment by dlongley** [comment]
> Thank you a lot for the hint.

Sure.

>
> > Note that the PRNG seed and the algorithm for finding random numbers needs to remain stable
> 
> How to ensure that they remain stable ?

By specifying the algorithm identifier. That's all I meant by that. Right now we only have one algorithm for generating primes and it is deterministic. However, if we add more algorithms in the future we may change the default algorithm. Therefore, you want to make sure you keep using the `PRIMEINC` one by explicitly specifying it.

I believe the code example you provided with `pbkdf2` will probably be sufficient, but you should test it.

**Comment by Loceka** [comment]
It works well, thanks a lot !
