### ISSUE TITLE
Invalid PEM formatted message.

### ISSUE THREAD

**Issue by sroczynski** [digitalbazaar/forge#433]
Hi!
I tryng to verify a signature that was signed by bouncycastle in a C# application.
To make the signature i have used this method:
```C#
       public string SignData(string msg, RsaKeyParameters privKey)
        {
            try
            {
                SHA1 sha = new SHA1CryptoServiceProvider();
                ISigner sig = SignerUtilities.GetSigner("RSA");
                sig.Init(true, privKey);
                var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(msg));
                sig.BlockUpdate(bytes, 0, bytes.Length);
                byte[] signature = sig.GenerateSignature();

                StringBuilder sb = new StringBuilder();
                foreach (byte b in signature)
                    sb.Append(b.ToString("x2"));

                string hexString = sb.ToString();

                return hexString;

            }
            catch (Exception exc)
            {
                Console.WriteLine("Signing Failed: " + exc.ToString());
                return null;
            }
        }
```

And to verify the signature, in the forge, i use this:

```javascript
   var pem = jetpack.read(path.join(__dirname, "public_key.pem"));
    var pki = forge.pki;
    var publicKey = pki.publicKeyFromPem(pem);
    var md = forge.md.sha1.create();
    md.update(msg, 'utf8');
    var signature = forge.util.hexToBytes(signature);
    var verified = publicKey.verify(md.digest().bytes(), signature);
```
but the verify method in forge throw 'Invalid PEM formatted message.'.
Anybody can help me?
This can be a issue?

**Comment by dlongley** [comment]
That error looks like it would be thrown by `pki.publicKeyFromPem(pem);`, not from the verify call. What does the public key PEM look like? Are you able to paste it into the issue?

**Comment by sroczynski** [comment]
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi0/ajmKQ6P3+lInTZvRp
l8NBxUikVzz1ZaqJVlW6cy6rXkms2TYwawHJp6Uat4VoMj7+jCFxs7daOcQOLWA2
6KMKP+C8uSzdy6tgKN/CwkalDPU/+kC/ImEHwa7i3FFnXsBeJN5Md7my0MOhqYR6
vpiGtFu99YvRzBkOsj53ZT7Fya/EgEFrAmudfnNg7BmALO0lgXUKwGBZbg5h4pSk
ss06SQdNwvrpC0dRBBnww0nOXQmnEljNIfcJ1kCXyYO3GKVNkyzW+gQCpkB+xPxM
4+m4WWo93xKbI9SOXaIxhDu19Y5V7cbm2BunVaIvTNAtQuoamUN3arfg3d9mO8/y
BQIDAQAB
-----END PUBLIC KEY-----

**Comment by sroczynski** [comment]
but working with forge to forge this work

**Comment by dlongley** [comment]
@sroczynski,

Yes, that public key works fine for me too. Can you print out the value of `pem` once you read it in with `jetpack.read`? Alternatively, can you do `fs.readFileSync(path.join(__dirname, "public_key.pem"), 'utf8')` instead?

**Comment by sroczynski** [comment]
I try use  fs.readFileSync(path.join(__dirname, "public_key.pem"), 'utf8') 
and now throw this: 
Too few bytes to read ASN.1 value.

**Comment by sroczynski** [comment]
Problem solved
```C#
public string SignData(string msg, RsaKeyParameters privKey)
        {
            try
            {
                //SHA1 sha = new SHA1CryptoServiceProvider();
                ISigner sig = SignerUtilities.GetSigner("SHA1withRSA");//SignerUtilities.GetSigner("RSA");

                sig.Init(true, privKey);
                var bytes = Encoding.UTF8.GetBytes(msg);//sha.ComputeHash(Encoding.UTF8.GetBytes(msg));
                sig.BlockUpdate(bytes, 0, bytes.Length);
                byte[] signature = sig.GenerateSignature();

                StringBuilder sb = new StringBuilder();
                foreach (byte b in signature)
                    sb.Append(b.ToString("x2"));

                string hexString = sb.ToString();

                return hexString;

            }
            catch (Exception exc)
            {
                Console.WriteLine("Signing Failed: " + exc.ToString());
                return null;
            }
        }
```
Thanks for the help! =D
