### ISSUE TITLE
node-forge install error

### ISSUE THREAD

**Issue by lbcsultan** [digitalbazaar/forge#442]
Hi. 

I have used node-forge successfully for more than 1 years.
When I try to install node-forge in another computer (Windows 7, 32-bit), I got the following error message. How can I install node-forge? 
-----

C:\node\forge\forge-master>npm install node-forge
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\608\\AppData\\Ro
aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-forge"
npm ERR! node v6.3.0
npm ERR! npm  v3.9.0
npm ERR! code ENOSELF
npm ERR! Refusing to install node-forge as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     
npm ERR! Please include the following file with any support request:
npm ERR!     C:\node\forge\forge-master\npm-debug.log
C:\node\forge\forge-master>

**Comment by mattcollier** [comment]
@lbcsultan it appears you have cloned the github repository into your `forge-master` folder.  If that's the case, you would want to run `npm install`.  You would use `npm install node-forge` when you would like to add forge to another project.

**Comment by lbcsultan** [comment]
Thanks for quick reply. 
I have tried both ways. 
1. I cloned node-forge, and run "npm install" with the default package.json. In this case, other packages were installed, but node-forge was not installed that I could not use require('node-forge').
2. In other project I tried "npm install node-forge", and I got the above error messages.
