### ISSUE TITLE
forge.min.js file is not generated after running r.js -o minify.js

### ISSUE THREAD

**Issue by saru17** [digitalbazaar/forge#443]
Hi,
My OS is windows.
I have updated the package.json  name node to  :   "name": "node_forge",
The code base for the https://github.com/digitalbazaar/forge.
While running r.js -o  minify.js i got script errors ( extra commos)
After correcting r.js  i ran the command "r.js -o minify.js" but forge.min.js is not generated

Can i know what might be the error.
Without including this "forge.min.js" i am getting error in creating certificate and generatekeypair

forge.pki.rsa.generateKeypair(512) - getting error as generateKeypair is undefined
Please help on this

Thanks,,
Saru

**Comment by saru17** [comment]
If possible can you please send forge.min.js file......... i am not able to generate this file

**Comment by GINCHER** [comment]
I had to make some changes to get the min file. Anyway, here it is: 
[forge.min.zip](https://github.com/digitalbazaar/forge/files/614356/forge.min.zip)

**Comment by saru17** [comment]
Thank you so much Vlad.

Regards,
Saru

**Comment by dlongley** [comment]
Hopefully will be addressed in a new release now that #456 has been merged.

**Comment by davidlehn** [comment]
0.7.0 was released with a new build system that should fix this.  Reopen if it's still an issue.
