### ISSUE TITLE
how to convert base64 encoded string to x509 certificate

### ISSUE THREAD

**Issue by saru17** [digitalbazaar/forge#449]
Hi,

How can i convert base64 encoded String to x509 certificate using forge ?
Using forge.util.decode64

Server code:
X509V3CertificateGenerator certGen = new X509V3CertificateGenerator();
/// some code
X509Certificate issuedCert = certGen.generate(privateKey, ALGORITHM_PROVIDER);
return (issuedCert.getEncoded())

Client side code: javascript=

//received the x509certificate encoded value successfuly
 var decode = forge.util.decode64(base64encodedString); -- this is working, able to decode
now how can i convert the decode into a X509 certificate ??

Thanks,
Sukanya

**Comment by ukoloff** [comment]
I would try
```js
pki.certificateFromAsn1(asn1.fromDer(derBuffer))
```
