### ISSUE TITLE
How can i debug Could not decrypt record or bad MAC error

### ISSUE THREAD

**Issue by magne4000** [digitalbazaar/forge#453]
I would like to be able to debug why I sometimes have this messages, but I don't know if there is a way to activate some debug mode that would fill-up the console.

**Comment by davidlehn** [comment]
Please provide test code that shows the problem.  Thanks.

**Comment by magne4000** [comment]
The point of my question was how can I do this by myself.
The issue happens for some users of [quassel-webserver](https://github.com/magne4000/quassel-webserver/issues/160), and I'm mostly unable to reproduce the same issue.
I'm rather searching for guidance on how I can debug what's happening inside `forge`.

**Comment by davidlehn** [comment]
That message comes from tls.js.  You might just have to add in debugging near the error spot to help find out the issue.  @dlongley might know what best to add.  Looks like that error case could at least be modified to expose which of those errors it was.  For instance adding more info to the message like the data that was failing.

**Comment by magne4000** [comment]
Ok thanks, that's what I was starting to do.

**Comment by mass85** [comment]
I have reproduced the same problem and provided an example project. Check: https://github.com/digitalbazaar/forge/issues/786
