### ISSUE TITLE
Can i create detached CMS signature using forge?

### ISSUE THREAD

**Issue by andreyjkee** [digitalbazaar/forge#455]
Hi everyone!
Can i create detached CMS signature using forge?

**Comment by diegonc** [comment]
As far as I know, you need to do some patching like in this library: [pdfsign.js](https://github.com/Communication-Systems-Group/pdfsign.js) Also #279 is related.

I'm not sure whether CMS is the same as PKCS#7; but maybe you could do something similar in your case.
