### ISSUE TITLE
Allow selective use of md algorithms.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/forge#468]
As mentioned in https://github.com/digitalbazaar/forge/issues/467, it should be possible to combine files without requiring all of the algorithms from md.js.

0.6.x was a bit more relaxed in what files got used but code conversion for 0.7.x made it more aggressive to just use all algorithms via the generic md.js.

One solution is to have md.js only setup the simple data structures and then individual algorithm files (ie, sha256.js) can be required by higher level code as needed.  As a default, index.js (or some meta md file) could require all known algorithms.

**Comment by davidlehn** [comment]
@alexlamsl: I think this addresses your concern from #467.  You should be able to just bundle pbkdf2.js and sha256.js and the dependencies will pull in the other files.  An example was added to the webpack file to do this.  Please reopen if this doesn't fit your use case. Thanks.

**Comment by alexlamsl** [comment]
@davidlehn looks great, thanks!
