### ISSUE TITLE
PKCS#7 Signing

### ISSUE THREAD

**Issue by heuels** [digitalbazaar/forge#477]
Hello,

I've been looking for ways of signing `.mobileconfig` files using node and found [an old thread](https://github.com/digitalbazaar/forge/issues/57#issuecomment-22439102). Has the situation changed since then? Is pkcs#7 signing now supported in **forge**?

**Comment by dlongley** [comment]
There is some minimal PKCS#7 signing support in forge now. See this section of the README for an example at the end:

https://github.com/digitalbazaar/forge#pkcs7

**Comment by heuels** [comment]
Wow, I wonder how did I miss that. Thank you so much!
