### ISSUE TITLE
0.7.0 release notes

### ISSUE THREAD

**Issue by kspearrin** [digitalbazaar/forge#483]
Congrats on releasing 0.7.0! Are there any release notes available or notable highlights we should be aware of if upgrading?

**Comment by davidlehn** [comment]
You are in luck: 0.7.x now has a CHANGELOG file and it even has 0.6.x to 0.7.x migration notes!  Let us know if we missed anything.  It shouldn't be too bad for many use cases since this release was more focused on packaging and other issues vs API changes.

**Comment by kspearrin** [comment]
I see you moved the npm package to https://github.com/digitalbazaar/forge-dist

Is there a package still available for the main repo? I'd like to still have that available since my build process (gulp) relies on building from source with webpack rather than pre-bundled full library.

**Comment by davidlehn** [comment]
The npm package still exists as before and includes both the source files in lib/ and built files in dist/.  It should work for node, people wanting to use webpack and similar, and systems that just want the built files.  Webpack users can point at the files they need in lib/.  Forge uses webpack to build the forge-dist bundles so they do build. ;-)  The forge-dist split is mainly to support bower and avoid putting built files into the main repo.

**Comment by kspearrin** [comment]
Ok, thanks. A little new to webpack so I'm figuring this out as I go.

**Comment by kspearrin** [comment]
This is great! I was able to get our build down from the full lib 900kb to just 190kb (unminified).

Here's our gulp build using webpack: https://github.com/bitwarden/browser/commit/d684227883cbbcf141078d14337ac02416452370

Does this look about as minimal as we can go for our [crypto implementation](https://github.com/bitwarden/browser/blob/master/src/services/cryptoService.js)?
