### ISSUE TITLE
RSA/ECB/NoPadding

### ISSUE THREAD

**Issue by VictorQueiroz** [digitalbazaar/forge#484]
Hi. sorry if this is a duplicate. But I'm new to forge and I would like to know if "RSA/ECB/NoPadding" is supported by `forge`? And if yes, how to use it?

**Comment by dlongley** [comment]
This may help a bit: https://github.com/digitalbazaar/forge/issues/379#issuecomment-208395176

**Comment by VictorQueiroz** [comment]
Very helpful and simple. Thank you
