### ISSUE TITLE
bower.json of release contains invalid metadata

### ISSUE THREAD

**Issue by hefloryd** [digitalbazaar/forge#490]
The bower.json file of the release has invalid metadata:

```
$ bower install forge
bower not-cached    https://github.com/digitalbazaar/forge-dist.git#*
bower resolve       https://github.com/digitalbazaar/forge-dist.git#*
bower not-cached    https://github.com/digitalbazaar/forge-dist.git#^0.7.0
bower resolve       https://github.com/digitalbazaar/forge-dist.git#^0.7.0
bower download      https://github.com/digitalbazaar/forge-dist/archive/0.7.0.tar.gz
bower download      https://github.com/digitalbazaar/forge-dist/archive/0.7.0.tar.gz
bower extract       forge#^0.7.0 archive.tar.gz
bower extract       forge#* archive.tar.gz
bower invalid-meta  for:/tmp/user/bower/228410f5c71f8af2b1266b70fa7824eb-24471-UUxrBr/bower.json
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  for:/tmp/user/bower/228410f5c71f8af2b1266b70fa7824eb-24471-8HNFq6/bower.json
bower invalid-meta  The "main" field cannot contain minified files
bower resolved      https://github.com/digitalbazaar/forge-dist.git#0.7.0
bower resolved      https://github.com/digitalbazaar/forge-dist.git#0.7.0
bower install       forge#0.7.0
```

In a project using grunt-contrib-uglify I am seeing an issue where forge.min.js gets minified again which causes an error (this may be a problem with uglify though). In any case bower packages seem to usually contain the unminified file in the "main" field.

**Comment by davidlehn** [comment]
```
$ bower --version
1.8.0
$ bower install forge
bower cached        https://github.com/digitalbazaar/forge-dist.git#0.7.0
bower validate      0.7.0 against https://github.com/digitalbazaar/forge-dist.git#*
bower install       forge#0.7.0
```
What bower version shows those errors?

The unminified code is rather large so we were trying to avoid filling up the git history with it.  uglify-js@2.8.5 seems to handle the min file fine.  What error do you get?

**Comment by hefloryd** [comment]
I am on bower 1.7.9. It seems that 1.8.0 removed the warnings about minified files. Due to dependencies of other modules in the project I also have uglify-js@2.4.24. The error I get is:

`Uncaught ReferenceError: l is not defined`

which refers to this minified line:

`                l.exports = d.random
`

which in turn seems to correspond to the export line at the end of https://github.com/digitalbazaar/forge/blob/0713d53170ef76b507b2345d8d1d8d8295f01e9f/lib/random.js

I'll close this issue since bower appears to no longer care about minified files and the problem likely goes away with a newer uglify-js.
