### ISSUE TITLE
Convert md5 to base64

### ISSUE THREAD

**Issue by pratik2pris** [digitalbazaar/forge#494]
Hello I want to generate base64-encoded 128-bit MD5 digest with forge but I am not able to find any suitable method for this.

var md = forge.md.md5.create();
md.update(data);
return // " base64 string"

Can you help me ?

**Comment by dlongley** [comment]
I think this will do it:

```js
var md = forge.md.md5.create();
md.update(data);
var base64String = forge.util.encode64(md.digest().getBytes());
```

**Comment by pke** [comment]
I guess that can be closed? ;) @dlongley

**Comment by dlongley** [comment]
:)
