### ISSUE TITLE
Which files need to be hosted? 

### ISSUE THREAD

**Issue by sufuf3** [digitalbazaar/forge#506]
Hi @dlongley, @davidlehn 
We are cdnjs team, we're going to host this library.
[cdnjs](https://github.com/cdnjs/cdnjs) is one of the most famous free and public web front-end CDN services.

I want konw that what the files should need to be added in cdnjs?

There is an issue that both of `js/forge.js` and `js/prime.worker.js` in old versions and `dist/forge.js` and `dist/prime.worker.js` in current version should need to be added in cdnjs?

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#11162

**Comment by mattcollier** [comment]
@sufuf3 That's awesome, see https://github.com/digitalbazaar/forge/issues/186, closing this as dup.

**Comment by sufuf3** [comment]
@mattcollier Thank you. I'm sorry to bother you.
