### ISSUE TITLE
create PKCS#7 signed data

### ISSUE THREAD

**Issue by msibilsk** [digitalbazaar/forge#509]
Hi there, 

I am a little confused by the documentation for creating pkcs7 signatures. I need to use this module for safari push notifications to sign the manifest. There are two certs and a key (all pem files), and the thing I am signing (the manifest) will be a string. Here is what I thought would work: 

```js
  var p7 = forge.pkcs7.createSignedData();
  p7.content = forge.util.createBuffer(JSON.stringify(manifest), 'utf8');
  p7.addCertificate(intermediateCert);

  p7.addSigner({
    key: privateKey,
    certificate: mainCert,
    digestAlgorithm: forge.pki.oids.sha256,
    authenticatedAttributes: [{
      type: forge.pki.oids.contentType,
      value: forge.pki.oids.data
    }, {
      type: forge.pki.oids.messageDigest
      // value will be auto-populated at signing time 
    }, {
      type: forge.pki.oids.signingTime,
      // value can also be auto-populated at signing time 
      value: new Date()
    }]
  });

  p7.sign();
  var content = forge.pkcs7.messageToPem(p7);
```

Could you provide some guidance on where I am going wrong? 

Thank you!

**Comment by davidlehn** [comment]
What problem are you seeing with the above code?

**Comment by msibilsk** [comment]
I went with a different solution, and honestly I can't remember now. Thanks for reaching out.
