### ISSUE TITLE
smime certificate to be installed on Mac OS and/or iOS

### ISSUE THREAD

**Issue by yustein** [digitalbazaar/forge#526]
Hi,

Exactly 4 years ago (20 Jul 2013) I asked the question below, I was wondering if anyone figured out what exactly OpenSSL does that Forge can't in this? Regardless, it would be nice if anyone figured out why OpenSSL can do this but Forge can't...

Question from 4 years ago:
"Can you please tell me if it is possible to accomplish what the below code is doing in openssl with your module?

I'm basically trying to use my own CA which I already created to create and sign a pk12 format compatible S/MIME certificate.

sudo openssl genrsa -out smime.key 2048
sudo openssl req -new -config ../openssl.cnf -key smime.key -out smime.csr
sudo openssl x509 -req -days 365 -in smime.csr -CA ../cacert.pem -CAkey ../private/cakey.pem -set_serial 1 -out smime.crt -setalias "Self Signed SMIME" -addtrust emailProtection -addreject clientAuth -addreject serverAuth -trustout -extfile ../openssl.cnf -extensions mail_ext
sudo openssl pkcs12 -export -in smime.crt -inkey smime.key -out smime.p12

**Comment by davidlehn** [comment]
Some of that is certainly possible.  Did you try writing the code?  How far did you get?  What pieces are missing from forge?

**Comment by yustein** [comment]
Well I did finished the App and published it 4 years ago by compiling OpenSSL for iOS and calling the funtions from Javascript. 

My issue here is I’m pissed at the fact that OpenSSL have nearly a monopoly at this point.

Technically speaking, I don’t see any limitations with Forge in this context compared to OpenSSL. We just don’t know how OpenSSL creates the structure of the SMIME PKCS#12 file that makes it sing on iOS vs the file created by Forge. 

So far the best I can do is create the password protected PKCS#12 .p12 file, import it into iOS using the password but there are certain things which are missing. iOS shows the .p12 file is not signed. The same file is showing as it is signed by an unknown entity. 

I import my self created root private key into Forge and use that to sign the certificate then create the PKCS#12, convert it to base64, export it and use it as described above. 

Without finding out what is the exact structure of the PKCS#12 for SMIME certificate that OpenSSL creates which also iOS likes, how can we fix this?

**Comment by yustein** [comment]
Ok, tracing everything from the beginning...

The signing of the certificate seems to be one problem, here is the file in PEM format generated by Forge with signing of my own CA's private key. When I load this to Mac's Keychain app it shows as signed by unknown authority instead of giving the details of the authority. I'm attaching the PEM file with the cert inside and screen capture of the Keychain app's result.

[Archive1.zip](https://github.com/digitalbazaar/forge/files/1167341/Archive1.zip)

**Comment by yustein** [comment]
update: if I change the code from

`    cert.setSubject(attrs);
    cert.setIssuer(attrsIssuer);`

to

`    cert.setSubject(attrs);
    cert.setIssuer(attrs);`

when the resulting PEM loaded into the Keychain app now it shows as 

"this certificate has not been verified by a third party" instead of "this certificate is signed by unknown authority"

How can I sign this certificate with my cA's certificate instead of cA's private key because signing it with my cA's private key was the first example above which didn't help...
<img width="505" alt="screenshot 2017-07-22 14 52 16" src="https://user-images.githubusercontent.com/966682/28491216-6a763392-6eed-11e7-9b33-6f610277b54b.png">

**Comment by yustein** [comment]
I might have found a workaround, I will close this issue for the moment and let you know when I sort it out...

**Comment by matth-c3** [comment]
Hello @yustein , do you mind sharing your finding ?

thanks.
