### ISSUE TITLE
A little help needed (noobie)

### ISSUE THREAD

**Issue by joveice** [digitalbazaar/forge#529]
Hello, I'm new to encryption and stuff like that and have no plans to use it for something special.

So in the example AES CBC, where is the "data" that is getting encrypted? I'm trying to encrypt a string then decrypt it back to the string.

This will be a noobie question but I'm just trying to understand this.

**Comment by mattcollier** [comment]
See the examples given here: https://github.com/digitalbazaar/forge#ciphers-1
And also take a look at the tests: https://github.com/digitalbazaar/forge/blob/master/tests/unit/aes.js#L274

**Comment by joveice** [comment]
Okey, so I need to go from my plaintext to hex, then turn that to bytes then encrypt?

**Comment by s349856186** [comment]
hi joveice, Are you successful?@joveice

**Comment by joveice** [comment]
@s349856186 Nope

**Comment by MaxFichtelmann** [comment]
Hi @joveice,

when encrypting a string, you are really processing the bytes of that string. These may be dependent on the used encoding, so the character 'ü' is 0xFC in ISO 8859-1 (Latin-1) encoding, but 0xC3BC when using UTF-8.

forge ciphers use forge buffers as input, which represent a sequence of bytes.

You can use `forge.util.createBuffer(input, 'utf8')` to create a forge buffer from an utf-8 string.

Note: If you are not _required_ to use AES in CBC mode, don't. You are better of using AES-GCM.

full sample:

```
const plaintext = 'encrypt me please';
const key = forge.pkcs5.pbkdf2('password', 'salt', 1000, 16);
const iv = forge.random.getBytesSync(8);

const input = forge.util.createBuffer(plaintext, 'utf8')

// CBC
var cipher = forge.cipher.createCipher('AES-CBC', key);
cipher.start({iv});
cipher.update(forge.util.createBuffer(input));
cipher.finish();

var encrypted = cipher.output;

var decipher = forge.cipher.createDecipher('AES-CBC', key);
decipher.start({iv});
decipher.update(encrypted);
if (!decipher.finish()) {
  throw new Error('decryption failed - wrong key?')
}

if (plaintext !== decipher.output.toString('utf8')) {
  throw new Error('decipher yields wrong result')
}

// GCM
var cipher = forge.cipher.createCipher('AES-GCM', key);
cipher.start({iv});
cipher.update(forge.util.createBuffer(input));
cipher.finish();

var encrypted = cipher.output;
var tag = cipher.mode.tag; // authentication info, to make sure the used key matches the encrypted data

var decipher = forge.cipher.createDecipher('AES-GCM', key);
decipher.start({iv, tag});
decipher.update(encrypted);
if (!decipher.finish()) {
  throw new Error('decryption failed - wrong key?')
}
if (plaintext !== decipher.output.toString('utf8')) {
  throw new Error('decipher yields wrong result')
}
```
