### ISSUE TITLE
PKCS #12 to PEM

### ISSUE THREAD

**Issue by raijinsetsu** [digitalbazaar/forge#533]
I'm trying to convert a PKCS#12 container into a PEM file same as this OpenSSL command:
`openssl pkcs12 -in certificate.pfx -out certificate.pem -nodes`

This is my code (taking cues from p12-to-pem module):
```
export function convertPFX(pfx: Buffer | string, passphrase?: string) {

    let p12buffer: string;

    if (Buffer.isBuffer(pfx)) {
        p12buffer = pfx.toString('base64');
    } else {
        p12buffer = pfx;
    }

    const asn = forge.asn1.fromDer(forge.util.decode64(p12buffer));
    const p12 = forge.pkcs12.pkcs12FromAsn1(asn, true, passphrase);

    const keyData = p12.getBags({ bagType: forge.pki.oids.pkcs8ShroudedKeyBag })[forge.pki.oids.pkcs8ShroudedKeyBag]
        .concat(p12.getBags({ bagType: forge.pki.oids.keyBag })[forge.pki.oids.keyBag]);
    const certBags = p12.getBags({ bagType: forge.pki.oids.certBag })[forge.pki.oids.certBag];

    console.log(keyData);

    return {
        certificate: forge.pki.certificateToPem(certBags[0].cert),
        ca: certBags.slice(1).map((a) => forge.pki.certificateToPem(a.cert)),
        key: keyData.length ? forge.pki.privateKeyToPem(keyData[0].key) : undefined
    };
}
```

The problem is that the private key does not match the output from OpenSSL: the OpenSSL output starts with "-----BEGIN PRIVATE KEY-----\nMIIEvg" while the output from the node-forge module starts with "-----BEGIN RSA PRIVATE KEY-----\nMIIEpA". As you can see, not only is the header different, but so is the contents.

It is not exactly clear how to convert this correctly. The software I need to insert the PEM into requires the private key, not the RSA private key. I'm not an expert on certificate formats, so I'm at a loss here.

Note: I did try forge.pki.decryptRsaPrivateKey, but that threw an exception about the encrypted message length.

**Comment by dlongley** [comment]
The format you want is [PKCS#8](https://github.com/digitalbazaar/forge#pkcs8) and `forge.pki.privateKeyToPem` outputs PKCS#1.

Do this to get PKCS#8 PEM-encoded output:

```js
// convert a Forge private key to an ASN.1 RSAPrivateKey
const rsaPrivateKey = forge.pki.privateKeyToAsn1(privateKey);

// wrap an RSAPrivateKey ASN.1 object in a PKCS#8 ASN.1 PrivateKeyInfo
const privateKeyInfo = forge.pki.wrapRsaPrivateKey(rsaPrivateKey);

// convert a PKCS#8 ASN.1 PrivateKeyInfo to PEM
const pem = forge.pki.privateKeyInfoToPem(privateKeyInfo);
```

**Comment by raijinsetsu** [comment]
Thanks for the prompt reply. I'll give this a try.

**Comment by raijinsetsu** [comment]
Confirmed: that worked.

Thanks again.
