### ISSUE TITLE
code splitting

### ISSUE THREAD

**Issue by sahanatroam** [digitalbazaar/forge#558]
Hi there,

I'm trying to just use some parts of this library. But on my build the complete library is added. Is there a way to avoid this please ?

`import {jsbn, util, pki} from 'node-forge'`

**Comment by sahanatroam** [comment]
`[
![screen shot 2018-01-23 at 3 50 53 pm](https://user-images.githubusercontent.com/29851224/35255708-3d5eddce-0055-11e8-9969-d025d8309ac8.png)
](url)`

**Comment by davidlehn** [comment]
What were you trying to include?  You can use just some parts of forge.  It's not as fine grained as it should be so it may pull in some cruft.  In particular, the util.js file has a bunch of ancient things that we just haven't had time to pull out.  There's a snippet in webpack.config.js talking about custom builds.  Some of it is a bit hard to make generic since, for instance, you may want to pick and choose hash algorithms that you need.

**Comment by sahanatroam** [comment]
Hi @davidlehn,

`import {jsbn, util, pki} from 'node-forge'

function bytesToBigInteger(bytes) {
    const buffer = util.createBuffer(bytes)
    const hex = buffer.toHex()
    return new jsbn.BigInteger(hex, 16)
}

function base64ToBn(s) {
    const decoded = util.decode64(s)
    return bytesToBigInteger(decoded)
}

function decodeBase64PublicKey(modulus, exponent) {
    const mod = base64ToBn(modulus)
    const exp = base64ToBn(exponent)
    return pki.setRsaPublicKey(mod, exp)
}

export default function encryptAndEncodeData(key, data) {
    const publicKey = decodeBase64PublicKey(key.modulus, key.exponent)

    const encrypted = publicKey.encrypt(data)
    const encoded = window.btoa(encrypted)

    return encoded
}
`

this is my one file I need node-forge for.
And even if I require only what I need the whole library seems to end up in the build file 😢

**Comment by davidlehn** [comment]
Oh, I see.  forge is still using CJS and hasn't switched over to newer module style.  So when you do the `import..from` I think it's loading all of forge then just extracting the few exported vars you list.  CJS style isn't as smart about excluding unused code.  I'm not sure what the right answer is.  Building a custom bundle via webpack would work but requires some effort.  You might also be able to import the internals like 'node-forge/lib/pki' directly.

**Comment by sahanatroam** [comment]
ahh.. I like that about importing internals 👍  will try it in the next 8 hours and will get back to you !! Thanks

**Comment by sahanatroam** [comment]
@davidlehn yep, 20kb less now,

I'll take it 👍  thanks 
![Uploading Screen Shot 2018-01-24 at 10.01.15 AM.png…]()
