### ISSUE TITLE
What return publicKey.encrypt('holawe')

### ISSUE THREAD

**Issue by krthr** [digitalbazaar/forge#560]
Hey! What is the type of publicKey.encrypt() function? 

I want to decrypt an string, but i dont know what to pass to the function privateKey.decrypt() :cry:

**Comment by dlongley** [comment]
Forge uses binary strings (strings where each character is in 0-255 range). You can convert to/from other formats using the `forge.util.encode64`/`forge.util.decode64` functions for Base64 and `forge.util.encodeUtf8`/`forge.util.decodeUtf8` functions for UTF-8.

If you're using node.js then you can get strings of the same format using the `binary` encoding option, e.g. `new Buffer(foo).toString('binary')` or `require('fs').readFileSync(foo, 'binary')`.

If you need further help, please re-open this issue and provide a more specific code example of what you're trying to do. Thanks!
