### ISSUE TITLE
Unable to install with npm - Cannot read property 'target' of null

### ISSUE THREAD

**Issue by beastybeast** [digitalbazaar/forge#561]
Hi

Must admit that I do not normally use Node.js or npm but I like to get the latest un-minimized sources for the browser so I have tried!

On latest Ubuntu I run into this error that I do not understand when I try to run "sudo npm install"

`npm ERR! Linux 4.13.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/benny/node_modules/node-forge/npm-debug.log`

Thank you for any help to get further

/Benny

**Comment by davidlehn** [comment]
This is sparse on details.  Did the log file tell you what the issue was?

**Comment by beastybeast** [comment]
22780 silly generateActionsToTake Starting
22781 silly install generateActionsToTake
22782 verbose stack TypeError: Cannot read property 'target' of null
22782 verbose stack     at module.exports (/usr/share/npm/lib/install/filter-invalid-actions.js:24:35)
22782 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
22782 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
22782 verbose stack     at /usr/share/npm/node_modules/slide/lib/chain.js:18:7
22782 verbose stack     at Object.Installer.computeLinked (/usr/share/npm/lib/install.js:411:41)
22782 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
22782 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
22782 verbose stack     at /usr/share/npm/node_modules/slide/lib/chain.js:18:7
22782 verbose stack     at module.exports (/usr/share/npm/lib/install/diff-trees.js:50:3)
22782 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
22783 verbose cwd /home/benny/node_modules/node-forge
22784 error Linux 4.13.0-32-generic
22785 error argv "/usr/bin/node" "/usr/bin/npm" "install"
22786 error node v6.11.4
22787 error npm  v3.5.2
22788 error Cannot read property 'target' of null
22789 error If you need help, you may report this error at:
22789 error     <https://github.com/npm/npm/issues>
22790 verbose exit [ 1, true ]

**Comment by davidlehn** [comment]
No idea what that trace means.  What are you trying to do?  Looks like you ran install inside the installed node-forge package?

**Comment by beastybeast** [comment]
Yes I run it inside the installed node-forge package. Shall I jun it outside that folder?

Just trying to get my hand on the non-minified browser js file

**Comment by beastybeast** [comment]
The project release the minified versions, but for some reasons not the non minified

**Comment by davidlehn** [comment]
Yes, the package.json file is setup to only include the .min.js files in the npm tarball.  The installed npm package may not have all the files it needs to install/build.  I'm not sure.  You should check out the code from github, run the following commands, and the built files will be in the `dist/` dir:
```
npm install
npm run build
```

**Comment by beastybeast** [comment]
During execution of "npm install" I now get this error:

Error: EACCES: permission denied, mkdir '/home/benny/node_modules/node-forge/node_modules/wd/build'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at sync (/home/benny/node_modules/node-forge/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/home/benny/node_modules/node-forge/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm WARN karma-browserify@5.1.3 requires a peer of watchify@>=3 <4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

NB: The wd folder is not there

What to do next?

**Comment by davidlehn** [comment]
Go to a top level directory outside any node_modules dir, do a fresh code checkout via git, and do the install and build steps.

**Comment by dlongley** [comment]
It seems like this might be resolved so I'm going to close it. If not, please feel free to reopen with further questions.
