### ISSUE TITLE
Snyk vulnerability (ReDOS)

### ISSUE THREAD

**Issue by knoxcard** [digitalbazaar/forge#567]
✗ Medium severity vulnerability found on node-forge@0.7.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:node-forge:20180226
- from: node_services@1.0.0 > apn@2.2.0 > node-forge@0.7.2

**Comment by davidlehn** [comment]
See also: https://github.com/digitalbazaar/forge/issues/563

**Comment by knoxcard** [comment]
Gothcya, guess I'll just close this ticket out.
