### ISSUE TITLE
node-forge:  Unhandled exception - ZIP does not support timestamps before 1980

### ISSUE THREAD

**Issue by shaileshgoswami** [digitalbazaar/forge#568]
Hi,

From last week "Wednesday" (28th Feb 2018), our build is getting failed. When we debugged the issue found out that latest version of this library is failing when we are packaging.
 
aws cloudformation package --template x.yaml .......

Unable to upload artifact ../xxxxxxxxx/ referenced by CodeUri parameter of xxxxxxxxxFunction resource.
ZIP does not support timestamps before 1980

**node-forge**   all file under this library is having timestamp lower than 1980.....

**Container] 2018/02/28 09:49:31 Running command find ./* -mtime +10950**

./google-oauth-endpoint/node_modules/node-forge/LICENSE
./google-oauth-endpoint/node_modules/node-forge/README.md
./google-oauth-endpoint/node_modules/node-forge/CHANGELOG.md
./google-oauth-endpoint/node_modules/node-forge/flash/README.md
./google-oauth-endpoint/node_modules/node-forge/flash/swf
./google-oauth-endpoint/node_modules/node-forge/flash/swf/SocketPool.swf
./google-oauth-endpoint/node_modules/node-forge/lib/ssh.js
./google-oauth-endpoint/node_modules/node-forge/lib/pkcs7.js
./google-oauth-endpoint/node_modules/node-forge/lib/log.js
./google-oauth-endpoint/node_modules/node-forge/lib/index.all.js
./google-oauth-endpoint/node_modules/node-forge/lib/pbe.js

Same kind of issue has been reported earlier by other libraries also :

https://github.com/aws/aws-cli/issues/2639
https://github.com/mishoo/UglifyJS2/issues/2054

Would appreciate if anyone look into the issue, or point out the right direction.

**Comment by davidlehn** [comment]
I filed an issue on npm about this.  npm 5.7.1 is setting all timestamps to the epoch.  I published node-forge 0.7.3 with npm 5.6.0 which should fix the issue.

**Comment by shaileshgoswami** [comment]
thank you :+1:

**Comment by davidlehn** [comment]
npm issue fixed in 5.8.0.
