### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiaohuoni** [digitalbazaar/forge#574]
/lib/ed25519   218
const hash = md.digest().getBytes();

**Comment by dlongley** [comment]
Could you provide more details or a test case?

你能提供更多的细节还是测试用例？
(I used https://translate.google.com if it helps).
(我用了 https://translate.google.com  如果有帮助).

**Comment by dlongley** [comment]
Nevermind, I see you did a pull request. Thanks!

没关系，我看到你做了拉请求。 谢谢！
