### ISSUE TITLE
encode long text with rsa public key

### ISSUE THREAD

**Issue by parsibox** [digitalbazaar/forge#579]
hi
how can encode a long text with rsa ( public and private key )

**Comment by mattcollier** [comment]
Hello, for RSA encryption your plaintext should be shorter than the length of the key.  RSA 2048 gives you about 256 bytes to work with and RSA 3072 gives you 384 bytes etc.  You have the option of breaking your message into small chunks that would fit inside these limits and performing multiple RSA encryption operations.  However, this is not a good idea for a variety of reasons, chiefly that it is very slow for large messages.

Typically RSA is used to exchange a shared *symmetric* key for algorithms such as AES.

https://crypto.stackexchange.com/a/42181

**Comment by dlongley** [comment]
@parsibox,

One option is to use an RSA public/private key pair to encrypt a random AES-128 or AES-256 symmetric key. Then use that symmetric key to do your encryption of long text using something like AES-GCM -- and send the encrypted symmetric key and encrypted text to the private key holder. Then they can decrypt the symmetric key and use it to decrypt the text.

**Comment by parsibox** [comment]
i understand this
