### ISSUE TITLE
Q: How to convert a CSR signature to base64 string?

### ISSUE THREAD

**Issue by fschaefer** [digitalbazaar/forge#587]
I've a signed CSR and I'm trying to do the equivalent to:

`openssl sha1 -sign "$PRIVATE_KEY" "$CUSTOMER_CSR_DER" | base64`

The obvious approach doesn't seem output the correct encoded base64 string: 

`forge.util.encode64(csr.signature)`.

What am I missing here?

**Comment by davidlehn** [comment]
It's hard to know what's wrong without seeing your code.  Can you add runnable openssl and forge test cases that differ?

**Comment by fschaefer** [comment]
Basicly I'm using `forge.pki.createCertificationRequest()` as shown in `examples/create-csr.js`.
My hope was, that I've to convert the `csr.signature` buffer somehow before encoding it Base64.
I'll check my code and try to build a openssl vs. forge test.

**Comment by fschaefer** [comment]
It seems that I was "holding it wrong".  Forge is working as expected. Sorry for the noise. I'm closing this now.
