### ISSUE TITLE
Remark on initModule

### ISSUE THREAD

**Issue by Ayms** [digitalbazaar/forge#59]
Hi again,

In older versions, you were checking window. 

I think it was better because now it's not possible without hooking inside node.js to run the same code inside a browser and inside node.js (when you don't want to use node.js's modules, it can look strange but this is what I am doing).

To be clear: it seems more clean to define a window var on a server environment if you want to keep the code as it is inside the browser rather than destroying process properties, module.exports, etc to do so, which have of course side effects on other parts of the code that are using node.

Regards,

Aymeric

**Comment by dlongley** [comment]
Closing after updates via #456.
