### ISSUE TITLE
Error: Cannot read private key. ASN.1 object does not contain an RSAPrivateKey.

### ISSUE THREAD

**Issue by naramiss** [digitalbazaar/forge#597]
Hello, 

I have an issue when I try to convert my private key, that I read in a file with readFileSync, in a good forge format. I get this error : **Error: Cannot read private key. ASN.1 object does not contain an RSAPrivateKey.**

I let the code below : 
`var privaKey = fs.readFileSync('ca-key.pem', "utf8");`
`var privateKey = pki.privateKeyFromPem(privaKey);`

Really need help on this issue, thanks for your help !

**Comment by mattcollier** [comment]
Hello @naramiss, there are quite a few closed issues related to this topic, have you taken a look at those?

https://github.com/digitalbazaar/forge/issues?utf8=%E2%9C%93&q=is%3Aissue+privateKeyFromPem

**Comment by naramiss** [comment]
Yes I did but I didn’t found the solution. I tried to convert the privaKey variable with the toString() method but it didn’t fix the issue.

**Comment by mattcollier** [comment]
What is the nature of your PEM file?  Is it something you're generating yourself somehow?  Have you inspected the contents?

**Comment by naramiss** [comment]
Yes I generate a pem file with the openssl command line :
openssl genrsa -out ça-key.pem 4096

The file contains :
——BEGIN ENCRYPTED PRIVATE KEY——
...
——END ENCRYPTED PRIVATE KEY——

I first had an issue due to the fact that forge cannot find the PRIVATE KEY line in the file so I deleted the “encrypted” word in the file to make it work. And not I have this issue that I tried to fix by using the toString() method and by trying to encode it in base 64 but no results.

**Comment by mattcollier** [comment]
Ah!  In that case you're looking for `forge.pki.decryptRsaPrivateKey` as here:

https://github.com/digitalbazaar/forge/issues/517#issuecomment-312200276

**Comment by naramiss** [comment]
Thanks again for the help, it works perfectly now. I close the issue.
