### ISSUE TITLE
SHA256 Digest Signature

### ISSUE THREAD

**Issue by nbouvrette** [digitalbazaar/forge#647]
I'm trying to get a SHA256 signature but I cannot figure out how to do it with forge. Here is how I can achieve it with the Node.js Crypto module:

```js
const signer = crypto.createSign('RSA-SHA256').update('hello world', 'utf8');
const signature = signer.sign(privatePem);
console.log(signature);
```

I tried the following using forge but the output is different:

```js
let messageDigest = forge.md.sha256.create();
messageDigest.update('hello world', 'utf8');
const privateKey = await forge.pki.privateKeyFromPem(privatePem);
const signature = privateKey.sign(messageDigest);
console.log(signature);
```

Can anyone help?

**Comment by mattcollier** [comment]
Hello, just a matter of encoding the signature outputs in the same way: https://repl.it/repls/RipeLatestOctal

forge `privateKey.sign` produces a binary encoded string which must be decoded.

**Comment by nbouvrette** [comment]
Perfect, thanks for sharing this example.

```js
Buffer.from(forge.util.binary.raw.decode(privateKey.sign(messageDigest)));
```

This did the trick!

**Comment by sm2017** [comment]
@mattcollier can you tell me more about `binary encoded string`, I am using `forge.util.encode64(sign)` to have a base64 encoded sign, I never used `forge.util.binary.raw.decode` before and I'm willing to know its there 2 different RSA signing algorithm?

**Comment by mattcollier** [comment]
@sm2017 I have just updated the URL for the REPL example above, perhaps this will help.  For most other common operations including RSA signatures I recommend studying the test suite.
