### ISSUE TITLE
Binary value of a key's Modulus and Exponent

### ISSUE THREAD

**Issue by nbouvrette** [digitalbazaar/forge#648]
I'm working on an ACME client which uses JSON Web Keys and I need to access the binary values of a key's Modulus and Exponent to use the API.

So far I have found this recipe to get the binary value, but I am wondering if there is a better way (easier to read/understand) to get the same result?

```js
Buffer.from(forge.util.hexToBytes(keyPair.privateKey.n.toString(16)), 'binary').toString();
```

**Comment by mattcollier** [comment]
Here's a shorter version: https://repl.it/repls/IdealisticNimbleAgent

**Comment by nbouvrette** [comment]
Sorry, I should have mentioned, I need raw binary, not the '01' string format. Here is what I'm expecting:

`�T+�CV)9e� ր{م�h�Qp�%�Nb��...`

Now I'm getting:

`11001010110010111011101101111110101...`

**Comment by mattcollier** [comment]
OK, how about this: https://repl.it/repls/FriendlyQuietHashfunction

**Comment by nbouvrette** [comment]
Thanks - unfortunately, it doesn't work for Exponents?

https://repl.it/repls/UrbanScalyComputeranimation

**Comment by mattcollier** [comment]
Some padding is required.  https://repl.it/repls/ImpureRoyalSupercollider

Unlike the bn.js library, the forge `toString` implementation does not add padding: https://github.com/indutny/bn.js#utilities

**Comment by nbouvrette** [comment]
So in other words, my original post is probably the best way to achieve the results right now? would you see any use in adding a `toBytes` method to forge? If so, I could try to do a pull request.
