### ISSUE TITLE
Possible (though unprobable to hit) bug in kem.js

### ISSUE THREAD

**Issue by maltemuth** [digitalbazaar/forge#657]
I'm not knowledgeable enough in crypto stuff to follow the code and discuss it, either way I believe that the following line should also checkout that `r > 1` instead of just `r > 0`:

https://github.com/digitalbazaar/forge/blob/dfdde475677a8a25c851e33e8f81dca60d90cfb9/lib/kem.js#L63

Could someone knowledgeable enough kindly check this?

**Comment by dlongley** [comment]
> Could someone knowledgeable enough kindly check this?

Yes, looks like a bug. PR #658 should fix it.

**Comment by davidlehn** [comment]
Fixed in 0.8.1.  Thanks!
