### ISSUE TITLE
CSR PEM to DER returns result different than OpenSSL?

### ISSUE THREAD

**Issue by nbouvrette** [digitalbazaar/forge#659]
I was trying to convert a certification signing request (CSR) in PEM format to DER and it looks like when trying to use the `forge.pki.pemToDer` method I'm getting different results than OpenSSL? Did I miss anything? Example here:

https://repl.it/repls/WrongAstonishingBoard

**Comment by mattcollier** [comment]
Several issues with your example, this should get you going: https://repl.it/repls/ClutteredNegligibleRecovery

**Comment by nbouvrette** [comment]
Good catch - thanks again.

This is the second issue I open which required using `raw.decode` while I can hardly find any example online using this method. I'm not sure what is the typical clientele of node-forge but I know I'm only using it for simple HTTPS (ACME) certificate renewal.

I'm not familiar enough with the library to have any recommendations but let me know if you need help with any changes that would help make this type of use case more friendly.
