### ISSUE TITLE
Building into a single file using require.js

### ISSUE THREAD

**Issue by tanx** [digitalbazaar/forge#66]
Hi,

I saw that forge's modules are loaded conditionally making generating a single file through require build difficult, since require can't handle that:

http://requirejs.org/docs/optimization.html

The reason I need this is because browserify can't resolve the node style require() depencies either and my hope is that requiring a single module might do the trick.

Is there any way to bundle the entire library into a single module? 

Thanks

**Comment by kin9puppy** [comment]
http://digitalbazaar.github.io/forge/javascripts/forge/forge.min.0.6.12.js
