### ISSUE TITLE
wrong sha-256 hash computation on pdf files

### ISSUE THREAD

**Issue by shubo** [digitalbazaar/forge#665]
after downloading this file [http://africau.edu/images/default/sample.pdf](url) (or any pdf file)
code below returns different hashs. crypto returns same hash like ```shasum -a 256 sample.pdf``` 

2ff51af9a9338cd9ea2e0782f636e37236b6dff1f1cf7745b26dbcba8f59542a

```
const fs = require('fs');
const crypto = require('crypto');
const forge = require('node-forge');

fs.readFile('./sample.pdf', function(error, buffer){
    let md = forge.md.sha256.create();
    md.update(buffer);
    console.log(`forge hash: ${md.digest().toHex()}`);    
    console.log(`crypto hash: ${crypto.createHash('sha256').update(buffer).digest('hex')}`);
});
```

outputs

forge hash: 1e445d0c9a2ec393c144e55758c86dd46f009ee91a975cf78ef8ecaac21b4166   <br>                                                                                             crypto hash: 2ff51af9a9338cd9ea2e0782f636e37236b6dff1f1cf7745b26dbcba8f59542a

**Comment by shubo** [comment]
saw #128 
```
let data = String.fromCharCode.apply(null, buffer);
```
after adding it hash is equal with crypto

**Comment by ponchofiesta** [comment]
Just had the same problem. This should be some where in documentation/examples.
