### ISSUE TITLE
incorrect GCM tag when a binary is passed in chunks via update

### ISSUE THREAD

**Issue by MaxFichtelmann** [digitalbazaar/forge#666]
I am not sure if I am doing something wrong, but it seems that the generated authentication tags are incorrect, if data is passed to the gcm cipher using multiple update calls.

I have created a repl that demonstrates the issue: https://repl.it/@MaxFichtelmann/forge-gcm

The single-pass tag appears to be the correct one.

**Comment by dlongley** [comment]
This is a bug ... thanks for finding it! I'm surprised we didn't find it earlier. I've put in PR #668 to fix it.

**Comment by MaxFichtelmann** [comment]
Thank you for the swift response!

**Comment by davidlehn** [comment]
Fixed in 0.8.2.
