### ISSUE TITLE
revision controlled .min.js files

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/forge#67]
I personally think the .min.js files should be left out of revision control. Just add instructions and a script to build them. Is that too much effort for users to handle? Would pre-built versioned downloads be better?

If they are left in, should they be updated with every single source changing commit? That would be a pain to do and cause repo bloat but I think could cause confusion if not done. If constant or per-release .min.js updating is the way forward, then please update the HACKING.md file to spell out the steps needed and when to perform them to keep the .min.js files correct.

**Comment by dlongley** [comment]
Addressed by #456.
