### ISSUE TITLE
Unhandled Rejection (TypeError): tmp.length is not a function

### ISSUE THREAD

**Issue by abhijithvijayan** [digitalbazaar/forge#688]
I have a key that is 32bytes in length which is in `Uint8Array` form. I used an encoder to convert this array to `base64uri` format and used the output in
`
    const cipher = forge.cipher.createCipher('AES-GCM', base64uriKey);
`

and this error pops up

![Screenshot from 2019-06-28 16-03-02](https://user-images.githubusercontent.com/34790378/60336551-4ad7bf80-99be-11e9-96a5-f5edfa60d3dd.png)
![Screenshot from 2019-06-28 16-03-12](https://user-images.githubusercontent.com/34790378/60336552-4ad7bf80-99be-11e9-9612-ba513f46da77.png)

**Comment by abhijithvijayan** [comment]
Uint8Array(32) 
`[193, 130, 178, 153, 62, 192, 1, 8, 203, 199, 52, 97, 60, 37, 174, 216, 221, 100, 96, 203, 65, 10, 72, 140, 105, 248, 50, 30, 158, 148, 12, 197]
`

base64uri-encoded MUK :  `wYKymT7AAQjLxzRhPCWu2N1kYMtBCkiMafgyHp6UDMU`

**Comment by abhijithvijayan** [comment]
@dlongley Help would be appreciated.

**Comment by davidlehn** [comment]
@abhijithvijayan forge was written before Uint8Array existed and still uses it's own buffer format.  Try something like this:
```js
const cipher = forge.cipher.createCipher('AES-GCM', forge.util.createBuffer(base64uriKey));
```

**Comment by abhijithvijayan** [comment]
@davidlehn 

`forge.util.createBuffer(base64uriKey)` produced 

![Screenshot from 2019-06-29 16-24-05](https://user-images.githubusercontent.com/34790378/60383100-6ad4b500-9a8a-11e9-8a5b-0edd65d47547.png)
`
and cipher function threw 

`Unhandled Rejection (Error): Invalid key parameter.`

<hr />

So I directly gave the `Uint8Array` input to `forge.util.createBuffer()` and that produced 

![Screenshot from 2019-06-29 16-27-12](https://user-images.githubusercontent.com/34790378/60383132-c8690180-9a8a-11e9-8051-0f9ae3e4edc4.png)
(data field same as input array)

which when fed to `cipher` function produced a 48 byte key

![Screenshot from 2019-06-29 16-30-46](https://user-images.githubusercontent.com/34790378/60383173-49c09400-9a8b-11e9-99b4-f935f07fc4ec.png)

This is the expected output that the cipher function produces right?

**Comment by dlongley** [comment]
@abhijithvijayan,

Pass the `Uint8Array` directly to `forge.util.createBuffer()` like you're doing:

```js
const cipher = forge.cipher.createCipher('AES-GCM', forge.util.createBuffer(theUint8ArrayHere));
```

Inspecting the underlying `DataBuffer` implementation is confusing you as to the length of the data. The underlying buffer might be 48 bytes, but that does not mean that there are 48 bytes of valid data there. This is similar to an Uint8Array that is a "view" into an ArrayBuffer that may have a very different size from the view.

You must call `length()` to see the number of bytes in the forge buffer:

```js
const b1 = new Uint8Array([193, 130, 178, 153, 62, 192, 1, 8, 203, 199, 52, 97, 60, 37, 174, 216, 221, 100, 96, 203, 65, 10, 72, 140, 105, 248, 50, 30, 158, 148, 12, 197]);
const b2 = forge.util.createBuffer(b1);
console.log('b2.length', b2.length());
```

This should print `32`.

**Comment by abhijithvijayan** [comment]
@dlongley Thanks for the help.
