### ISSUE TITLE
AES-CBC decrypt Chinese error

### ISSUE THREAD

**Issue by dasoncheng** [digitalbazaar/forge#700]
First of all, thanks to the authors for the open source tool, I encountered some problems in using it

## environment

- "OS": "macOS 10.14.6"
- "node-forge": "0.8.5"
- "Firefox": "68.0.1 "
- "Chrome": "75.0.3770.142"

## function
```ts
import { cipher, util } from 'node-forge';

function aes_encrypt(param: string): string {
  const c = cipher.createCipher('AES-CBC', 'key');

  c.start({ iv: 'iv' });
  c.update(util.createBuffer(param, 'utf8'));
  c.finish();

  return util.encode64(c.output.getBytes());
}

function aes_decrypt(param: string): string {
  const decipher = cipher.createDecipher('AES-CBC', 'key');
  decipher.start({ iv: 'iv' });
  // decipher.update(new util.ByteStringBuffer(util.decode64(param)));
  decipher.update(util.createBuffer(util.decode64(param), 'utf8'));
  decipher.finish();

  return decipher.output.data;
}
```

```ts
const encrypt_str = forge.aes_encrypt('hello, 世界！');
const decrypt_str = forge.aes_decrypt(encrypt_str);
// "hello, ä¸çï¼"
```
How do I get the correct decrypted string use aes_decrypt

## online demo

[angular-forge.stackblitz.io](https://stackblitz.com/edit/angular-forge)

**Comment by dlongley** [comment]
The decoding not being in the reverse order of the encoding.

The above encrypt function takes `param` as a regular JS string of characters and then:

1. Encodes those characters using UTF-8 and represents the bytes using a binary string. (`util.createBuffer(param, 'utf8')`).
2. Encrypts the binary string buffer to produce encrypted bytes as a binary string buffer (`c.update`, `c.finish`).
3. Encodes the binary string output from the encryption operation using base 64 (`util.encode64(c.output.getBytes())`).

The decrypt function therefore should:

1. Base 64 decode the data (`util.decode64(param)`).
2. Decrypt the encrypted binary string output from the encryption operation (`decipher.update`, `decipher.finish`).
3. Decode the UTF-8 encoded bytes that are represented as a binary string to produce a JS string of characters (`decipher.output.toString()`). You could also call `util.decodeUtf8(decipher.output.getBytes())` but that is more verbose.

So, try this change to your decrypt function:

```
function aes_decrypt(param: string): string {
  const decipher = cipher.createDecipher('AES-CBC', key);
  decipher.start({ iv: 'iv' });
  decipher.update(util.createBuffer(util.decode64(param)));
  decipher.finish();

  return decipher.output.toString();
}
```

Also, please note that your key should be a 16 or 32 forge byte buffer, not a JS string of characters. If you want to create a key from a password, please use a key derivation function. Forge provides one if you need it: [pbkdf2](https://github.com/digitalbazaar/forge#pkcs5).

**Comment by dasoncheng** [comment]
@dlongley thanks a lot
