### ISSUE TITLE
Unit test is wrong

### ISSUE THREAD

**Issue by nicolas-f** [digitalbazaar/forge#725]
On this unit test:

https://github.com/digitalbazaar/forge/blob/master/tests/unit/aes.js#L466

With key
2b7e151628aed2a6abf7158809cf4f3c

And iv
000102030405060708090a0b0c0d0e0f

The result should be
3b79424c9c0dd436bace9e0ed4586a4f

http://aes.online-domain-tools.com/link/1ac6441g5zNWuBfF0l/

This has been tested with python PyCrypto and it give the same result as the linked web page.

```python
from Crypto.Cipher import AES

def test1():
    keys = [
        '00000000000000000000000000000000',
        '2b7e151628aed2a6abf7158809cf4f3c',
        '2b7e151628aed2a6abf7158809cf4f3c',
        '2b7e151628aed2a6abf7158809cf4f3c',
        '2b7e151628aed2a6abf7158809cf4f3c'
    ]
    ivs = [
        '80000000000000000000000000000000',
        '000102030405060708090a0b0c0d0e0f',
        '3B3FD92EB72DAD20333449F8E83CFB4A',
        'C8A64537A0B3A93FCDE3CDAD9F1CE58B',
        '26751F67A3CBB140B1808CF187A4F4DF'
    ]
    inputs = [
        '00000000000000000000000000000000',
        '6bc1bee22e409f96e93d7e117393172a',
        'ae2d8a571e03ac9c9eb76fac45af8e51',
        '30c81c46a35ce411e5fbc1191a0a52ef',
        'f69f2445df4f9b17ad2b417be66c3710'
    ]
    outputs = [
        '3ad78e726c1ec02b7ebfe92b23d9ec34',
        '3b3fd92eb72dad20333449f8e83cfb4a',
        'c8a64537a0b3a93fcde3cdad9f1ce58b',
        '26751f67a3cbb140b1808cf187a4f4df',
        'c04b05357c5d1c0eeac4c66f9ff7f2e6'
      ]
    for i in range(len(inputs)):
        aes_key = bytes.fromhex(keys[i])
        iv = bytes.fromhex(ivs[i])
        aes_in = bytes.fromhex(inputs[i])
        aes_expected_out = bytes.fromhex(outputs[i])
        aes_cipher = AES.new(aes_key, AES.MODE_CFB, iv)
        aes_out = aes_cipher.encrypt(aes_in)
        print("Test %d ok ? %s %s == %s" % (i, outputs[i] == aes_out.hex(), outputs[i], aes_out.hex()))
test1()
```

What is the issue here ?

Thanks

**Comment by davidlehn** [comment]
@dlongley figured it out.  CFB mode in python has a `segment_size` parameter.  Forge supports CFB128 while Python defaults to CFB8.  1 and 8 are inefficient and rarely supported by libraries.  The Node.js `crypto` library also only supports CFB128 and produces the same output as forge.

Forge uses the NIST test vectors, so they should all be ok.  See F.3.13:
https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf

Here's some more text about this:
https://security.stackexchange.com/questions/85727/what-is-the-segment-size-when-using-cipher-feedback-cfb-chaining-mode/85741

To make your Python code match what Forge does, here's the change:
```diff
-        aes_cipher = AES.new(aes_key, AES.MODE_CFB, iv)
+        aes_cipher = AES.new(aes_key, AES.MODE_CFB, iv, segment_size=128)
```
Docs on that parameter:
https://www.dlitz.net/software/pycrypto/api/current/Crypto.Cipher.AES-module.html#new

**Comment by nicolas-f** [comment]
Thanks, I was not aware of CFB128 type.

Maybe you could add a notice in the Readme to explain that you use the CFB128 as written in NIST test vectors ?
