### ISSUE TITLE
Create a pkcs#7 signed with a pkcs#11 token

### ISSUE THREAD

**Issue by andres-blanco** [digitalbazaar/forge#729]
I'm trying to make a pdf signature. They need to be encoded in a pkcs#7 message.
The current way of adding a signer to a pkcs7 message requires a private key as parameter. If you are using a pkcs11 token you don't have access to the private key itself, you can only pass the buffer to the token for it to sign.

Is there a way to add a signer without sending the private key? Maybe a callback that receives the buffer and returns it signed?

If there is no current way i'm willing to make a PR

Cheers!

**Comment by davidlehn** [comment]
I'm not sure there's an official way to do that (i'm also not very familar with pkcs#11).  Poking at the code, looks like maybe the only use of the key param is in `addSignerInfos()`:
```js
      signer.signature = signer.key.sign(signer.md, 'RSASSA-PKCS1-V1_5');
```
So maybe with a key object with a custom `sign()` function it could work.  I think this is all a sync API currently, so if the signing code was async, it may involve more invasive API changes to make it work.  I imagine all of forge should evolve to be more async to better support using HSM hardware and similar. 

If minimal changes are needed to support your use case, we'll certainly consider such a PR.

**Comment by andres-blanco** [comment]
Great, on Monday I'll make the change and see if it works

**Comment by andres-blanco** [comment]
Hey, I tried to sign using an object with a sign function. 
The 'trick' to make it work was to avoid using the **md** parameter and instead hash over the original content. The pkcs#11 tokens digests and signs the contents (all done inside the token), so I need access to the raw bytes, but I couldn't access the raw bytes from the **md** parameter of the sign function.
Is there a way to do it? 

I'm using this library: https://github.com/PeculiarVentures/graphene to access the token.

**Comment by andres-blanco** [comment]
Here is the code I'am using to create a p7 message that's valid for embedding in a pdf file:
https://github.com/SIU-Toba/node-signpdf/blob/feature/pkcs11-token/src/signpdf.js#L137

**Comment by vbuch** [comment]
@andres-blanco, if you read on pdf signatures, you'll see that you need to sign with P7 in detached mode. Detached mode means only signing the md. So fpr the pdf case you maybe need the byte representation of the md. I am pretty sure you don't need the whole body.

**Comment by andres-blanco** [comment]
I don't need the body to include in the P7 message, I need it to send it to the pkcs#11 token for it to digest and sign.
I could use the [CKM_RSA_PKCS](https://www.cryptsoft.com/pkcs11doc/v100/group__SEC__13__MECHANISMS.html#CKM_RSA_PKCS) mechanism, which doesn't do a digest but if I do it that way I think I have to sign something wrapped in an ASN1 package as per this [answer](https://stackoverflow.com/questions/47106122/sign-sha256-hash-with-rsa-using-pkcs11-api).
If I use a mechanism that does the digest inside the token (for example CKM_SHA256_RSA_PKCS) and I pass the correct bytes to be digested (as you can see [here](https://github.com/SIU-Toba/node-signpdf/blob/feature/pkcs11-token/src/signpdf.js#L144)), it works as expected.

**Comment by andres-blanco** [comment]
I prefixed the digest with the bytes from the pkcs#1 spec and it worked! (https://stackoverflow.com/a/47106124)
You can see the code here: https://github.com/SIU-Toba/node-signpdf/blob/feature/pkcs11-token/src/signpdf.js#L140-L152

Closing this issue since there's nothing to do in node-forge.

**Comment by FilipeAraujo** [comment]
@andres-blanco first of all, thanks for the example you gave, it help me a lot implementing digital signature using pkcs#11, however every time I use your example the PDF has the digital signature but adobe acrobat reader says: 

```

Error during signature verification.  

Error encountered while validating:  

Error encountered while BER decoding:
```

Did you get this error when you did your tests?

Thanks for the help!

**Comment by dearzubi** [comment]
> I prefixed the digest with the bytes from the pkcs#1 spec and it worked! (https://stackoverflow.com/a/47106124) You can see the code here: https://github.com/SIU-Toba/node-signpdf/blob/feature/pkcs11-token/src/signpdf.js#L140-L152
> 
> Closing this issue since there's nothing to do in node-forge.

Thanks for the help. Cheers.
Struggled so hard to get a PKCS10 certificate request get signed. This helped a lot. It's working now.
