### ISSUE TITLE
Certificate Chain missing while creating pkcs12 

### ISSUE THREAD

**Issue by sureshreddygovindu** [digitalbazaar/forge#759]
Really appreciating your **forge**, I'm using this source to generate pkcs12 using certificate, certificate chain and key. 

code snippet 
```js
    let forgeKey = forge.pki.privateKeyFromPem(params.key);
    let forgeCert = forge.pki.certificateFromPem(params.certificate);
    let forgeCertChain = forge.pki.certificateFromPem(params.certChain)
    console.log("*************** Cert chain", params.certChain);
    let newPkcs12Asn1 = forge.pkcs12.toPkcs12Asn1(
      forgeKey, [forgeCert, forgeCertChain], passPhase,
      { generateLocalKeyId: true, friendlyName: 'test', algorithm: '3des' });
    let newPkcs12Der = forge.asn1.toDer(newPkcs12Asn1).getBytes();
    let p12b64 = forge.util.encode64(newPkcs12Der);
```

Once I get the certificate, I try to open using **openssl pkcs12 -in gibbon3.p12**
I observed that certificate chain is missing( root certificate). Can you assist me where I'm missing?

**Comment by sureshreddygovindu** [comment]
@davidlehn can you assist me on it?

**Comment by sureshreddygovindu** [comment]
any update on it @davidlehn

**Comment by sureshreddygovindu** [comment]
@dlongley can you please update on it?

**Comment by davidlehn** [comment]
@sureshreddygovindu We're very busy and find it difficult to help with these sorts of issues.  You should at least make the test case runnable code and explain what is the expected output.

**Comment by sureshreddygovindu** [comment]
Thanks for update
[create-pkcs12.js.zip](https://github.com/digitalbazaar/forge/files/4221576/create-pkcs12.js.zip)
@davidlehn I've created test case 
1. Input PrivateKey, PublicCert and Certificate Chain(ICA & Root)
2. Output PKCS12 format cert. 
3. CertificateChain(ICA & Root) missing in PKCS12

**Comment by sureshreddygovindu** [comment]
ICA and Root Certs(Certificate Chain)  are missing in pkcs12 format cert even though I've injected Key, Cert and Chain for creation of PKCS12

**Comment by sureshreddygovindu** [comment]
I fixed this. I've separated ICU and Root cert.
