### ISSUE TITLE
Can I use node-forge to encrypt a signed mail pkcs#7 

### ISSUE THREAD

**Issue by peteroreil** [digitalbazaar/forge#763]
I am completely in the dark when it comes to the dark arts of encryption.
I am attempting to send a signed and encrypted email with native JS.

I have checked out [nodemailer-smime](https://github.com/gazoakley/nodemailer-smime#readme) and seen that they are using node-forge for signing mail. Is it possible to take a signed mail and encrypt it using `node-forge` and if so how?

So far this is what I have tried but to no success. Any help would be greatly appreciated.

```
module.exports.encrypt = (pubKey, content) => {
	p7 = forge.pkcs7.createEnvelopedData();
	const cert = forge.pki.certificateFromPem(pubKey);
	p7.addRecipient(cert);
	p7.content = forge.util.createBuffer(content);
	p7.encrypt();
	const asn1 = p7.toAsn1();
	asn1.value[1].value[0].value[2].value.splice(1, 1);
	const der = forge.asn1.toDer(asn1);
	const derBuffer = Buffer.from(der.getBytes(), 'binary');
	const encr = derBuffer.toString('base64')
	return format(encr);
}

function format(str) {
	let result = '';
	while (str.length > 0) {
		result += str.substring(0, 64) + '\n';
		str = str.substring(64);
	}
	return result;
}
```

**Comment by KevinBLT** [comment]
@peteroreil Were you able to achieve this? I am stuck with this as a nodemailer plugin, also coming from the smime signer plugin. The message is always undecryptable.

**Comment by peteroreil** [comment]
No @KevinBLT, unfortunately I couldn't. I think I ended up using a wrapper for an openssl binary to get it to work, but it was a PITA.

**Comment by KevinBLT** [comment]
Oh man that's a pitty. Even more considering how good S/MIME signing works with this library. I wonder why they are not putting effort into this topic. Nonetheless, thank you for clarifying.
