### ISSUE TITLE
Is there any simple to get BigIntString from RSA private key elements (for example from primes)?

### ISSUE THREAD

**Issue by Asphiii** [digitalbazaar/forge#772]
![image](https://user-images.githubusercontent.com/32648528/76748968-feb2f200-677b-11ea-8354-7e870454e5ff.png)
Is there an easy way to convert this kind of numbers into BigIntString?

**Comment by Asphiii** [comment]
I've found the answer - we can use toByteArray() like this:
key.privateKey.p.toByteArray()
and from this form convert to string
i'm closing

**Comment by davidlehn** [comment]
I'm not sure what a BigIntString is, but note that the jsbn BigInteger forge uses also has a `toString(radix)` method that might be more direct for your use case.
