### ISSUE TITLE
Issue in writing a .p12 using writeFile API

### ISSUE THREAD

**Issue by alawatugoda** [digitalbazaar/forge#798]
Hi @dlongley , thank you so much for explaining the concept behind Asn1, DER and p12 formats in a reply to my previous email.

According to @dlongley 's valuable explanation, my  code was:

var crt = fs.readFileSync ('jiji.cert.pem');
var crt_forge = forge.pki.certificateFromPem(crt);
var sk = fs.readFileSync ('jiji.key.pem');
var sk_forge = forge.pki.privateKeyFromPem(sk);

// get the ASN.1 representation of a PKCS#12 archive
var p12Asn1 = forge.pkcs12.toPkcs12Asn1(sk_forge, [crt_forge], 'password');
// encode the ASN.1 representation using DER
var p12Der = forge.asn1.toDer(p12Asn1).getBytes();
// write the `p12Der` binary string to a file
fs.writeFile("cert.test.p12", p12Der, {encoding: 'binary'},
  function(err) {
   if(err) {
     return console.log(err);
   }
});

This runs without errors and generates a .p12 file. But when I tried to load it, it gives an error saying "content of this item cannot be retrieved" in my Mac. I have manually created the .p12 file and noticed a slight difference. Manual one loaded properly and I noticed it is 2285 bytes, whereas the code-generated .p12 is 2273 bytes. I'm wondering what is going on here.

**Comment by dlongley** [comment]
You may need to use `3des` encryption in order for it to be imported in your browser:

> Note for Chrome/Firefox/iOS/similar users: If you have trouble importing a PKCS#12 container, try using the TripleDES algorithm. It can be passed to forge.pkcs12.toPkcs12Asn1 using the {algorithm: '3des'} option.

https://github.com/digitalbazaar/forge#pkcs12

```js
// generate a p12 that can be imported by Chrome/Firefox/iOS
// (requires the use of Triple DES instead of AES)
var p12Asn1 = forge.pkcs12.toPkcs12Asn1(
  privateKey, certificateChain, 'password',
  {algorithm: '3des'});
```

**Comment by alawatugoda** [comment]
> You may need to use `3des` encryption in order for it to be imported in your browser:
> 
> > Note for Chrome/Firefox/iOS/similar users: If you have trouble importing a PKCS#12 container, try using the TripleDES algorithm. It can be passed to forge.pkcs12.toPkcs12Asn1 using the {algorithm: '3des'} option.
> 
> https://github.com/digitalbazaar/forge#pkcs12
> 
> ```js
> // generate a p12 that can be imported by Chrome/Firefox/iOS
> // (requires the use of Triple DES instead of AES)
> var p12Asn1 = forge.pkcs12.toPkcs12Asn1(
>   privateKey, certificateChain, 'password',
>   {algorithm: '3des'});
> ```

Yes, it worked. Thank you so much. I have written my code and run as a desktop application. So it seems 3DES is needed in iOS. Will this code run in Windows too?

**Comment by dlongley** [comment]
> Yes, it worked. Thank you so much.

Sure!

> Will this code run in Windows too?

In theory. You'll have to try it -- no guarantees. We don't specifically test with Windows -- but forge runs in both modern browsers and node.
