### ISSUE TITLE
public key encrypt RSAES_OAEP PADDING?

### ISSUE THREAD

**Issue by jfromaniello** [digitalbazaar/forge#80]
I'm trying to migrate a code that uses the [Obvious/ursa](https://github.com/Obvious/ursa) module, the code is:

``` javascript
  var rsa_pub_ursa = ursa.createPublicKey(pub);
  var encrypted_key = rsa_pub_ursa.encrypt(key);
  console.log(encrypted_key.toString('base64'));
```

which seems to be the equivalent in forge to this:

``` javascript
  var rsa_pub = pki.publicKeyFromPem(pub);
  var encrypted_key = rsa_pub.encrypt(key, 'RSA-OAEP'); 
  console.log(new Buffer(encrypted_key).toString('base64'));
```

Except is not, and does not pass my tests, the result seems longer and decrypt fails with "Uncaught Error: error:0406506C:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data greater than mod len".

while the ursa output is something like this:

```
OtWlaSKBuXeAvwjwcYK9IBMwGbu44JwBzcmCkjv1FXYl1lUiknaCxhML4H8ZZ4jqccyiYr9rX1ZH6LnH2ba9wZmHZmSyUnCBKS2wcBxKjxP+Dfpo1sU/ivh74OrY3ggrZUPgLLhLOGCmULmjdqk5SY2L8tl9vTXAuCxdjMpNahbtZKlswFd4rTZkMJmJtfRf7bkCsW5MX6SpAoJYhGmkW052Qu2/1dzjLjzm47UlzP3Mm29KSJ0W3rWcWcPXpo6oqnWwcpyU2B1mq2XmpzCNXtlAGnsFYwUoJc5INp28xlvVsc+YPv5kiwjn0i7oz4lJ2yLYQxw22+zj41r+ZHxsqg==
```

forge is like this:

```
TxbCp1nDoRPCtsOUOVLDkDrCrsKAcsKywpLDq8KrwojCrsKfbsOUIcODKcO2El1FZAbDkQvDvcKgwrlcw5jDu1xQw5XClSHDun/CiR5bZinCoS7DisKCw5kow6bDul3DncOJWVgUZMKow4HDt8KYwrzDk8K/EsOjw4rDqMK9w7zDgsKmw5rCrAA3TsKswp1fwqQAwoJzwqA9BTvCmiXDhwDDozgJIUMJw6vDhAcBw7rCoMKEworDsknCiRzDvsOOwrMsTcOeRsKySMO8N8K8w6FfUAhiw4M3HMKfw7LCtmg/a2bDtSZnwqNlbcKIwrl/OMKXw7Qww5xRwpXCuWjCqyDCmEAjeMKPQ8K0KmfDicO2w4NeH8K/PnhmwrDDt3DCk1jDh2FgwpZvw4fDiMOgw5rCqhIRwr/DtcOGWcOdBmzDs3l7wrFIw6cZD8KOd2TCum3DicONw53Dh1HDmsOSw6Bjw5NDw63DhMKqEB1FOcKGAk7CvXHDiznChU8rw75yTSjDng==
```

Ursa documentation says it uses `RSA_PKCS1_OAEP_PADDING` by default I don't know if this is different from `RSA-OAEP` in forge

thanks a lot

**Comment by Erpraveen-28** [comment]
Can you provide CDN for the crypto library. Because it is no longer supported in "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"

**Comment by Erpraveen-28** [comment]
> Sure! :)

**Comment by Erpraveen-28** [comment]
Can you provide CDN for the crypto library. Because it is no longer supported in "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"
