### ISSUE TITLE
Support for OID 1.3.14.3.2.29 (sha1RSA)

### ISSUE THREAD

**Issue by dpwatrous** [digitalbazaar/forge#825]
It looks like there is currently no handling of [OID 1.3.14.3.2.29 (sha1RSA)](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpnap/a48b02b2-2a10-4eb0-bed4-1807a6d2f5ad) , causing the following error to be thrown when computing a digest: "Could not compute certificate digest. Unknown signature OID."

I suspect the same code that handles 1.2.840.113549.1.1.5 would work here, and I'm happy to try to put together a PR for this, but any guidance would be appreciated!

**Comment by dpwatrous** [comment]
Looking at [this issue](https://github.com/pyca/cryptography/issues/3160) in python's cryptography library seems to indicate we can treat this the same as 1.2.840.113549.1.1.5 (sha1WithRSAEncryption).

Because the id -> name and name -> id mappings are 1:1, we'd either have to change the structure of the maps or introduce a new name. I'm leaning toward the latter to limit the scope of the change.

**Comment by dpwatrous** [comment]
A couple more links to similar issues (which include more context):

Chromium: https://codereview.chromium.org/1223763002
Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1042479

**Comment by davidlehn** [comment]
Fixed in https://github.com/digitalbazaar/forge/pull/940.
