### ISSUE TITLE
Is there a way to read a .KEY file ?

### ISSUE THREAD

**Issue by icebergdelphi** [digitalbazaar/forge#828]
Hi I am traying to read a .Key file from  my computer but I get always errors like:Cannot read private key. ASN.1 object does not contain an RSAPrivateKey.

This is part of my code:
/Lee Key
	function readKeyFromFile(){
	// Get Key
	var fileInput = document.getElementById('keyFile'); //test.key
	var file = fileInput.files[0];

	// Leer archivo
	var reader = new FileReader();
	reader.onload = function(e) 
		{
		var contents = e.target.result;
		var pkcs12Der = arrayBufferToString(contents)
		var pkcs12B64 = forge.util.encode64(pkcs12Der);
		var keyPem =  arrayBufferToPrivatePem(pkcs12B64);
		
			 $('#privateKetTxt').val(pkcs12B64);
			 var forgePrivateKey = forge.pki.privateKeyFromPem(keyPem); //<---ERROR

		}
		reader.readAsArrayBuffer(file);
	}
function arrayBufferToPrivatePem (data){
        return    '-----BEGIN RSA PRIVATE KEY-----\r\n'
                + data + "\r\n"
                + '-----END RSA PRIVATE KEY-----\r\n';
    }

**Comment by icebergdelphi** [comment]
> Hi I am traying to read a .Key file from my computer but I get always errors like:Cannot read private key. ASN.1 object does not contain an RSAPrivateKey.
> 
> This is part of my code:
> /Lee Key
> function readKeyFromFile(){
> // Get Key
> var fileInput = document.getElementById('keyFile'); //test.key
> var file = fileInput.files[0];
> 
> ```
> // Leer archivo
> var reader = new FileReader();
> reader.onload = function(e) 
> 	{
> 	var contents = e.target.result;
> 	var pkcs12Der = arrayBufferToString(contents)
> 	var pkcs12B64 = forge.util.encode64(pkcs12Der);
> 	var keyPem =  arrayBufferToPrivatePem(pkcs12B64);
> 	
> 		 $('#privateKetTxt').val(pkcs12B64);
> 		 var forgePrivateKey = forge.pki.privateKeyFromPem(keyPem); //<---ERROR
> 
> 	}
> 	reader.readAsArrayBuffer(file);
> }
> ```
> 
> function arrayBufferToPrivatePem (data){
> return '-----BEGIN RSA PRIVATE KEY-----\r\n'
> + data + "\r\n"
> + '-----END RSA PRIVATE KEY-----\r\n';
> }

**Comment by icebergdelphi** [comment]
Solved thanks.

**Comment by osopandacool** [comment]
how did you solve it?
