### ISSUE TITLE
Using Forge with a use-case for Ajax encryption (like aSSL)

### ISSUE THREAD

**Issue by fpietrosanti** [digitalbazaar/forge#84]
It would be very interesting to plan the use of Forge for "unauthenticated SSL with DHE/PFS" for Ajax JS-based applications.

aSSL is an example framework that used this approach http://assl.sullof.com/assl/ .

Obviously aSSL is a kind of custom crypto stuff.

I think that if Forge would be available for use as a wrapper for Ajax application, with some thin server-side layer, it would be of very valuable use.

For example adding opportunistic encryption with unauthenticated TLS with DHE, would provide Perfect Forward Secrecy encryption also for HTTP-only application without using "https" .

This would be of very great help in many case.

What do you think? Which could be the quickest/cleanest way to achieve a goal like this one?

**Comment by dlongley** [comment]
Closing as resolved/external to forge -- links to other issues already exist for adding DHE support to forge in the future.
