### ISSUE TITLE
High, Prototype Pollution in node-forge 

### ISSUE THREAD

**Issue by cjaneway** [digitalbazaar/forge#840]
Package            │ node-forge   
Patched in         │ >= 0.10.0  
Dependency of   | parcel-bundler 
Path                  │ parcel-bundler > node-forge 
More info          │ https://npmjs.com/advisories/1561
Overview
The package node-forge before 0.10.0 is vulnerable to Prototype Pollution via the util.setPath function. Note: Version 0.10.0 is a breaking change removing the vulnerable functions.
Remediation
Upgrade to version 0.10.0 or later.
>> My current version is 0.10.0

**Comment by mattcollier** [comment]
The npm package `parcel-bundler@1.12.4` has a dep of `node-forg@^0.7.1`.  See: https://gist.github.com/mattcollier/69eb6fca3ff36bc1709492210bc8aaf4#file-gistfile1-txt-L81

There is an open PR over there to update: https://github.com/parcel-bundler/parcel/pull/5521

**Comment by davidlehn** [comment]
This appears to have been fixed long ago.
