### ISSUE TITLE
Missing OIDs for surname, title and givenName

### ISSUE THREAD

**Issue by renzenicolai** [digitalbazaar/forge#856]
The OIDs for surname, title and givenName are missing from the list in oids.js.

I need these OIDs to support certificates used by UZI pas cards. UZI pas is a means for Dutch healthcare professionals to identify themselves (see https://www.uziregister.nl/ and https://www.zorgcsp.nl/documents/RK1%20CPS%20UZI-register%20V10.2%20ENG.pdf). But these OIDs are very generic and probably usefull in many other cases.

I've created a PR that adds these missing OIDs: https://github.com/digitalbazaar/forge/pull/855

**Comment by davidlehn** [comment]
Fixed in v1.0.0.
