### ISSUE TITLE
Reconstruct public and private key for re-use later

### ISSUE THREAD

**Issue by nikole-dunixi** [digitalbazaar/forge#87]
Hopefully this isn't too basic a question to ask, however I am having a difficult time figuring out how to reconstruct a the private and public keys after I have used them. I have attempted the following:

``` Javascript
var rsa = forge.pki.rsa;
var keypair = rsa.generateKeyPair({bits: 2048, e: 0x10001});
var ct = keypair.publicKey.encrypt("Arbitrary Message Here");
keypair.privateKey.decrypt(ct);
```

Which outputs: "Arbitrary Message Here" as expected. I have tried to reconstruct the public key this way:

``` Javascript
var nVal = JSON.stringify(keypair.publicKey.n);
var eVal = JSON.stringify(keypair.publicKey.e);
var nwRsa = rsa.setPublicKey(JSON.parse(nHere), JSON.parse(eHere));
var nwCt = nwRsa.encrypt("Arbitrary Message Here"); 
```

When I try to encrypt the message again, I get an error:

``` Javascript
"TypeError: Object #<Object> has no method 'bitLength'"
```

I'm not sure why though, as I believe I have used the method correctly:

``` Javascript
/**
 * Sets an RSA public key from BigIntegers modulus and exponent.
 *
 * @param n the modulus.
 * @param e the exponent.
 *
 * @return the public key.
 */
pki.setRsaPublicKey = pki.rsa.setPublicKey = function(n, e) {
  var key = {
    n: n,
    e: e
  };
```

And I haven't even tried reconstructing the private key yet. I'm not sure what I'm not doing correctly, could you please help me?

Additionally here are the files I'm importing in my html page, I believe I've resolved all dependency issues, but I am unsure:

`````` html
<script src="forge/util.js"></script>
<script src="forge/debug.js"></script>
<script src="forge/jsbn.js"></script>
<script src="forge/oids.js"></script>
<script src="forge/asn1.js"></script>
<script src="forge/sha1.js"></script>
<script src="forge/sha256.js"></script>
<script src="forge/md5.js"></script>
<script src="forge/md.js"></script> 
<script src="forge/aes.js"></script>
<script src="forge/prng.js"></script>
<script src="forge/random.js"></script>
<script src="forge/jsbn.js"></script> 
<script src="forge/pkcs1.js"></script>
<script src="forge/rsa.js"></script>

<script src="forge/des.js"></script>
<script src="forge/rc2.js"></script>
<script src="forge/pbe.js"></script>
<script src="forge/pem.js"></script>
<script src="forge/hmac.js"></script>
<script src="forge/pbkdf2.js"></script>
<script src="forge/pkcs7asn1.js"></script>
<script src="forge/pkcs12.js"></script>
<script src="forge/pss.js"></script>
<script src="forge/mgf1.js"></script>
<script src="forge/mgf.js"></script>
<script src="forge/x509.js"></script>
<script src="forge/pki.js"></script>```
``````

**Comment by bradleyhodges** [comment]
Attempting to decrypt a PEM-formatted, encrypted private key (using `forge.pki.decryptRsaPrivateKey(pem, 'password');`) produces the following error for me: `Uncaught Error: Too few bytes to read ASN.1 value`. Here's what I'm using to encrypt:

    rsa.generateKeyPair({bits: 2048, workers: 2}, function(err, keypair) {
        var publicKey = forge.pki.publicKeyToPem(keypair.publicKey);
        var privateKey = forge.pki.encryptRsaPrivateKey(keypair.privateKey, passphrase);
    });

and decrypt:

    var retrievedKey = this.responseText; // <-- this is the response from an XHR request (it's a string)
    var privateKey = forge.pki.decryptRsaPrivateKey(retrievedKey, passphrase);

Any ideas why this may be occuring, @dlongley?
