### ISSUE TITLE
When will the version be updated? How often is the update?

### ISSUE THREAD

**Issue by MandaJC** [digitalbazaar/forge#882]

**Comment by matth-c3** [comment]
@dhensby / @davidlehn is it possible to get an answer :) ?

Thanks

**Comment by davidlehn** [comment]
We've been busy with many things.  Has been difficult to find time for releases here.  Sorry about that.  Which patches were you interested in specifically?

**Comment by matth-c3** [comment]
Hello @davidlehn , 

I understand, it just that there are several interresting PR like (some from 2019): 

- [Support authority info access x509 v3](https://github.com/digitalbazaar/forge/pull/775)
- [add authenticatedAttribute signingCertificateV2](https://github.com/digitalbazaar/forge/pull/768)
- [Feature/add unauthenticated attributes](https://github.com/digitalbazaar/forge/pull/824)
- [Implement PKCS#7 signature verification](https://github.com/digitalbazaar/forge/pull/706)
- [Allowing to run inside web worker with webpack config](https://github.com/digitalbazaar/forge/pull/819)

and maybe an update on [Switch to ES Modules](https://github.com/digitalbazaar/forge/pull/718) if that's possible. 

Thanks

**Comment by dhensby** [comment]
FYI - @matth-c3 I'm not a maintainer of this repo, so I can't help with this

**Comment by matth-c3** [comment]
Hello @davidlehn , 

Is it possible to get an update please ? 

Thanks

**Comment by matth-c3** [comment]
Hello @petternordholm , @D-Simon94 , 

as you can see the topic was open long time ago, I would be you, I would not expect much ( I dont anymore ).  I think the best for you is to fork it and implement your own change.

**Comment by davidlehn** [comment]
The just released v1.0.0 should fix the "security" issues.  Many other issues are still pending.

**Comment by D-Simon94** [comment]
@davidlehn Thanks for the update!

**Comment by davidlehn** [comment]
I'm going to close this.  Going to try and use [milestones](https://github.com/digitalbazaar/forge/milestones) to track items.  There's a [short term queue](https://github.com/digitalbazaar/forge/milestone/3) and [future queue](https://github.com/digitalbazaar/forge/milestone/2) now.

@matth-c3 Added your [list of items](https://github.com/digitalbazaar/forge/issues/882#issuecomment-868160144) to short term items. But of course it takes time to figure out every issue unless they have clear fixes/features, docs, spec refs, tests, etc to make it easy.

We're cautious updating code here but will try to get things released quicker when we can. Please nag us in individual issues/PRs as needed.
