### ISSUE TITLE
`forge.random.getBytesSync(12) ` returned 19 bytes?

### ISSUE THREAD

**Issue by sify21** [digitalbazaar/forge#903]
I generated a nonce value and want to save it somewhere else. My code is like:
```
let nonce = Buffer.from(forge.random.getBytesSync(12));
```
I found the `Buffer` has 19 bytes, and I have to manually slice it, Why is that?
I'm using latest(0.10.0) forge on node 14.17.0

**Comment by mattcollier** [comment]
forge transacts in "binary encoded strings", here's what you're looking for:
```
const forge = require('node-forge');

const bytes = forge.random.getBytesSync(12);

const m = Buffer.from(bytes, 'binary');

console.log('buffer:', m);
console.log('buffer length:', m.length);
```

https://replit.com/@mattcollier/AdoredUnpleasantAbility#index.js
