### ISSUE TITLE
heads up: domain certificate expired

### ISSUE THREAD

**Issue by DanielRuf** [digitalbazaar/forge#919]
The version without www has an expired certificate: https://digitalbazaar.com/ (expired 61 days ago).

You might want to renew it.

**Comment by davidlehn** [comment]
Hi, I think this is working now.  Please check.  I did see the errors as well, but now it works.  Procrastination fixed it. :-)  I think it might have been some issue with cert caching, older intermediate certs expiring, odd traffic routing, or some combination of that or more.  In any case, probably working now.  If not, please reopen and it would help to know the fingerprints of the certs in the chain.

**Comment by davidlehn** [comment]
I think I fixed the root cause.  If it works for another ~24 hours, then another ~90 days, then we'll know for sure.

**Comment by DanielRuf** [comment]
Looks good now on my smartphone =)

I will give an update tomorrow.
