### ISSUE TITLE
node-forge CVE Vulnerabilities

### ISSUE THREAD

**Issue by dcortinag** [digitalbazaar/forge#951]
Good morning,

I contact to you because I have three CVE issue with node-forge library (version 1.2.1). I downloaded the latest version and Sonar Report shows this:

1.	Filename: node-forge:1.2.1 | Reference: 1006898 | CVSS Score: 4.0 | parseUrl functionality in node-forge mishandles certain uses of backslash such as https:/\/\/\ and interprets the URI as a relative path.

2.	Filename: node-forge:1.2.1 | Reference: 1006854 | CVSS Score: 0.0 | ### Impact The regex used for the `forge.util.parseUrl` API would not properly parse certain inputs resulting in a parsed data structure that could lead to undesired behavior. ### Patches `forge.util.parseUrl` and other very old related URL APIs were removed in 1.0.0 in favor of letting applications use the more modern WHATWG URL Standard API. ### Workarounds Ensure code does not directly or indirectly call `forge.util.parseUrl` with untrusted input. ### References - https://www.huntr.dev/bounties/41852c50-3c6d-4703-8c55-4db27164a4ae/ ### For more information If you have any questions or comments about this advisory: * Open an issue in [forge](https://github.com/digitalbazaar/forge) * Email us at [support@digitalbazaar.com](mailto:support@digitalbazaar.com)

3.	Filename: node-forge:1.2.1 | Reference: 1006852 | CVSS Score: 0.0 | ### Impact The `forge.debug` API had a potential prototype pollution issue if called with untrusted input. The API was only used for internal debug purposes in a safe way and never documented or advertised. It is suspected that uses of this API, if any exist, would likely not have used untrusted inputs in a vulnerable way. ### Patches The `forge.debug` API and related functions were removed in 1.0.0. ### Workarounds Don't use the `forge.debug` API directly or indirectly with untrusted input. ### References - https://www.huntr.dev/bounties/1-npm-node-forge/ ### For more information If you have any questions or comments about this advisory: * Open an issue in [forge](https://github.com/digitalbazaar/forge). * Email us at [support@digitalbazaar.com](mailto:support@digitalbazaar.com).

I searched those issues on internet and the only solution that I found is upgrade to 1.2.1 but I already did this. So, I don’t know what to do to solve it.

Thank you! 

Have a good day.

**Comment by davidlehn** [comment]
I hadn't heard of Sonar Report until now, and don't know it works, or how they determine when issues are fixed.  If forge is updated to 1.2.1 then those issues are fixed.  Maybe there is another older version in your dependency tree?

If any case, while those issues *could* cause security problems, we're still unaware of anyone using the related APIs for any purpose at all. But you should check your code if it's a concern.

**Comment by dcortinag** [comment]
Hi davidlehn,

Thank you for the answer. I checked my dependency tree and I found another version of node-forge in webpack-dev-server@3.11.3
|   `-- selfsigned@1.10.14
|     `-- UNMET DEPENDENCY node-forge@^0.10.0

I delete this dependency tree and it works.

Thank you so much!

Best regards.

David.
