### ISSUE TITLE
Typescript interface for private key `sign()` is incorrect

### ISSUE THREAD

**Issue by petertorelli** [digitalbazaar/forge#964]
The interface for PrivateKey.sign() is defined as:

`sign(md: md.MessageDigest, scheme?: SignatureScheme): Bytes;`

However, if the scheme is `null`, `'NULL'`, or `'NONE'`, in order to pass raw bytes only for padding you must provide `md.digest().getBytes()`, Typescript complains it is not type `MessageDigest`.

**Comment by davidlehn** [comment]
If this is a forge issue could you please provide a short runnable example that shows the problem?

The forge maintainers don't use typescript, so we (or at least I) don't know how to help with related issues.  I'm not sure where that typescript support comes from, but I'd follow up with whoever maintains that info.

**Comment by petertorelli** [comment]
Ah, I was wondering why there was no `index.d.ts` file in this repo. Ok, I'll find out made the `@types` module and file a PR with them. I do think the type switcheroo is a bit confusing, as we go from message digest to bytes, but that's part of the beauty/ugly of JavaScript!

Thanks.
