### ISSUE TITLE
Initialization and SocketPools

### ISSUE THREAD

**Issue by duerig** [digitalbazaar/forge#97]
There are two issues with initialization. First, forge.js does not directly or indirectly include socket.js, so when including it via RequireJS (rather than using script tags to get all the files), forge.net is undefined.

Second, I have not been able to discover the point where it is guaranteed to be safe to call forge.net.createSocketPool() during initialization. It fails with an exception if embedding the SWF object hasn't completed yet.

(1) I call swfobject.embedSWF() immediately when the page loads
(2) When the document.onready handler runs, the SWF object might not be ready
(3) When the embedSWF completion handler itself runs, the SWF object might not be ready

Currently I'm working around this by waiting until the embedSWF completion handler runs, then adding an extra 500 millisecond delay timeout before running createSocketPool(). But this is very ad-hoc.

Is there a best practices here about when to run it? Ideally, that could be added to the documentation. Alternatively, making createSocketPool() itself smarter about initialization so I don't have to care would be great.

**Comment by dlongley** [comment]
Flash support (and socket pools, etc.) will be dropped in a future version, so closing this.
