### ISSUE TITLE
object has no method getInt16le

### ISSUE THREAD

**Issue by govin** [digitalbazaar/forge#99]
I tried to use your RC2 encryption. I get this error - object has no method getInt16le. 

Below is the sample code (in coffee script)

forge = require 'node-forge'
key = forge.random.getBytesSync(16)
iv = forge.random.getBytesSync(8)

cipher = forge.rc2.createEncryptionCipher(key, 'CBC')
cipher.start(iv)
cipher.update(forge.util.createBuffer('Hello World', 'utf-8'))
cipher.finish()
encrypted = cipher.output

console.log(encrypted.toHex())

**Comment by JonahTzuChi** [comment]
I still ran into the issue of getInt16Le is undefined. The root caused was because I read iv in as string type. 
Therefore I have to do the following to convert in to Buffer type.

```
const iv = process.env.AES_IV;
const iv_buffer = Buffer.from(iv);
```
*PS: At the point of writing, `new Buffer(string)` is depreceated.*
