### ISSUE TITLE
 Chinese is not supported RSA sign

### ISSUE THREAD

**Issue by a1031101978** [digitalbazaar/forge#999]
Hopefully can work it out

**Comment by a1031101978** [comment]
PKCS1

**Comment by davidlehn** [comment]
Can you provide a minimal code example?

**Comment by a1031101978** [comment]
let chinese = "中文";
![屏幕截图 2022-09-03 123343](https://user-images.githubusercontent.com/45253733/188256003-3038810f-28a8-42f7-adb8-78e467ddbcc7.png)
![屏幕截图 2022-09-03 123358](https://user-images.githubusercontent.com/45253733/188256004-7b7f0691-1555-4c83-afff-b0f633531aa2.png)
![屏幕截图 2022-09-03 123422](https://user-images.githubusercontent.com/45253733/188256005-91e474a2-e38a-4cdc-97f3-0106a901ce05.png)
![屏幕截图 2022-09-03 123435](https://user-images.githubusercontent.com/45253733/188256006-23e251b7-b4b4-41d4-8804-363baedabc5e.png)

**Comment by a1031101978** [comment]
> Can you provide a minimal code example?

The SIGN I returned with JavaWeb does not contain Chinese and can be passed
![屏幕截图 2022-09-03 125248](https://user-images.githubusercontent.com/45253733/188256429-4c260226-5f39-442e-9dfc-3f777d7ade93.png)
angular:
![屏幕截图 2022-09-03 125303](https://user-images.githubusercontent.com/45253733/188256431-77935f28-1f4d-4770-8361-176c2ca098b9.png)
![屏幕截图 2022-09-03 125202](https://user-images.githubusercontent.com/45253733/188256438-5daa13c3-428e-455c-b3b0-cad788396219.png)
![屏幕截图 2022-09-03 125317](https://user-images.githubusercontent.com/45253733/188256456-89ad16ec-2a0e-43f4-9130-1bf465dbe9e5.png)
Returns false after using Chinese

**Comment by a1031101978** [comment]
> Can you provide a minimal code example?

This is what happens when use Chinese
中文
![屏幕截图 2022-09-03 125918](https://user-images.githubusercontent.com/45253733/188256568-3880ca85-14d4-443f-8fb5-d2d187627cf9.png)
![屏幕截图 2022-09-03 130014](https://user-images.githubusercontent.com/45253733/188256572-b7434d2f-b817-4a7c-b2b0-fda4842f3dcc.png)
![屏幕截图 2022-09-03 130032](https://user-images.githubusercontent.com/45253733/188256576-4e87fbb6-f22b-4e1e-806f-e4a1dc03bd1a.png)

**Comment by dlongley** [comment]
@a1031101978,

Please take a look at these issues: https://github.com/digitalbazaar/forge/issues?q=chinese

You need to convert your character strings into binary-encoded strings (each character uses a character code of 0-255, i.e. a "string of bytes") when using forge. This is because forge was written before `Uint8Array` existed. Therefore, use the UTF-8 encoding APIs to convert a string of characters into a string of bytes before passing the string to the various crypto APIs.

**Comment by akino512** [comment]
@a1031101978 
As @dlongley  said,you should encode those Chinese characters to utf-8 style first.
for encryption  
```js
    const publickeyStr = "<public key...>";
    const plaintextStr = "我爱你";
    const publickey = forge.pki.publicKeyFromPem(publickeyStr);
    const buffer = forge.util.createBuffer();
    buffer.data = forge.util.encodeUtf8(plaintextStr)
    const encryptedStr = forge.util.encode64(publickey.encrypt(buffer.bytes()))
    console.log(encryptedStr);
```
for decryption
```js
    const privatekeyStr = "<private key...>"
    const encryptedStr = "<encrypted string ...>";
    const privateKey = forge.pki.privateKeyFromPem(privatekeyStr);
    const decryptedStr = privateKey.decrypt(forge.util.decode64(encryptedStr))
    const plaintextStr = forge.util.decodeUtf8(decryptedStr)
    console.log(plaintextStr);
```
You can find more detail on this project:
https://github.com/akino512/forge-web

I think this issue should be closed.

**Comment by dlongley** [comment]
Thanks! I agree -- closing.

**Comment by zxhts** [comment]
> @a1031101978 As @dlongley said,you should encode those Chinese characters to utf-8 style first. for encryption
> 
> ```js
>     const publickeyStr = "<public key...>";
>     const plaintextStr = "我爱你";
>     const publickey = forge.pki.publicKeyFromPem(publickeyStr);
>     const buffer = forge.util.createBuffer();
>     buffer.data = forge.util.encodeUtf8(plaintextStr)
>     const encryptedStr = forge.util.encode64(publickey.encrypt(buffer.bytes()))
>     console.log(encryptedStr);
> ```
> 
> for decryption
> 
> ```js
>     const privatekeyStr = "<private key...>"
>     const encryptedStr = "<encrypted string ...>";
>     const privateKey = forge.pki.privateKeyFromPem(privatekeyStr);
>     const decrypted = privateKey.decrypt(forge.util.decode64(encryptedStr))
>     const plaintextStr = forge.util.decodeUtf8(decrypted)
>     console.log(plaintextStr);
> ```
> 
> You can find more detail on this project: https://github.com/akino512/forge-web
> 
> I think this issue should be closed.
